### ISSUE TITLE
No offline page

### ISSUE THREAD

**Issue by klejejs** [home-assistant/home-assistant-android#101]
If Home Assistant server is restarted and you press retry on "Unable to connect" page, you get default error page instead of retry again option.
![Screenshot_20191204-150052](https://user-images.githubusercontent.com/24546950/70144798-5f279300-16a7-11ea-9803-002126c6a5aa.png)

**Comment by JBassett** [comment]
We now give you the option to go to settings if the UI fails to load.
https://github.com/home-assistant/home-assistant-android/pull/249
