### ISSUE TITLE
App closes/crashes when pasting username or password on login

### ISSUE THREAD

**Issue by MerlinXLL** [home-assistant/home-assistant-android#103]
Tested on a Galaxy S9. 

With the newest version 1.1.1, long pressing (copy/paste) either the username or password input-field of the login-view closes/crashes the app. Pasting the URL right before works like a charm.
It was still working in 1.0.0.

Pasting is therefore impossible, which makes it quite difficult to enter long and complex passwords.

**Comment by andriej** [comment]
Also when pasting 2FA code from authenticator.
I've had to re-write it, as it crashed app 3 times when pasting.

**Comment by aleksandrov1995** [comment]
I do have kind of the same issue. Mine is related to when copying or pasting an entity from States page over to the Lovelace raw config. The app crashes on both, when trying to copy from or when trying to paste it to Lovelace.

**Comment by fredamn76** [comment]
I have the same issue.

**Comment by kallangerard** [comment]
Ditto

**Comment by pdecat** [comment]
Reverting commit https://github.com/home-assistant/home-assistant-android/commit/3bc7fdaa11e4a211172cf0930cc399c25b4c83df resolves the issue.

**Comment by balloob** [comment]
@robbiet480 do you know enough Kotlin to be able to fix this, or maybe we should revert it for activities that have webviews?

**Comment by pdecat** [comment]
An alternative maybe to instead use crowdin that does not require using a closed source library at all https://crowdin.com/page/open-source-project-setup-request

**Comment by gotson** [comment]
This is still happening for me on 2 different devices. I have the issue on Oneplus 6T and Samsung galaxy tab s5e. Both are running the latest version 1.3.1 on Android 9, and I am running HA 0.103.3.

The app crashes when trying to long press the password field at login.

**Comment by balloob** [comment]
Please open a new issue as this one has been resolved. Make sure to include logs.
