### ISSUE TITLE
Returning from a websites results in login windows

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant-android#104]
Reproduce:
1. Open app and navigate to any web URL
![Screenshot_20191204-154250](https://user-images.githubusercontent.com/15657682/70152055-cb58c580-16ac-11ea-82ea-82d2fcf6a4f6.png)
2. Click on that link to open the website
3. Use Androids back button to return to HA
4. See the login page

When you close and reopen the app it's logged in again.

**Comment by balloob** [comment]
This is fixed in 103 via https://github.com/home-assistant/home-assistant-polymer/pull/4280

**Comment by Santobert** [comment]
Thanks
