### ISSUE TITLE
Service doesn't start after phone restart

### ISSUE THREAD

**Issue by andriej** [home-assistant/home-assistant-android#108]
I'm currently testing the battery reporting (and location too) and I can see that after reboot entity doesn't get any updates until I run App.

Shouldn't background service start automatically together with the system?

**Comment by SeLLeRoNe** [comment]
It would also be interesting to know how often the App is reporting the battery status and GPS, for battery I would sugget on each update (or when charging state changes, especially when that will be implemented hopefully).

**Comment by SeLLeRoNe** [comment]
I actually noticed that the Battery it is not updated unless the App is opened (it is not updated even if it's in background as far as I can tell).
I did some test leaving the phone discharge and in HA (using only the Mobile App reported value) the battery level has never been updated (tested with 3 hours span), same goes when I charged it.
(OnePlus 5 with Android 9 Oxygen OS 9.0.9)

**Comment by JBassett** [comment]
If you want battery updates outside of location changes I would say create a new issue for that enhancement.  As far as when the battery level gets updated currently, it's whenever we update the location.  I added some extra reboot intents in https://github.com/home-assistant/home-assistant-android/pull/95 but if that's doesn't fix it I'll dig deeper.  @andriej what make, model and os version do you have?

**Comment by SeLLeRoNe** [comment]
Oh ok, sorry I didn't know that, I thought the battery level was indipendent from the GPS, I will open a new issue for that ;)

Cheers

**Comment by andriej** [comment]
@JBassett didn't see your question, but it's android 10 oneplus 6

**Comment by JBassett** [comment]
I added some more intents to the boot handler, try again with latest.

**Comment by SeLLeRoNe** [comment]
When the next version is supposed to be released?
Is there a pre-defined release day that HA uses as standard? (Ex. Every 2 Tuesday)

**Comment by robbiet480** [comment]
It's being released as we speak. It should be available within the next 12 hours.

**Comment by robbiet480** [comment]
Reopening as this is now a issue for notifications too.

**Comment by SeLLeRoNe** [comment]
Cheers :)
Still curious to know if there is a specific day of the week we can usually expect a new update (if available) or if it goes on as soon as a feature is completed :)

**Comment by robbiet480** [comment]
It goes out whenever one of the admins decides to pull the trigger

**Comment by robbiet480** [comment]
After consultation with Justin, we will open a new issue.
