### ISSUE TITLE
Mobile app invalid webhook payload for vertical accuracy

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-android#111]
So I had successfully installed 1.1.1 on a pixel 3 and pixel 4 with location working fine and no errors in my HA logs.  I then decided to install it on my Amazon Fire HD8 that has google services and the play store.  App installed and created a device tracker that did not update.  No errors were seen in the logs.  I then installed google maps on the tablet to see if a missing service was found and the following error shows up now.

`2019-12-04 16:50:13 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Received invalid webhook payload: expected int for dictionary value @ data['vertical_accuracy']. Got None`

This error shows up every few minutes so I suspect the tablet is attempting to send back data but it does not have `vertical_accuracy` to send back. 

I know this is probably a stretch but I think this error should probably be fixed?

**Comment by JBassett** [comment]
Not sure if we can fix that well in app.  Vertical accuracy depends on a certain version of Android and above.  We might need to enhance the mobile app integration to make it optional rather than mandatory.  Or we could hard code an accuracy for devices that don't support it.

**Comment by dshokouhi** [comment]
@JBassett maybe just send back `0` if there is none?  I also wasn't sure where to file this bug.

**Comment by robbiet480** [comment]
@balloob just fixed this in `mobile_app` late last night at https://github.com/home-assistant/home-assistant/pull/29381. Will be in next version of HA, not the app.

**Comment by balloob** [comment]
I fixed allowing `altitude` to be negative. I did not allow `vertical_accuracy` to be None. 

For vertical accuracy, in the Android app can we either send in 0 or not add the key if it's null ?

**Comment by reharmsen** [comment]
When will this be released?
I am noticing this same issue with an Samsung S6, while my Nokia 6 works just fine.

`Received invalid webhook payload: expected int for dictionary value @ data['vertical_accuracy']. Got None`

**Comment by balloob** [comment]
Has been released as 1.1.2

**Comment by djxela** [comment]
`Received invalid webhook payload: required key not provided @ data['device_name']. Got None`

I have this same problem with Samsung S7.  Mobile App version 1.7.2-128
