### ISSUE TITLE
Biometrics Support

### ISSUE THREAD

**Issue by N-Schaef** [home-assistant/home-assistant-android#112]
I'd love it, if we could have an option to secure the app with a fingerprint (or PIN/Password for devices without sensor).

I could take a look if I could do something like that after christmas.

**Comment by dshokouhi** [comment]
actually instead of fingerprint (which uses an older API) this should use the biometrics API so it includes face unlock too

**Comment by julioyg** [comment]
Hi guys, is there anyone working on this? I would happily do it and open a PR if that's ok 😄

**Comment by robbiet480** [comment]
@julioyg PRs gladly accepted

**Comment by julioyg** [comment]
agreed then, I'll try to get something done by this weekend :)

**Comment by JBassett** [comment]
Closed via https://github.com/home-assistant/home-assistant-android/pull/484
