### ISSUE TITLE
Could not connect to HA

### ISSUE THREAD

**Issue by neopilou** [home-assistant/home-assistant-android#115]
I can not connect to Ha on my Teclast X16 Pro tablet with android 5.1. After manually entering and validating the Home Assistant URL, loading start, then the screen remains frozen on "initializing", and I can not enter my login credentials. On Chrome, on the same tablet, or on my Galaxy S5E (with HASS apk) and on my Galaxy S9 + (with HASS apk), and on any browser, HASS will load correctly. I have an HTTPS configuration with a domain name (no-ip.com, like hass.ddns.net) and a letsencrypt certificate, but I'm not sure it has a report.

![Screenshot_2019-12-05-14-51-20](https://user-images.githubusercontent.com/45233613/70242360-fefd2380-1770-11ea-95fb-977946b497c8.png)

**Comment by balloob** [comment]
Make sure that the version of WebView on your Android device is up to date.

https://developer.chrome.com/multidevice/webview/overview

**Comment by neopilou** [comment]
You're right, the version of WebView on my tablet is outdated. And i can't update it (Chinese tablet with intel architecture). 
I will soon buy a new tablet. 
So this is not a bug, you may close this problem.

**Comment by balloob** [comment]
Closing this as it's not an issue with our app. 

Webview is based on Chrome and kept up to date by Google via the Play store.
