### ISSUE TITLE
Support for custom URI schemes

### ISSUE THREAD

**Issue by david81** [home-assistant/home-assistant-android#117]
I'd like to be able to issue commands to Tasker using the autoappscommand custom URI scheme to trigger Tasker actions. This would allow deep integration with the local device to do things like launch other apps, change device settings, etc. from HA buttons.

**Comment by balloob** [comment]
Doesn't this work already? You can add the urls you want to a link in the frontend.

**Comment by david81** [comment]
I can add the urls, yes, but the app doesn't know what to do with them.
![Screenshot_20191205-230335](https://user-images.githubusercontent.com/918769/70295130-d9ddd480-17b3-11ea-8cad-3953b265b158.png)
