### ISSUE TITLE
Device added twice

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/home-assistant-android#123]
I have just tried the new functionality and I noted two things:

1 - The device is added twice:
![image](https://user-images.githubusercontent.com/9599441/70389975-ad4dd680-19c6-11ea-8a78-f718fec5461c.png)

The first one correctly create the device tracker, the second one only report the firmware
![image](https://user-images.githubusercontent.com/9599441/70389989-d2424980-19c6-11ea-8974-17ab08713571.png)
![image](https://user-images.githubusercontent.com/9599441/70389991-d9695780-19c6-11ea-8549-3f251519e799.png)

Battery leve is not present, but in the device_tracker somehow it is:
![image](https://user-images.githubusercontent.com/9599441/70389982-bd65b600-19c6-11ea-81b3-79a6c973e34d.png)

**Comment by balloob** [comment]
The creation of two devices if fixed in the latest HA release.

**Comment by SeLLeRoNe** [comment]
Tested with latest beta and confirm it's now working, it might be nice to have the ability to remove a device rather than having to remove the integration and start over ;)
