### ISSUE TITLE
Changed Hassio IP. App no longer connects.

### ISSUE THREAD

**Issue by vazquezjm** [home-assistant/home-assistant-android#130]
- I installed Hassio on an Ubuntu Server box, got its IP from the DHCP (192.168.1.132)
- Installed Home Assistant for Android, everything worked fine
- Set Hassio a static IP
- Now Android app keeps trying to connect to the previous address

**Screen capture** (sorry, it's in Spanish)
![Screenshot_20191209-171305~2](https://user-images.githubusercontent.com/5269397/70469293-8c10e700-1aa7-11ea-9fd7-a9cdb181b907.png)

Is there any way I can change that IP manually?

**Comment by dshokouhi** [comment]
clear data to change the url, only way for now

**Comment by vazquezjm** [comment]
> clear data to change the url, only way for now

It worked. Thanks
