### ISSUE TITLE
WiFi Connection Status

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/home-assistant-android#131]
Along with many other information the App might be able to report that can become useful for phone tracking and the battery status, it might be also useful to know if the wireless is on/off and/or if the wireless is connected to any wireless (and eventually the SSID) to be able to improve the tracking (ex. GPS details + connected to Home Wireless)

Maybe can be implemented along with battery level and charging state?

Cheers
Andrea

**Comment by dshokouhi** [comment]
WiFi connection status was added in https://github.com/home-assistant/home-assistant-android/pull/336
