### ISSUE TITLE
Can't change server to connect

### ISSUE THREAD

**Issue by Joeri94** [home-assistant/home-assistant-android#133]
Hello,

I'm running Android 10. 
After instaaling the app ant connecting all works fine. But when i logout i can change server to somthing else (like my cloud url).
I have already reinstall the app several times and i'am stuck to the local one.

**Comment by dshokouhi** [comment]
you need to clear data in order to change the URL

**Comment by Joeri94** [comment]
Which data do you mean, I removed the app, delete data from Android we view already end restarted my Phone. But when download (on mobile netwerk) and install Again it says, cant reach server and shows My host adres already.
Thank you for the comment

**Comment by dshokouhi** [comment]
On my phone I just select "Clear Storage" and the first thing the app does is ask me to enter the URL.  I am on a Pixel 4 XL.

**Comment by allanpersson** [comment]
@Joeri94 settings - apps - home assistant - storage - clear data

**Comment by Joeri94** [comment]
Damn now I feel myself total noob, Thanks guys! It workes

**Comment by allanpersson** [comment]
> Damn now I feel myself total noob, Thanks guys! It workes

Don't feel like that 🙏 Helping each other is what makes this community so fantastic and strong 💪 ❤️
