### ISSUE TITLE
Implement full screen of app

### ISSUE THREAD

**Issue by barrymossel** [home-assistant/home-assistant-android#134]
Please implement fullscreen through: https://developer.android.com/training/system-ui/navigation
Should be possible as its also possible for the frontend through Chrome...

**Comment by dshokouhi** [comment]
Duplicate of #59

**Comment by robbiet480** [comment]
Closing in favor of #59

**Comment by barrymossel** [comment]
> Closing in favor of #59

But that one is closed, right. Thought no-one would look there anyway. And I believe the question is mis-understood there. Not the UI should be fullscreen, but rather the app (so the shell). The UI will adapt to the shell anyway I reckon, just like on a monitor...
