### ISSUE TITLE
Duplicate device found

### ISSUE THREAD

**Issue by blakeblackshear** [home-assistant/home-assistant-android#143]
My wife and I both have pixel 3s, and I get an error in the logs on startup about duplicate devices: 

> Found duplicate device name Pixel 3

Is there a way to modify the device name registered in homeassistant?

**Comment by simbesh** [comment]
I had a kind of similar issue, duplicate entries created in core.config_entries for my one device.
Once I deleted the older entry its now working

**Comment by CookieMonster87** [comment]
I also get same error. We both have Galaxy S10 and get the Duplicate name in error log. Tried to delete the core.config_entries file but still get this error.

**Comment by eyeson** [comment]
Also having the same issue, my wife and I hav S9s - can only get notify.xxxx on the first phone to regsiter as 
Found duplicate device name SM-G960F
10:12 AM components/mobile_app/notify.py (WARNING) - message first occurred at 10:12 AM and shows up 2 times
Appeares once I add my wifes.

**Comment by damusmf** [comment]
Same issue here.  You need to edit /config/.storage/core.config_entries.  You will see both devices there.  Change the "device_name" on both of them so they are unique and restart home assistant.  This gives you the 2 service calls and can send notifications to each phone.  However, it doesn't stick so after a restart of HA or 2, you will need to edit the file again.

**Comment by novitibo** [comment]
I wonder if this could be edited in lovelace in near future...
