### ISSUE TITLE
Tiny notifications Icons

### ISSUE THREAD

**Issue by simbesh** [home-assistant/home-assistant-android#144]
OnePlus 7 Pro - Android 10

![image](https://user-images.githubusercontent.com/17171925/70760620-f8386700-1d95-11ea-96dc-770dae4cb4c4.png)
![image](https://user-images.githubusercontent.com/17171925/70760663-1736f900-1d96-11ea-8175-4671a15ee56e.png)

**Comment by robbiet480** [comment]
Working on it literally as I type this

**Comment by robbiet480** [comment]
Fixed via 42d380589ff2eca7a0f724655fe8af30fcec4fae. Will probably push it in the next 24 hours or so. 

![](https://cdn.discordapp.com/attachments/562408603345092636/654852481079181323/Screenshot_20191212-1709042.png)

**Comment by adriancampos** [comment]
Beat me by 4 minutes! Found out as I tried to create the pull request.

Thanks for the quick fix, @robbiet480 .
