### ISSUE TITLE
Notifications coming though but not showing up on screen

### ISSUE THREAD

**Issue by sblfc** [home-assistant/home-assistant-android#146]
When I get a notification I have to pull down the notification bar to see it as my phone just vibrates, would it be possible to make the bubble appear on screen? I'm not sure if this was intended or not but to have this as a configuration option would be very useful.

Thanks

**Comment by mammuth** [comment]
What you're requesting should be [heads-up notifications](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up).

**Comment by sblfc** [comment]
I have figured out how to enable it
![Screenshot_20191218-074327](https://user-images.githubusercontent.com/7306413/71066442-787e1400-216a-11ea-8a86-6eca5e7162f3.jpg)
![Screenshot_20191218-074339](https://user-images.githubusercontent.com/7306413/71066453-816ee580-216a-11ea-9fed-756899f67908.jpg)
![Screenshot_20191218-074346](https://user-images.githubusercontent.com/7306413/71066463-86339980-216a-11ea-8ea1-f0658245e605.jpg)

Make sure pop-up notifications is enabled in the miscellaneous menus (might be on oxygenOS only)

**Comment by JBassett** [comment]
Appears to have fixed via changing system notification settings for the application.
