### ISSUE TITLE
Requested entity was not found - when call notification service

### ISSUE THREAD

**Issue by dmaciaszek** [home-assistant/home-assistant-android#147]
After restart HA I get `notify.mobile_app_*` but when I call it by dev tools with payload `message: 
 testing notification` nothing happen. In log I have error `Requested entity was not found.` Probably it is a bug but maybe I am doing something wrong.

**Comment by dshokouhi** [comment]
One thing you can try doing is clearing data in the app and re-registering. If you do that you will want to remove the old integration as this process will create a new integration.  After you login to the app you will need to restart HA.

**Comment by dmaciaszek** [comment]
Clean up app data, remove old integration and restart HA solve problem as you describe. Thanks.
