### ISSUE TITLE
Logging out and logging back in creates new device_tracker

### ISSUE THREAD

**Issue by PurelyNicole** [home-assistant/home-assistant-android#149]
When I log out of the app, and then log back in, there is a new device_tracker entry, device_tracker.my_phone_2.  This causes any automations/sensors/displays using the initial device tracker to break.

Running app version 1.2.0 on a Pixel 3a.

**Comment by dshokouhi** [comment]
Do you also get a new Integration or just a new entity?

**Comment by PurelyNicole** [comment]
I also get a new integration.

**Comment by dshokouhi** [comment]
Ok I believe this is working as expected then but we can wait for someone else to confirm it.

**Comment by PurelyNicole** [comment]
If that's the case, I'd argue this should be reconsidered.

**Comment by dshokouhi** [comment]
I don't know if its possible because the config entry get a new ID and I am not sure if they are able to get the old ID to link it back.  If for example you clear data the same thing happens.

**Comment by balloob** [comment]
We should include a device ID in the registration so that mobile app can link up new registrations with existing integrations.

**Comment by balloob** [comment]
Written up as https://github.com/home-assistant/home-assistant/issues/29987
