### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-android#159]
Hi
Where is available project to support translation app ?

**Comment by balloob** [comment]
I'ts on Lokalise. URL here: https://lokalise.com/project/145814835dd655bc5ab0d0.36753359/

**Comment by pepeEL** [comment]
k thanks. But how get permission t access ?

**Comment by balloob** [comment]
added you.

**Comment by klejejs** [comment]
I would be happy to help too.

**Comment by pepeEL** [comment]
But there is only Enlish strings... no other languages....

**Comment by balloob** [comment]
Right, each person needs to have their languages added. Which language do you want to translate?

@klejejs what is your lokalise username so I can add you?

**Comment by pepeEL** [comment]
Polish

**Comment by pepeEL** [comment]
Thanks

**Comment by klejejs** [comment]
@balloob My username is my email: krisjanis.lejejs@gmail.com
The language I want to translate is Latvian.

**Comment by klejejs** [comment]
Thank you!

**Comment by Tickaren** [comment]
@balloob can you add Swedish for translation? :)

**Comment by balloob** [comment]
Done.

**Comment by sashao** [comment]
Hi @balloob, I want to help translate this app to Ukrainian, could you please add this lang to localize and assign me to it?
My localize username is "Oleksandr Omelchuk"
Thanks

**Comment by dshokouhi** [comment]
>  I want to help translate this app to Ukrainian, could you please add this lang to localize and assign me to it? My localize username is "Oleksandr Omelchuk" Thanks

done, language added to the project and granted your user name access. As this is a very old issue I am going to lock this now. For future language requests please open a new request on github.
