### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by CedrickFlocon** [home-assistant/home-assistant-android#16]
Update the App icon according to the Android 8 Adaptive icons 
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
[Logo SVG asset](https://github.com/home-assistant/home-assistant-android/files/3821857/logo.svg.zip)

**Comment by BCNelson** [comment]
![Screenshot_1573246649](https://user-images.githubusercontent.com/5659892/68510112-e19b6f00-022f-11ea-8bc1-5a9c9cef99bc.png)
