### ISSUE TITLE
OZW log return blank page

### ISSUE THREAD

**Issue by CookieMonster87** [home-assistant/home-assistant-android#164]
**Home Assistant Android version:**
1.2.0
**Android version:**
10
**Phone model:**
Galaxy S10
**Home Assistant version:**
0.103

**Description of problem:**
When trying to check the OZW log from the app in Z wave control panel, it only returns a blank page. Same issue for previous app versions.

**Comment by balloob** [comment]
Isn't the OZW log opened in a new window on desktop?

**Comment by CookieMonster87** [comment]
Yes opens in new window, Same on mobile browser. Just thinking it should work to check the logs on the mobile app to.

**Comment by balloob** [comment]
This won't work in the app because we are unable to open new windows and share the authentication context. This should be fixed in the frontend in that it should not open the logs in a new window to begin with.

**Comment by balloob** [comment]
Going to close this as it's not an issue for the Android app.
