### ISSUE TITLE
Add support for Cloudflare Access Service Tokens

### ISSUE THREAD

**Issue by gregg098** [home-assistant/home-assistant-android#167]
I use Cloudflare Access to add an additional layer of security before any request is made to my Nginx instance which then goes to Home Assistant. I have read through a few of the other open/closed issues here that are related ([HERE](https://github.com/home-assistant/home-assistant-android/issues/151) and [HERE](https://github.com/home-assistant/home-assistant-android/issues/45) for example), and understand that there is no way to use the workflow with the app right now.

At the same time, Cloudflare Access has the ability to use Service Tokens which give you a way to bypass using Google or whatever auth method is setup in Cloudflare Access, and just pass the token in the header.  See here for more information:
https://developers.cloudflare.com/access/service-auth/service-token/

Is this something that would be able to be added to the app relatively easy?

As an example, I was able to setup GPS Logger to use the token by adding these tokens to the HTTP header in the configuration of that app. Would be nice if there was something similar in this app if realistic.

Thanks.

**Comment by balloob** [comment]
This is not something we can easily add, and its outside of scope of what we want to have in the main app.
