### ISSUE TITLE
Location tracking: validate webhook

### ISSUE THREAD

**Issue by starkillerOG** [home-assistant/home-assistant-android#172]
I just recently started using the android app and it is greath!
Thank you so much for developing this app.

I discovered during the setup of the app that the webhook used to sent location data to HomeAssistant is not checked within the app/does not have perfect error handeling.
If you do not have the "mobile_app" component during setup of the app, location tracking will not work withouth seeing any errors/warnings. If you then add the "mobile_app" component the location tracking will still not work and you will have to completly remove the app and clear the data, go through the setup again to make it work.

**Desired behaviour:**
When sending location data to HomeAssistant through the webhook of NabuCasa there is probably some response message (or there schould be) that tells if the location data has been received correctly by HomeAssistant.
If this response indicates there is a problem, throw an error message in the app or in HomeAssistant and try to setup the webhook again (in the same whay it is done during first install of the app).
Of course if the app does not have a connection to HomeAssistant (because it is not connected through wifi) this retry of the setup can not be done, but it schould then be done the next time an connection is established to HomeAssistant through wifi.
Alternatively the webhook could always (and only) be checked while beeing connected with wifi to HomeAssistant such that an error is detected and fixed as soon as a connection to HomeAssistant with wifi is established.

**Reproduction:**
1) if you already have the app installed, clear the cach and data of the app and remove the app.
2) do not have the "mobile_app" configured in HomeAssistant
3) install the app and go through the setup.
4) realize you need to add "mobile_app" in the HomeAssistant configuration and add it.
5) now location tracking will not work even if you remove and reinstall the app
6) solution: clear the catch and all data of the app again, remove the app and reinstall and go through the setup again.
7) now loacation tracking will work again.

Same thing happens (I think) when i was not yet logged into HomeAssistant cloud account and only logged in to nabucase after intalling and setting up the app.

**Comment by balloob** [comment]
Set up should not finish when the mobile app integration is not loaded. The app should then inform that the user needs to set up the mobile_app integration.

**Comment by SamJongenelen** [comment]
I had the same issue. Ha logs actual null errors.
The fix for me was logging out and in on the app, while mobile_app is registered

**Comment by starkillerOG** [comment]
@balloob I agree, if the mobile_app integration is not set up the mobile app schould not finish its setup but inform the user.

However if a user does not have a cloud account he schould be able to set up the mobile app succesfully for local use (no device tracking).
If that user later decides to get a cloud account the mobile app schould either inform the user to logout/in again to properly setup the webhook, or the mobile app schould just automatically detect that the webhook is not working/not setup and schould set it up correctly.

**Comment by balloob** [comment]
Incorrect. The mobile app integration has nothing to do with the cloud account, it literally exists to create a foundation for mobile apps to integrate. If the mobile app integration is not set up, we should not finish.

**Comment by starkillerOG** [comment]
don't you need a cloud account to setup a webhook in order to use location tracking if you are not connected to the same wifi as your homeassistant instance?

**Comment by balloob** [comment]
Nope. Home Assistant supports webhooks natively. Your instance will need to be remotely accessible if you want to use webhooks outside of your network. With the cloud you can convert webhooks to cloudhooks, that are accessible outside of your network (and mobile_app does this automatically if it's available).

**Comment by starkillerOG** [comment]
Thanks for the explanation I get it.
So if you use HomeAssistant only locally (not remotely accessible) and have a cloud account, the mobile_app automatically sets-up a couldwebhook that redirects trafic to the local HomeAssistant webhook, but this set-up of the cloudwebhook is only done during the first setup (onboarding) of the mobile_app.
Right?

So if you setup the cloud account later (after the mobile_app setup) this cloudwebhook will not be created automatically?

**Comment by balloob** [comment]
That is correct and a current limitation.

**Comment by starkillerOG** [comment]
Thank you, I understand.

So for now:
- it would be usefull to stop the setup of the phone application if mobile_app is not setup in HomeAssistant and open a prompt in the app to let user now to set it up.

for later:
- it would be nice if eventually the cloudwebhook would be automatically setup if the cloud account becomes available after the phone application is already setup.

**Comment by JBassett** [comment]
Right now we should display an error saying that we were unable to setup the integration when you are setting up the application with a retry button so that after you enable the component in HA you can retry the integration.

**Comment by balloob** [comment]
Retry is possible, but it also complicates things. I would just abort the onboarding.

**Comment by balloob** [comment]
btw, we have this string, is it not used? https://github.com/home-assistant/home-assistant-android/blob/4f34a9b67f542b6d414aab9da50f03c9ac5d8b46/app/src/main/res/values/strings.xml#L20-L21

**Comment by JBassett** [comment]
We use it here:
https://github.com/home-assistant/home-assistant-android/blob/4f34a9b67f542b6d414aab9da50f03c9ac5d8b46/app/src/main/res/layout/fragment_mobile_app_integration.xml#L46-L56
This fragment view has the retry or skip choice after it fails to register with the integration.

**Comment by balloob** [comment]
Okay, we should not offer a skip choice there and just abort onboarding and revoke the token. The user can always log in a second time.

**Comment by starkillerOG** [comment]
I agree with balloob

**Comment by JBassett** [comment]
Closing because we no longer allow you not to have the mobile_app component.
