### ISSUE TITLE
Implement notification with 'request_location_update' functionality

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/home-assistant-android#176]
**Home Assistant Android version:**
1.2.0 (42)
**Android version:**
10
**Phone model:**
pixel2

**Home Assistant version:**
0.103.0

**Description of problem:**

~~when sending _request_location_update_ message body to the android app, I get the notification delivered with a message body _request_location_update_. 
Is this the expected behavior ? How can i confirm my location is being asked? Or is this not yet supported on the Android version of the app?~~
not yet supported functionality. This ticket is became the enhancement request

**Traceback (if applicable):**

```

```

**Additional information:**
I am using a HA API call (using NodeRed). The following payload is being sent:

```
{"domain":"notify","service":"mobile_app_pixel_2","data":{"message":"request_location_update"}}
```

**Comment by balloob** [comment]
This is not supported. Is this a feature that is supported on iOS?

**Comment by SamJongenelen** [comment]
Im trying to implement _https://companion.home-assistant.io/en/notifications/location_. 

The feature would be useful for me when trying to locate someone _n_ min after wifi disconnect

**Comment by dshokouhi** [comment]
This could be interesting, does the notification just stay on the device until the user dismisses it?  I wonder what the iOS behavior is like here.

**Comment by SeanPM5** [comment]
The way it works in the iOS app, the notification isn't supposed to show up on the lock screen at all or require any user interaction. It's supposed to be a completely invisible method of updating your location for use in automations and scripts etc.

For certain automations you want to ensure the location data is completely fresh and that's where `request_location_update` is useful. I use it to track precisely where I parked my car for example ([screenshot](https://pbs.twimg.com/media/D-HJ2X9XkAEh2u7?format=jpg&name=4096x4096) from a few months ago). 

I'm not entirely sure how it all works behind the scenes but I believe that @robbiet480  suppresses the notification somehow on the Firebase side of things, so maybe that has to be done for the Android app too?

**Comment by robbiet480** [comment]
This functionality needs to be implemented in the Android app before it will work.

**Comment by Mic92** [comment]
Some special handling could be added here: https://github.com/home-assistant/home-assistant-android/blob/dfb03e32e088b28304dd2bdaa728420b9acf36d4/app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt#L52

**Comment by Mic92** [comment]
I also implemented something: https://github.com/home-assistant/home-assistant-android/pull/333

**Comment by JBassett** [comment]
Fixed via https://github.com/home-assistant/home-assistant-android/pull/333
