### ISSUE TITLE
Allow App to trust Android platform user-type certificate store

### ISSUE THREAD

**Issue by roseaxl** [home-assistant/home-assistant-android#184]
Setup:
SSL/TLS Certificate issued by organization/entity non-public Certificate Authority is used for securing the HTTP service of Home Assistant web server.  
The certificate is fully featured and enables HTTP/S access and encrypts network traffic to/from Home Assistant web server.

Observed Issue:  

1) When logging in Homeassistant a blank page is produced and error is thrown in the android app logs.

2) The Certificate Authority that issued the TLS/SSL certificate is not present in the Android Phone's "System Certificate Authority list" but present in the Android Phone's "User Certificate Authority list". This configuration does not work with Home Assistant Android App.

Note: This is not to be confused with self-signed certificates as it is a different case.

Root cause of the issue: 

By default, Android apps only use the Android system certificate store on Android 7.0+
To use the Android user certificate store, apps need to specify this in their Network Security Configuration. 

The default configuration for apps targeting Android 7.0 (API level 24) to Android 8.1 (API level 27) is as follows:

base-config 
    trust-anchors
        certificates src "system" 
    trust-anchors
base-config ...

The default configuration for apps targeting Android 6.0 (API level 23) and lower is as follows:

...base
        certificates src="system" 
        certificates src="user"
    trust-anchors
base-config ...

ref. url 
https://developer.android.com/training/articles/security-config.html

With no way to make apps trust the user-installed certificates, users have no choice but to accept the app failing. So far, when a device did something like this, the general advice to non-technical people was "just use the browser" or "sorry, that doesn't work on your device".

Optional resolution: 
Adding "certificates src="user"  (as referenced above) allows the Android App to trust also the Android user's certificate store. Only the user of the Android device have access to that user certificate store, nobody else can import CA certificates there and break security or introduce harmful behavior.

Effect: 
This would give the ability for the App to function with user's own Certificate Authority and trust 
only SSL certs issued by user's pproved Certificate Authority.

It is a valid business and technical case, for an organization or a single entity/person to have their own Certificate Authority and issue ssl/tls certificates to secure their own web servers.

**Comment by reharmsen** [comment]
Looks as same issue as #171

**Comment by urusha** [comment]
It's more about #48

**Comment by roseaxl** [comment]
I guess both would apply, but would like to confirm it has nothing with self signed certs alone. Which seems to scare people off.

I see now that there is a fork with this option which works but I cannot understand why the devs behind the official app do not want to integrate it.
It is not introducing MITM at all if only the android user has control over their device.

**Comment by JBassett** [comment]
It's not that we don't want to support self signed certificates.  We want to make sure that whatever changes are made are made correctly.

**Comment by roseaxl** [comment]
A self signed certificate is one that is not issued by a certificate authority.

This primary change in reference is actually about allowing an organization or persons own certificate authority and a cert signed by a certificate authority.
