### ISSUE TITLE
Feature: home screen widgets

### ISSUE THREAD

**Issue by urusha** [home-assistant/home-assistant-android#186]
It would be nice to have an ability to add widgets to android home screen.
Informational - data from sensors/other entities.
Control - turning switches/lights/groups/automations on/off/run, media player play/stop/back/forward/volume/source/on/off, etc.

**Comment by Quantum-cross** [comment]
Not sure if I should make another issue about this -- but it looks like you can make custom quick tiles in the notification bar too. That would be really rad as well.

**Comment by dshokouhi** [comment]
I think we can close this since we have widgets now?
