### ISSUE TITLE
Scrolling through large logs og addons lags 

### ISSUE THREAD

**Issue by CodeFinder2** [home-assistant/home-assistant-android#187]
**Home Assistant Android version:**  v1.3.1 (57)

**Android version:** 9

**Phone model:** OnePlus 3T

**Home Assistant version:** 0.103.3

**Last working Home Assistant release (if known):** n/a

**Description of problem:** When I scroll through a long log/output of a HASSIO addon, it lags a lot and scrolling is very slow. Really difficult to get to the end of the output. 

**Traceback (if applicable):** n/a

```

```

**Additional information:**

EDIT: the app sometimes even freezes completely and I have to restart it by swiping it from androids task mgr.

**Comment by balloob** [comment]
Can you reproduce this in the Chrome app ?

**Comment by CodeFinder2** [comment]
Yes! It's latest Chrome v79.0.39.45.93.

Is it related to Chrome then? 🙈

**Comment by quthla** [comment]
Try disabling any accessibility services. If that improves the situation, you're experiencing https://bugs.chromium.org/p/chromium/issues/detail?id=1014945

You must and should complain there then because Chrome devs don't really care so far though

**Comment by CodeFinder2** [comment]
Thanks for your quick reply! Where do I disable such services? Is it just an option inside the Chrome app? I disabled "AutoFill" as mentioned in your linked page but that does not solve the issue. My other "accessibility services" seem to be off, see following screenshots (sry, it's German).

![photo_2019-12-22_14-31-10](https://user-images.githubusercontent.com/20599588/71322431-c3c85780-24c7-11ea-8002-917b98fdf405.jpg)
![photo_2019-12-22_14-31-18](https://user-images.githubusercontent.com/20599588/71322432-c5921b00-24c7-11ea-8466-38b98e248ea3.jpg)

**Comment by quthla** [comment]
https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker

Can you open this site without Chrome crashing?

**Comment by CodeFinder2** [comment]
Yes and I can scroll until the end of that page quite fluently. AutoFill enabled. Accessibility services as in the screenshot above.

**Comment by quthla** [comment]
I guess it's a different issue then. You can try your usecase with another browser not based on Chromium, like Firefox Previewo or so. If you can browse your logs without issues then, you should open an issue on the Chromium bugtracker.

**Comment by balloob** [comment]
The webview that we use is using an engine similar to Chrome. Since you experience it in Chrome, it's clear that it's not the app (since we don't make any changes to the webview, that would also be surprising)

**Comment by CodeFinder2** [comment]
Would it be possible to make the engine configurable, so that I can also switch to, eg Firefox?

I use Chrome as my daily driver but for Home Assistant, it really sucks (reloading sometimes takes plenty of seconds, scrolling issues, editing issues in Lovelace configs, buttons not being visible / rendered correctly,... )... 🙄

**Comment by CodeFinder2** [comment]
This issue seems to be gone (maybe Chrome and/or the App was updated). Scrolling is very fluent now.
