### ISSUE TITLE
Unable to Register Application

### ISSUE THREAD

**Issue by CyanoFresh** [home-assistant/home-assistant-android#190]
**Home Assistant Android version:**
1.3.1 also tried 1.3.1 (59)
**Android version:**
9
**Phone model:**
Xiaomi Mi6
**Home Assistant version:**
0.103.3
**Last working Home Assistant release (if known):**
Works fine with HA Client from Play Store
**Description of problem:**
After starting the app it scans the network but doesn't find my HA instance. I type address manually (domain + nginx + https, but also tried default installation with ip:port). Then type username and password and then I get this error: 
![photo_2019-12-22_18-38-55](https://user-images.githubusercontent.com/4249082/71324669-511ca380-24ea-11ea-8010-11e89cc1652e.jpg)
`default_config` is in my config.yaml. Also tried to add `mobile_app` but it doesn't help. Tried all methods from https://community.home-assistant.io/t/mobile-app-integration-not-working/150683/35 but same result. 
Also checked `mobile_app`  in `/api/config` and it is there.
Tried HA Client https://play.google.com/store/apps/details?id=com.keyboardcrumbs.haclient&hl=ru and it works fine (adds integration, tracks, etc.)

**Additional information:**
Update: tried on few other devices (samsung) and it works fine on them. How I can debug it on my xiaomi mi 6?

**Comment by balloob** [comment]
Any error in your Home Assistant logs related to mobile app ?

**Comment by CyanoFresh** [comment]
no errors

**Comment by JBassett** [comment]
Can you give us an example of the url and ip string you are using?
If possible can you get adb logs from the device while trying to connect?

**Comment by CyanoFresh** [comment]
I type this: `https://home.mydomain.com`
Can you please give a link for tutorial how to get this logs right?

**Comment by CyanoFresh** [comment]
hmm, updated yo MIUI 11 and now it works, sorry.
Thanks for great app btw!

**Comment by allard-code** [comment]
@CyanoFresh I'm also on MIUI 11 and it still doesn't work. How did you fix it?

**Comment by CyanoFresh** [comment]
> @CyanoFresh I'm also on MIUI 11 and it still doesn't work. How did you fix it?

Just reinstalled OS with full wipe. 

I think my problem was in cluttered previous MIUI installation as some other functions were not working too.

**Comment by farazfiazi** [comment]
i have the same issue..
can anyone help me.
Please
