### ISSUE TITLE
BUG/FR - Improve Notification's Service Naming

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/home-assistant-android#191]
Hi there,

I just realized that for notification I don't have to enable it on my profile but it does create a service with the device model.

I can see some issue with that, for instance if two devices share the same model number.
I would suggest to use the "device_tracker" name (the one after the .) so that each device got it's own unique service
(ex. I call my device device_tracker.andrea_oneplus5 and it would make sense if the notifiy service for that device is notify.mobile_app_andrea_oneplus5 (or even better, notify.andrea_oneplus5).

Additionally, it might also be "easier" to manage a generic "notify.mobile_app" service where you can select in the payload the entity_id (device_tracker.andrea_oneplsu5 or notify.andrea_oneplus5) so that there are not tons of services created and each user can define groups and which device to call also using variables or other logic).

Hope it makes sense :)

Cheers and thanks!
Andrea

**Comment by dshokouhi** [comment]
If you update to the latest app version you can head over to App Configuration and change the device name, then restart HA and you will see the notify service change.

**Comment by JBassett** [comment]
Like @dshokouhi stated, if you go to App Configuration and update the device name and restart HA it will update the service name.  As far as an enhancement to the mobile_app integration that should go to the main Home Assistant repository.

**Comment by SeLLeRoNe** [comment]
Hi, thanks for the response.
I did set the device name but even after a restart I don't see the service "per-device-name" but still as "model number".
Should I remove the integration are re-do it via the App (logout and login)?

Regarding the enhancement I will open the ticket on the main repo.

**Comment by JBassett** [comment]
The issue you are having with the device_tracker entity can be solved by just renaming the entity in home assistant.

**Comment by SeLLeRoNe** [comment]
Let me try to clarify, devices name are already customized but still doesn't work as I understood it already should:

On the phone side, in within the App, the device name is set to "Sonia - Mi 9T Pro), same in HA.
![image](https://user-images.githubusercontent.com/9599441/71341400-0cc8ec00-255a-11ea-9850-05cdb0fa2622.png)

But the service is somehow generic:
![image](https://user-images.githubusercontent.com/9599441/71341439-2a965100-255a-11ea-9b2f-89abddb81977.png)

And it is using the device model set in the integration:
![image](https://user-images.githubusercontent.com/9599441/71341464-3c77f400-255a-11ea-8b6e-f64518c6acda.png)



![image](https://user-images.githubusercontent.com/9599441/71341553-7b0dae80-255a-11ea-8c9a-14b47ad1bd94.png)


Same goes for instance for my tablet:
![image](https://user-images.githubusercontent.com/9599441/71341482-4d286a00-255a-11ea-8176-0c505595df4a.png)

![image](https://user-images.githubusercontent.com/9599441/71341517-5e717680-255a-11ea-8758-d4ef672abb37.png)

![image](https://user-images.githubusercontent.com/9599441/71341532-6a5d3880-255a-11ea-9a38-77069ecc2dad.png)

![image](https://user-images.githubusercontent.com/9599441/71341546-721cdd00-255a-11ea-9b6d-c3f1f7b39218.png)


So, even if I have customized the names, the service remain generic for the model, which make me think it might also cause issue for multiple devices with same model.

Thanks :)

Andrea
