### ISSUE TITLE
location not updating for Android 10 pixel devices

### ISSUE THREAD

**Issue by jon-zimperium** [home-assistant/home-assistant-android#192]
**Home Assistant Android version:**
1.31 (57)

**Android version:**
10 - December patch
**Phone model:**
Pixel 2XL, 3XL, 4XL
**Home Assistant version:**
103
**Last working Home Assistant release (if known):**

**Description of problem:**
Location is not updating for any pixel devices running android 10.  Permission to get location in background is enabled in the app, and the OS permission control is set to get location when not using the app.  The battery level does seem to be updating periodically.
**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by JBassett** [comment]
If the battery is updating then you are getting updates from the phone.  If you aren't entering or exiting a HA zone then the state of the device_tracker will not change.  However if you put a template sensor on the GPS coordinates they should still be updating.

**Comment by jon-zimperium** [comment]
thanks @JBassett .  I am looking at the location co-ordinates, and they are not accurate.  They show that devices are at the home location when I know they are several miles away.  How often does the app check in / on what triggers?

**Comment by balloob** [comment]
Make sure you check the location in the state machine. If the location of an entity + accuracy overlaps with the home zone, the entity is considered home.

**Comment by jonpaterson** [comment]
I believe this issue may be due to how background services are started in Android 10.  I just performed a test and it was not updating for a rebooted device.  If I open the app - it is updating.  perhaps related to this? https://stackoverflow.com/questions/58362719/how-can-i-start-android-application-on-device-boot

the Pixel devices (along with other manufacturers) have aggressive memory management and will kill apps without foreground services, or excluded from battery optimization.  I am testing the app with battery optimization disabled to see if this helps.

**Comment by JBassett** [comment]
I just validated everything is starting on reboot with a Pixel 2.  I did however notice that the accuracy very poor until another application requests a more precise location.  So poor that it won't actually send to HA.  On boot we could request a single accurate location which would help.

**Comment by jonpaterson** [comment]
The app is definately getting managed out by memory management.  My son's phone (who plays games a lot using memory) (Pixel 2XL) still shows at a friends house he was at several hours ago.  I think that the only way around this is additional callbacks to the app (wifi network change etc..), excluding from memory "optimization" or having some persistant notification system that keeps it from being pushed out.  I am going to set all phones to not optimized for the next few days and will report back.

**Comment by jonpaterson** [comment]
@JBassett I saw the same behavior now with my daughters pixel 3XL, she also plays games on the phone.  she was shown at a location that was from several hours ago.  As soon as I had her open the app it was correctly reflected.  I have had luck testing on one phone excluding the app from "optimization" , but perhaps other ways to callback the app (network change, device unlock etc) would allow it to wake long enough to update the location

**Comment by heytcass** [comment]
I also experience this issue, both on my 4Xl and my wife's 3. Opening the app on my phone updates correctly, but it would be extremely rare that my wife opens the app, thus defeating the purpose. Location permissions are correctly set, and set to High-accuracy. Have also tried both zone-based and continuous tracking in the HA app itself, but neither helps.
