### ISSUE TITLE
duplicate / secondary objects created in UI for same phone app install

### ISSUE THREAD

**Issue by jonpaterson** [home-assistant/home-assistant-android#193]
**Home Assistant Android version:**
1.3.1(57)
**Android version:**
10
**Phone model:**
Pixel 4 XL
**Home Assistant version:**
103
**Last working Home Assistant release (if known):**

**Description of problem:**
for 2 of my devices, it shows two items for the same phone.  The second item does not have any details or device tracker definition other than the Android API level.  The battery level is never shown for any devices in the UI.

![image](https://user-images.githubusercontent.com/10554323/71325844-5660fa80-24b8-11ea-9dee-1728e20335de.png)

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by jonpaterson** [comment]
secondary object 
![image](https://user-images.githubusercontent.com/10554323/71325857-7e505e00-24b8-11ea-810a-16e4a21f0ec7.png)

**Comment by JBassett** [comment]
This was a known issue in HA version 103.0 it was fixed in 103.1 and above.  After updating HA version you will need to delete the integration, clear data on the app, and re sign in.
