### ISSUE TITLE
unable to enable notifications - slider "jams".

### ISSUE THREAD

**Issue by jonpaterson** [home-assistant/home-assistant-android#199]
**Home Assistant Android version:**
1.3.1 (57)

**Android version:**
10
**Phone model:**
Pixel 4 XL
**Home Assistant version:**
103
**Last working Home Assistant release (if known):**

**Description of problem:**
Unable to enable notifications in the android app. The slider "sticks" and never completes configuration.  I can enable notifications via the HTML5 app without problem. I am using a valid publicly verifiable cert via letsencrypt.

Native app stuck:
![image](https://user-images.githubusercontent.com/10554323/71373296-53c7d900-257c-11ea-8f2c-f22b6f2e19c6.png)

working in the HTML5 app:

![image](https://user-images.githubusercontent.com/10554323/71373335-7659f200-257c-11ea-96cb-d552c11140c0.png)

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by JBassett** [comment]
That switch is only for html5 notifications, here is the documentation for native push notifications.
https://companion.home-assistant.io/en/notifications/basic.html

Currently we only support super basic notifications; title, message, image (not currently in documentation)

**Comment by jonpaterson** [comment]
thanks @JBassett I did look around for info on this but could not locate it  It would be good to add this link to the Github project also.

**Comment by JBassett** [comment]
@jonpaterson https://github.com/home-assistant/home-assistant-android/pull/200
