### ISSUE TITLE
Add support for reporting alarms, charging and telephony states

### ISSUE THREAD

**Issue by tiagofreire-pt** [home-assistant/home-assistant-android#201]
**Home Assistant Android version:** 
Last commit available on github.

**Android version:**
9.0

**Phone model:**
Samsung Galaxy J7 2017

**Home Assistant version:**
0.103.4

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**

The full integration of an android smartphone with its main status reported to Home Assistant would improve the data available for automations regarding the phone states:

The android intents for Alarms (specifically for Samsung phones using the manufaturer alarm clock app):
- com.samsung.sec.android.clockpackage.alarm_ALARM_STOPPED_IN_ALERT
- com.samsung.sec.android.clockpackage.alarm_ALARM_ALERT

The ones for the charging plug:
- android.intent.action.ACTION_POWER_CONNECTED
- android.intent.action.ACTION_POWER_DISCONNECTED

For in-out call/ring state (https://developer.android.com/reference/android/telephony/TelephonyManager):

- android.intent.action.ACTION_PHONE_STATE_CHANGED (https://developer.android.com/reference/android/telephony/TelephonyManager.html#ACTION_PHONE_STATE_CHANGED)

For most of these intents I have integration through MQTT, except the android.intent.action.ACTION_PHONE_STATE_CHANGED that requires some permissions on android manifest non-existant in the [PlayStore app available](https://play.google.com/store/apps/details?id=pixento.nl.broadcasttomqtt&hl=en). 

This full integration on the HA app would require less complexity, resources used by a bunch of apps and generally more efficient workflow and HA configuration.

**Comment by tiagofreire-pt** [comment]
Android alarm intents:
com.android.alarmclock.ALARM_ALERT
com.android.deskclock.ALARM_ALERT

Sony alarm intent:
com.sonyericsson.alarm.ALARM_ALERT

**Comment by dshokouhi** [comment]
Charging status was added in https://github.com/home-assistant/home-assistant-android/pull/336

**Comment by tiagofreire-pt** [comment]
@balloob , this is also about so many other states for the phone, not just the charging one.

My proposal is to evaluate the value to report the states for the examples provided above, related to android intents.

Please, re-consider opening this issue.

Thanks.

**Comment by balloob** [comment]
We should have 1 thing per issue. Please open a new issue for the other things.
