### ISSUE TITLE
Feature request: add swipe gesture to change between Lovelace tabs

### ISSUE THREAD

**Issue by CodeFinder2** [home-assistant/home-assistant-android#202]
**Home Assistant Android version:** v1.3.1 (57)

**Android version:** 9

**Phone model:** OnePlus 3T

**Home Assistant version:** 0.103.4

**Last working Home Assistant release (if known):** none.

**Description of problem:** No problem but a feature request. It would be really nice to allow switching tabs on the Lovelace UI using a left or right swipe gesture. Similar to changing tabs in Chrome by swiping to the left or right on the address bar.  Thank you so much!

**Traceback (if applicable):** none.

**Additional information:** none.

**Comment by aleksandrov1995** [comment]
There is a custom component https://github.com/maykar/lovelace-swipe-navigation which allows for just that.

**Comment by CodeFinder2** [comment]
Great, thanks!

**Comment by duesseldorferjung** [comment]
are there any plans to include that in the app itself?
