### ISSUE TITLE
App being pushed to Firebase app distribution for irrelevant changes

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/home-assistant-android#205]
**Home Assistant Android version:**
1.3.1 (63)

**Android version:**
9

**Phone model:**
Huawei Mate 20 Pro

**Home Assistant version:**
0.103.3

**Last working Home Assistant release (if known):**

**Description of problem:**
I am currently running the dev releases, via Firebase App Distribution and it appears that currently *every* commit triggers a push of the app, even if the changes don't affect the app in any way. 
For example, I had an update to 1.3.1 (63) today when it appears that the only change was to the README.md file.

Can pushes be limited to only changes that actually affect the app?

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by balloob** [comment]
Commits will need to be tagged with skip ci in message. It's also not so bad, one commit that only changed readme 🤷‍♂️
