### ISSUE TITLE
Image not always working

### ISSUE THREAD

**Issue by Ulrar** [home-assistant/home-assistant-android#208]
**Home Assistant Android version:**
1.3.1
**Android version:**
10
**Phone model:**
pixel 3 XL
**Home Assistant version:**
 0.103.5 
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
I'm using nodered to write snapshots of motion detection from an IP camera. The actual file is valid and served from the home assistant www directory, and the links passed to the app are returning valid jpeg files.

Some notifications don't show the picture, just the text. No errors or any way to know which link did not work, or why.
**Traceback (if applicable):**

```

```

**Additional information:**
Is there a debug mode I could use to know why the picture link is ignored by the app sometimes ?
Most times it does work.

thanks

**Comment by jes1417** [comment]
I have not been able to pass an image to the app notification at all, even just testing in dev tools, services. The same image works in my push notifications though.

**Comment by andriej** [comment]
@jes1417 those are not supported by app yet (notification images and other attributes)

**Comment by dshokouhi** [comment]
You can send an image using the android app.  You need to make sure to use the full external URL for the image.

Here is an example of the data you can send:

```
      message: "test"
      title: "test"
      data:
        android:
          notification:
            image: "https://i.imgur.com/2wS3Jht.jpg"
```

**Comment by Ulrar** [comment]
Yes, using that format images do work fine, sometimes. And sometimes the
notification shows up with just the text, no image and no error to figure
out what went wrong

**Comment by balloob** [comment]
the url you use for your image needs to be accessible by your phone. So if it's an internal network url, your phone needs to be there too.

Please share the image url that you'er using.

**Comment by Ulrar** [comment]
The URL is accessible by my phone, it's served by the HA instance directly,
I just have node red write the image in HA's www.

And I did test all the links it sends (by adding a debug to the nodered
flow to show the generated API call, with the full image link) to the
application, they are returning valid jpeg files both internally and
externally.

I can't share the link as it's images from my camera, but I did test all of
this. The links are valid and working when the app shows only text. I also
made sure the notification is only sent after the image is written to disk,
as I thought it might be getting an incomplete image but that's not it.

Is there a debug mode I could enable in the app to get the error message it
gets (if any) when loading the image ?

**Comment by mamrai1** [comment]
Yes I can confirm this bugs exists.. The image is sent if receiving device is on same Lan with HA. If not the image is missing. With my ios devices works ok

**Comment by Ulrar** [comment]
Hi,

Nothing to do with the network, I get images both from internal or
external, it's just sending a link to the app.
The link is valid and accessible from anywhere, sometimes it just fails
with no explanation when fetching it though

**Comment by shbatm** [comment]
I'm having issues receiving images in the notifications as well (Samsung Galaxy S9+, v 1.6.0-105). 

Example from @dshokouhi above fails, as does using Node-RED to send image with a publicly accessible link to a camera image.

**Comment by dshokouhi** [comment]
@shbatm it changed earlier today actually, docs are not updated yet but you can use:

```
      message: "test"
      title: "test"
      data:
        image: "https://i.imgur.com/2wS3Jht.jpg"
```

**Comment by shbatm** [comment]
@dshokouhi I guess it figures that I waited until today to try. It's working. Thanks!

**Comment by dshokouhi** [comment]
@Ulrar there were some updates done recently in the lastest firebase builds and on the FCM side. Can you check it out with the new configuration? Check the Android example for the new format: https://companion.home-assistant.io/en/notifications/attachments
