### ISSUE TITLE
Unable to modify input_datetime 

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/home-assistant-android#210]
**Home Assistant Android version:**
1.3.1 (65) via AppTester
**Android version:**
9 (OxygenOS 9.0.9
**Phone model:**
OnePlus 5
**Home Assistant version:**
103.5
**Last working Home Assistant release (if known):**

**Description of problem:**
Everytime you have to change a input_datetime (only a time one tested), the keyboard popup and immediatly close, preventing you to change the value
Also would be nice if in those fields that are technically number-only, if the number-only keypad popups up instead of the whole keyboard.
**Traceback (if applicable):**

```
N/A
```

**Additional information:**

**Comment by ve6rah** [comment]
Possibly the same issue here, I find trying to modify a time field causes the entire app to crash.
