### ISSUE TITLE
Enable client SSL/certificate/auth support

### ISSUE THREAD

**Issue by cicavey** [home-assistant/home-assistant-android#214]
I protect my hosted services behind two-way / client SSL. This is a very convenient method of authenticate for me. This application currently does not support client SSL. Nor does HASS itself, but that's an issue for a different repo. I am content for now allowing the selection of a client cert and then entering normal HASS credentials.

A bit of research turned up the following:

https://developer.android.com/reference/android/webkit/WebViewClient.html#onReceivedClientCertRequest(android.webkit.WebView,%20android.webkit.ClientCertRequest)

which in turn links directly to an example which may simply be a copy/paste exercise:

https://android.googlesource.com/platform/packages/apps/Browser/+/android-5.1.1_r1/src/com/android/browser/Tab.java#573

I may attempt to submit a PR if I get the chance. It seems fairly straightforward.

**Comment by balloob** [comment]
This is not a feature we want to have in the official app. It creates complexity and we have other priorities now.

**Comment by cicavey** [comment]
I understand priorities. I manage a large backlog of my own at work. But why close the issue? I'd rather include detail in this ticket about the subtleties and complexity than simply close the ticket. It's a feature request that anyone could pickup maybe even something like hacktoberfest next year.

I'm not suggesting that the application itself needs to manage client certs. At most remember the key alias. You simply defer to the to the system key manager which has its own Activity to select keys/certs. Users that don't use client certs would never even see the prompt.

I started looking into to implementing this and perhaps the complexity is more subtle than my naive Android development skills. Would you consider a PR if I implemented this?

**Comment by balloob** [comment]
Closed this because we won't consider a PR right now.

**Comment by cicavey** [comment]
Fair enough. I appreciate the honesty.

**Comment by inspire1989** [comment]
I would also love to have this feature! Can't use the app because of the client certificate I am using...

**Comment by maciekczwa** [comment]
I did some testing about that.
It is not that simple as adding certificate chooser to webview.

Application is also using OkHttpClient in HomeAssistantRetrofit so we will need to keep the certificate and private key somewhere in safe place.
Also it is not kept by any means automatically, so after restarting the application you see the chooser again.

The easiest thing to implement that would be to allow user to choose the certificate before connecting to home assistant in some place during manual url configuration.

Embedding the certificate in application code works correctly - we need to pass it in 3 places:
1. WebViewClient in WebViewActivity
2. WebViewClient in AuthenticationFragment
3. OkHttpClient in HomeAssistantRetrofit

**Comment by cicavey** [comment]
Any chance of posting a patch? a fork? I'd love to see this

**Comment by maciekczwa** [comment]
I need to clean it a little bit. I will push it to my GitHub probably next
week.

śr., 29 sty 2020, 21:47 użytkownik Christopher Cavey <
notifications@github.com> napisał:

**Comment by m11tch** [comment]
@maciekczwa Any chance you managed to get this to work? :)

**Comment by spali** [comment]
would love to get an example too.
side note: a lot of issues and requests inside these issues for a "niche" feature. 😈

**Comment by evil-dog** [comment]
I would also be interested in a fork that has client cert support.

**Comment by andras-tim** [comment]
I would like this feature, because:

- the VPN drains the phone's battery
- the app's login page / Nabucasa service is not enough secure (for me)

therefore the client cert-based auth is the only solution for me.
(I know, this is quite advanced stuff, but I think, the security-minded guys will love that + the feature is not so big)
