### ISSUE TITLE
Cloud URL is used even if it is disabled

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/home-assistant-android#216]
**Home Assistant Android version:**
1.3.1 (66)
**Android version:**
9
**Phone model:**

**Home Assistant version:**
0.104
**Last working Home Assistant release (if known):**

**Description of problem:**
If I have Remote Control disabled in the Cloud config panel, the app still sends me to the cloud url when onboarding. This obviously results in an error.

I'm then guided to the settings screen where I can change the URL to the one I entered when onboarding.

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by JBassett** [comment]
This might be a defect in Home Assistant, if it is disabled the mobile_app integration should not send it when we register.  @balloob thoughts?

**Comment by balloob** [comment]
Yeah, I agree.

**Comment by balloob** [comment]
PR: https://github.com/home-assistant/home-assistant/pull/30453
