### ISSUE TITLE
Empty screen after entering SSID

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/home-assistant-android#217]
When I enter my WiFi SSID in the settings screen, and press return, I'm faced with an empty screen. After restarting the app it keeps going to onboarding and then I'm faced with an empty screen again.

(I have not entered an internal URL, that might be the problem?)

**Comment by jes1417** [comment]
I cannot even login, I an have with empty screen as soon as I entered login credentials. Closing app or pressing back causes app to search for ha again.
