### ISSUE TITLE
Notify service does not show up in HA

### ISSUE THREAD

**Issue by anybody84** [home-assistant/home-assistant-android#218]
**Home Assistant Android version:** 1.3.1 (57)

**Android version:** 9

**Phone model:** Samsung Galaxy S9 (SM-G960F)

**Home Assistant version:** 0.103.5

**Last working Home Assistant release (if known):** n/a

**Description of problem:** I cannot send notifications to my android app, because the expected notify-service does not show up in HA. In general I'm using default_config in my HA instance, so the mobile_app component should be loaded by default. I gave all the permissions (location) to my application, I was trying to re-login and re-install the application. Still no success. For the remote access I'm using Remote UI and nabu casa subscription. Is there something I'm missing? AFAIK, if the mobile_app component is loaded, it should work out of the box.

**Comment by dshokouhi** [comment]
Did you restart HA after installing the app and logging in?

**Comment by anybody84** [comment]
@dshokouhi, yes, I did. I even tried to add ```mobile_app``` component to my config (even though I already had ```default_config```) and restart HA, but still nothing.

**Comment by dshokouhi** [comment]
Where are you looking for the notify service?  You should only see it as a service call in the services tab, it will not show up as an entity.  You should see it as `notify.mobile_app_*` where * is your device name.

**Comment by anybody84** [comment]
@dshokouhi, yep, that's exactly where I was searching for it.
But, I managed to get it working. I started all over again and it seems that the solution was to remove the web app installed from Google Chrome. I've removed everything HA-related from my phone, then installed the app, restarted HA and the service appeared. The question is - could it be, that there is kinda conflict between Chrome and this app causing the issue?

**Comment by andriej** [comment]
@anybody84 it shouldn't be (or at least it's not for me). I use OxygenOS 10 (Android10) on OnePlus device and still have both: HA app and Webview shortcut.
Both of them works 'together' on same device (as notifications are too).

**Comment by ronsum232** [comment]
Solution is to clear the storage for the app... needs to be done after update to version supporting notifications.

**Comment by seidler2547** [comment]
Had the same problem, confirmed also here: https://community.home-assistant.io/t/mobile-app-doesnt-work-on-android/159392/4

**Comment by JBassett** [comment]
Initial issue has been resolved above
