### ISSUE TITLE
How do we know if we're using internal or external url? Mutliple home networks?

### ISSUE THREAD

**Issue by Knoxie** [home-assistant/home-assistant-android#222]
**Home Assistant Android version:**

**Android version:**

**Phone model:**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**
There's no indication of which URL is being used. Also what if a user has multiple home networks?

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by balloob** [comment]
There is only 1 home network necessary to be configured, as that is the one that allows direct access to Home Assistant. We don't aim on supporting users with more complicated configurations.
