### ISSUE TITLE
Swipe navigation

### ISSUE THREAD

**Issue by nelbs** [home-assistant/home-assistant-android#225]
I like the app very much but i am missing the ability to swipe between views. Are there plans tot add this functionality in the (nearby) future? Or is this to complex to implement?

**Comment by balloob** [comment]
The app shows the Home Assistant frontend so this is out of scope for the Android app.

**Comment by schildgenb** [comment]
For swipe navigation you can try installing the custom card Lovelace Swipe Navigation. That is what I have been using and it works. The link https://github.com/maykar/Lovelace-Swipe-Navigation

**Comment by nelbs** [comment]
Thanks

**Comment by duesseldorferjung** [comment]
As it seems for security reason custom components are not the preferred way of homeassistant anymore, I feel the integration of a swiping function into the Android App itself would make sense.

**Comment by dshokouhi** [comment]
> As it seems for security reason custom components are not the preferred way of homeassistant anymore, I feel the integration of a swiping function into the Android App itself would make sense.

Since it was a custom component it will need to be added elsewhere and not the app. Probably in the frontend.

**Comment by duesseldorferjung** [comment]
Where would be a good place to raise the issue?

**Comment by duesseldorferjung** [comment]
any update?
