### ISSUE TITLE
Send a device_id in registration when HA >= 0.104.0

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#226]
In Home Assistant 0.104 mobile app registration allows passing in a `device_id` to the registration (https://github.com/home-assistant/home-assistant/pull/30457). Together with the `app_id` it will be set as the unique ID for the Android app. This means that Home Assistant will automatically clean up duplicate config entries for the same model.

When we register, we should first hit `/api/discovery_info` to fetch the version of Home Assistant.  Example response:

```json
{
  "base_url": "http://192.168.1.150:8123",
  "location_name": "Home",
  "requires_api_password": true,
  "version": "0.104.0.dev20200103"
}
```

If version is >= 0.104, we can add `device_id`. I've made the mobile app integration future proof to not need version checks for the future when we add new attributes.

**Comment by JBassett** [comment]
So the device id should be unique, but constant, on reinstall per devices?

**Comment by balloob** [comment]
Note: it was `model_id` but I changed it to `device_id` as that is better.

**Comment by scottismyname** [comment]
After factory resets, the device id will change, but this setting should be preserved on uninstalls/reinstalls of the app itself.
