### ISSUE TITLE
Location updates inconsistent

### ISSUE THREAD

**Issue by Knoxie** [home-assistant/home-assistant-android#227]
**Home Assistant Android version:**
1.3.1 (67)
**Android version:**
10
**Phone model:**
Pixel 2
**Home Assistant version:**0.103.5
**Last working Home Assistant release (if known):**

**Description of problem:**
Location doesn't update. Location services still has me at work 25 mi from home. I updated at work, app broke, downgraded,  drove home and updated to current release and no location update. 

**Traceback (if applicable):**

```

```

**Additional information:**
Can we get a force update button. I've been using apps that require gps since getting home so I'm not sure why we're not getting Hass location updates.

**Comment by dshokouhi** [comment]
Yea sometimes the location updates trigger quickly like when leaving a zone and sometimes its just so darn slow.  In all honesty this app hardly uses battery as is, I think more frequent updates are in order.  I dont ever see the app in my batter draining list.

**Comment by nerdfoundrygaming** [comment]
**Home Assistant Android version:** 1.3.1 (57)
**Android version:** 10
**Phone model:** OnePlus 6
**Home Assistant version:** 0.103.5

Upon first installing the app, it was updating frequently, I was getting updates frequently as I walked around the house, and occassionally thinking my location was across the city. 

Then for about a week it completely stopped updating unless I opened the app, and waited about 30-60s. I've driven upwards of 60miles away from my home and when I came home HA never saw I left the home zone (default 100m).

As of the last 24 hours, it's suddenly falsely putting my device about 30 miles away, quite a few times.

I have the battery optimization off, precise location on.

Let us know if there's any further information needed.

**Comment by marchingphoenix** [comment]
Home Assistant Android version: 1.3.1 (57)
Android version: 10 
Security Update: 2019-11-05
Kernel: 4.9.165-g7cce48a52887-ab5897369
Phone model: Pixel 3

Location allowed always. Batt Optimization off.
Position and battery life does not update unless the app is opened or a notification is received.
Home Assistant version: 0.103.5

**Comment by dshokouhi** [comment]
My wifes Pixel 3 XL shows her as home all day and battery is not updating. Meanwhile google maps updating as it should.  Location on, battery optimization off.  My Pixel 4 XL is updating as it should but I have been using the HA app during the day.  My wife hasnt touched the HA app since yesterday.

**Comment by reharmsen** [comment]
I also see issues with my wife's Samsung Galaxy S6.
Infrequent updates, no updates, wrong updates, inaccuracy, etc.

I hope https://github.com/home-assistant/home-assistant-android/commit/ab602bca4f7a4e1ad87684ee2155fbb072bff248 (Set minimum accuracy for location updates.) will also help to at least mitigate inaccuracy issues.
And i hope https://github.com/home-assistant/home-assistant-android/commit/ffdc3c3750d501eb86ad48a4cb28bd67774e2f7a (Home Network Settings) also helps, as this will allow SSID tracking

Any news on when an updated app will be released? 
After that I will try to look into it more closely.

**Comment by codycodes** [comment]
Glad I found this issue. Also having some funkyness around location updates; it seems like there's a delay sometimes and other times it's right behind my partner's iPhone. I can't really use this for presence detection right now so I'm thinking about using webhooks or OwnTracks as I'm sure (like others) that my phone is grabbing its location. I commute with navigation on for about an hour and a half a day and sometimes my location is reported as still being at work hours after I've returned home.

Home Assistant Android version: 1.4.0 (77)
Android version: 10
Security Update: 2020-1-05
Build Number: QQ1A.200105.007
Phone model: Essential PH-1

also happy two months for Home Assistant Companion for Android! Can't believe the app has been developed this far in the past couple of months and can't wait to see where this goes! 🎉

**Comment by Whytey** [comment]
I am seeing similar sporadic updates.  Wife has been out all day but still showing at home.

Managed to call the notify service for her phone with payload of "message: "request_location_update"" on her phone and get an accurate location instantly.

I have two devices connected (both Pixel 4's).  I haven't gotten a good handle on exactly what the behaviour is but I do know it isn't what I was expecting (or even experiencing previously).

**Comment by dpjrodrigues** [comment]
I don't think this is fully fixed. It is much better then before but for time to time the location update freeze and just comeback when app is opened or phone restarted (in this period google location timeline still works ok)
I couldn't find the pattern so not sure how I can help

**Comment by dshokouhi** [comment]
@dpjrodrigues please make sure to check these steps: https://companion.home-assistant.io/docs/troubleshooting/faqs#location-is-not-updating-in-android-app

**Comment by dpjrodrigues** [comment]
> @dpjrodrigues please make sure to check these steps: https://companion.home-assistant.io/docs/troubleshooting/faqs#location-is-not-updating-in-android-app

Thanks. Yes have points 1,2 & 3 covered. Regarding point 4 I have data saver off so it shouldn't apply right?... anyway even with data saver off I've added HA app to unrestricted data to test
