### ISSUE TITLE
Location Device name being reset

### ISSUE THREAD

**Issue by Knoxie** [home-assistant/home-assistant-android#228]
**Home Assistant Android version:**

**Android version:**

**Phone model:**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**
Device name being reset on update. Multiple devices being registered.

![Screenshot_20200104-000125](https://user-images.githubusercontent.com/1057404/71760077-a4490b80-2e85-11ea-8c95-59406a552e18.png)

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by JBassett** [comment]
Steps to reproduce?  Did you wipe the apps data then register again because right now that's expected behavior?

**Comment by Knoxie** [comment]
No, only upgraded through firebase. Didn't touch cache or storage.

Installed build that left screen blank on install. Downgraded, then
upgraded to this version .

**Comment by JBassett** [comment]
If you are still experiencing this please try wiping data on app, delete app integration in HA, reboot HA, then log back in.  If you are still experiencing the issue please reopen.
