### ISSUE TITLE
Ability to export Logs / Debug issues

### ISSUE THREAD

**Issue by schneekluth** [home-assistant/home-assistant-android#229]
**Home Assistant Android version:**
1.3.1 (latest)

**Phone model:**
Oneplus 3 (Android 9) and
Oneplus 7T (Android 10)

**Home Assistant version:**
0.103.5

**Last working Home Assistant release (if known):**
unknown

**Description of problem:**
I have an issue with the app: When I open a specific view the app crashes. All other views work as expected. This happens on two phones and the latest 2 Android versions. I've tried to use logcat to investigate the error but cannot find the reason for the crash.
It would be nice if I could export a crash log directly from the app.

**Comment by balloob** [comment]
First step should be to try to reproduce this on Chrome.

**Comment by schneekluth** [comment]
Issue also appears in latest Chrome for Android (79.0.3945.93).

**Comment by balloob** [comment]
In that case you should report it in the frontend repo. https://github.com/home-assistant/home-assistant-polymer/
