### ISSUE TITLE
Unable to Register Application: Couldn't get FirebaseInstanceId

### ISSUE THREAD

**Issue by grote** [home-assistant/home-assistant-android#231]
**Home Assistant Android version:** 1.3.1 (57)

**Android version:** 10

**Phone model:** Xiaomi Mi A2

**Home Assistant version:** 0.103.5

**Last working Home Assistant release (if known):** none

**Description of problem:** setting up the Android mobile app for the first time, it tells me that the app is "Unable to Register Application".

**Traceback (if applicable):**

```
01-06 15:46:02.938  3487  3487 D GmsGcmRegisterSvc: onBind: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
01-06 15:46:02.969 10688 10688 E IntegrationPresenter: Couldn't get FirebaseInstanceId
01-06 15:46:02.969 10688 10688 E IntegrationPresenter: java.io.IOException: SERVICE_NOT_AVAILABLE
01-06 15:46:02.969 10688 10688 E IntegrationPresenter:  at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.2:71)
01-06 15:46:02.969 10688 10688 E IntegrationPresenter:  at com.google.firebase.iid.zzl.zza(com.google.firebase:firebase-iid@@20.0.2:84)
01-06 15:46:02.969 10688 10688 E IntegrationPresenter:  at com.google.firebase.iid.zzp.then(com.google.firebase:firebase-iid@@20.0.2:4)
01-06 15:46:02.969 10688 10688 E IntegrationPresenter:  at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
01-06 15:46:02.969 10688 10688 E IntegrationPresenter:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-06 15:46:02.969 10688 10688 E IntegrationPresenter:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-06 15:46:02.969 10688 10688 E IntegrationPresenter:  at java.lang.Thread.run(Thread.java:919)
```

**Additional information:** My phone doesn't have any Google software installed which is probably not expected. Why do you need Firebase to register the mobile app anyway?

**Comment by dshokouhi** [comment]
you need google services and firebase for the app to work, its how everything works.

**Comment by grote** [comment]
I would argue that in the tradition of homeassistant, its official app should at least be available in a Free Software (Open Source) version and not rely on non-free software being available on users phones.

**Comment by dshokouhi** [comment]
The app itself offers location tracking, notifications and other upcoming features so in those cases its required regardless if you use those features or not.  If you don't require that then maybe its best for you to just use chrome or a browser.  The developers also use firebase for distribution and other reasons.

**Comment by balloob** [comment]
The official app will rely on Google services to offer the best Android experience.

**Comment by jleeuwes** [comment]
@grote Please note that the app works fine if you kill it at that error screen and start it again, even though registration 'failed'. I run without Google Play Services as well and so far I'm only missing the possibility to send notifications and 'see' the app from inside Home Assistant. Everything else in the app seems to work fine.

@balloob I understand your stance. But I think there is a simple solution for this issue: catching the error and displaying a nicer message that can be closed, so people know what is going on but can continue using the app. Usually apps that use Google Play Services trigger a built-in popup that complains about Google Play Services missing, and Home Assistant for some reason doesn't seem to trigger that popup, so it took me a while before I realized this was the reason I was getting this error and not being able to send notifications.

**Comment by skylarmt** [comment]
> The app itself offers location tracking, notifications and other upcoming features so in those cases its required regardless if you use those features or not.

Except it's not, the developers are refusing to implement self-hosted/open source/libre/etc push notifications for some unknown reason.  For example, Signal runs a background websocket service if Google spyware isn't installed, and Gotify is a cross-platform server and client that does nothing but push notifications.  Gotify's license is actually compatible; the server could be rebranded and bundled with Home Assistant, and the background service code for the Gotify Android app could be copied and included in this project.

There's another even simpler option as well; the Home Assistant app could check for Google, and if not found, use [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager) to ask the OS to "wake up" the app every 15 minutes so it can poll the server for new notifications.

**Comment by larena1** [comment]
> 
> 
> > The app itself offers location tracking, notifications and other upcoming features so in those cases its required regardless if you use those features or not.
> 
> Except it's not, the [developers are refusing to implement](https://github.com/home-assistant/home-assistant-android/issues/42#issuecomment-584372676) self-hosted/open source/libre/etc push notifications for some unknown reason. For example, Signal runs a background websocket service if Google spyware isn't installed, and Gotify is a cross-platform server and client that does nothing but push notifications. Gotify's license is actually compatible; the server could be rebranded and bundled with Home Assistant, and the background service code for the Gotify Android app could be copied and included in this project.
> 
> There's another even simpler option as well; the Home Assistant app could check for Google, and if not found, use [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager) to ask the OS to "wake up" the app every 15 minutes so it can poll the server for new notifications.

Sounds great! When will you start implementing it?
