### ISSUE TITLE
Fallback to remote.nabucasa.com when local connection is not available

### ISSUE THREAD

**Issue by ekt-** [home-assistant/home-assistant-android#237]
If I'm at home, I'd prefer to use the local connection since is faster.
When I'm away, the app should automatically connect via nabucasa

**Comment by allanpersson** [comment]
Duplicate of #30 !? 🙏

**Comment by JBassett** [comment]
Duplicate: #30

**Comment by ekt-** [comment]
#30 didn't came up in my search probably because was already closed. I see it's implemented in #209, which is great. Thanks
