### ISSUE TITLE
Unreachable HA URI causes app to be defunct

### ISSUE THREAD

**Issue by nerdfoundrygaming** [home-assistant/home-assistant-android#238]
**Home Assistant Android version:** 1.3.1
**Android version:** 10
**Phone model:** OnePlus 6
**Home Assistant version:** 0.103.6
**Last working Home Assistant release (if known):** N/A

----

**Description of problem:**

App was previously set up to be accessed via Class-C LAN IP, and upon leaving the network (ie went remote/off-site) the app only attempts to connect to previously functioning URI but fails with an Android WebView error: `Webpage not avilable` `net::ERR_CONNECTION_TIMED_OUT`.

While the error is completely valid, the issue is there's no way to resolve (ie, replace invalid URI with domain/WAN IP) as the app becomes completely defunct.

**Additional information:**

Workaround is to clear data for the app, and reopen. Would prefer some UX around failure to connect, maybe even a few suggestions on what to check for, and informing the user what the attempted URI was.

**Comment by JBassett** [comment]
Can you please give the full app version the number in the (XX) is the most important part

**Comment by nerdfoundrygaming** [comment]
I'm not sure if you read my issue, but no.. I cannot. This is WHY the issue was submitted.
