### ISSUE TITLE
Error when loading screen

### ISSUE THREAD

**Issue by fernandex00** [home-assistant/home-assistant-android#242]
![Screenshot_20200108-204745_Home Assistant](https://user-images.githubusercontent.com/34770145/72028231-23f52280-3258-11ea-9e7c-075921ce22f4.jpg)
Got this when open the app and loading, it won't work with the nabu casa or ip adress

**Comment by allanpersson** [comment]
I have same issue, since v68. 
Samsung galaxy s9+ / Android 10 b5
HA: 0.104.0b0

![20200103_121031](https://user-images.githubusercontent.com/46043392/72051406-846d7980-32c3-11ea-80ed-bbb0f731ed3f.jpg)

**Comment by fernandex00** [comment]
I'm o ha  0.103.6, Galaxy s10+ android 10
