### ISSUE TITLE
Login URL mangled on beta build 

### ISSUE THREAD

**Issue by jonpaterson** [home-assistant/home-assistant-android#243]
**Home Assistant Android version:**
1.3.1(71)
**Android version:**
10
**Phone model:**
Pixel XL4
**Home Assistant version:**
103.5
**Last working Home Assistant release (if known):**

**Description of problem:**
After new install of beta version to support testing, after logging in with OTP error occurs and URL is replaced with garbage.
![Screenshot_20200108-210906](https://user-images.githubusercontent.com/10554323/72035213-d9c27000-325c-11ea-955a-32a3f65e0baa.png)

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by jonpaterson** [comment]
If I should report beta bugs elsewhere pls let me know.

**Comment by JBassett** [comment]
I just validated with the latest, that url is your cloud access url.  This is to be expected if you have a cloud account setup.  If you have the Remote UI disabled, a fix in HA 0.105 (https://github.com/home-assistant/home-assistant/pull/30453) should keep it from being returned.
