### ISSUE TITLE
Feature request: GPS Accuracy limitation

### ISSUE THREAD

**Issue by Nornode** [home-assistant/home-assistant-android#244]
On several other GPS trackers, there are a way to block inaccurate GPS updates.
Please have that implemented here as well, either on HA (configuration.yaml) side or within the preferred way, the app.

Thanks for a great app!

**Comment by JBassett** [comment]
This was fixed via https://github.com/home-assistant/home-assistant-android/pull/181.  Currently we don't want to expose the actual minimum accuracy value in the UI.
