### ISSUE TITLE
iframe panel url link "401: Unauthorized user" error

### ISSUE THREAD

**Issue by jrhbcn** [home-assistant/home-assistant-android#259]
**Home Assistant Android version:**
1.4.0 (77)

**Android version:**
10

**Phone model:**
pixel 3XL

**Home Assistant version:**
0.103.6

**Last working Home Assistant release (if known):**
none

**Description of problem:**
I have setup a iframe panel url link to an internal https link (a transmission server running in a local computer). However, i get "401: Unauthorized user" error. I was expecting to get the web login interface of the transmission server. The same thing works perfectly if accessing home assistant from a browser (from desktop or phone). It only happens when accessing the iframe link through the android app.

**Comment by balloob** [comment]
If you're opening Home Assistant from an `https` url you cannot open websites using `http`. This might be related ?

**Comment by jrhbcn** [comment]
The link is actually a https (a redirection using nginx). 

> If you're opening Home Assistant from an `https` url you cannot open websites using `http`. This might be related ?

Yes. The link is actually an https (a redirection using a nginx server). Something like: https://xxxx.duckdns.org:8080

The link works perfectly accessing home assistant using the browser (using same phone) but not the app. Maybe the re-direction is somehow confusing the Android app?

**Comment by rsfurlan90** [comment]
@jrhbcn it would be a great enhancement if the web view embedded on the Android app was able to ask for credentials whenever required. Chances are that you have already logged in the page you are trying to open from Home Assistant via browser, as subsequent requests will be authenticated through the Authorization header.

I have been looking for a workaround the past days as well. If you open Home Assistant using Incognito Mode (private browsing) it will prompt for username and password again. However, it won't behave the same when you play with Home Assistant using the Android app, so there is no way to somehow authenticate into the service. In my example, I refeer to Configurator, but it would be very useful for any other 3rd party application we may want to embbed into HA.

Thank you for driving this.

**Comment by jrhbcn** [comment]
Just to give a little bit more information to the issue. My ipanel configuration is:
```
  info:
    title: 'Info'
    url: 'https://xxxx.duckdns.org:8080'
```

Then at machine xxxx.duckdns.org I have a nginx proxy pass site enabled with this config:
```
server {
  listen 8080 ssl;
  server_name xxxx.duckdns.org;
  ssl on;
  ssl_certificate /etc/nginx/certs/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/privkey.pem;
  ssl_trusted_certificate /etc/nginx/certs/chain.pem;
  ssl_prefer_server_ciphers on;

  location / {
    proxy_hide_header   Referer;
    proxy_hide_header   Origin;
    proxy_set_header    Referer                 ";
    proxy_set_header    Origin                  ";

    proxy_set_header        X-Forwarded-Host $host:$server_port;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;

    proxy_pass         http://localhost:8081;
  }
}
```

And finally the transmission server is running on port 8081 in the local machine. 

As I said, this config works well when accessing home assistant from the direct https link, however, it fails to authenticate when accessing from the android app. 

Hope this extra info helps to solve the issue...
