### ISSUE TITLE
App starts fresh everytime it is lauched from the home screen

### ISSUE THREAD

**Issue by m2hofi94** [home-assistant/home-assistant-android#260]
**Home Assistant Android version:**  1.4.0

**Android version:** 10

**Phone model:** Pixel 3

**Home Assistant version:**  0.103.6

**Last working Home Assistant release (if known):** n/a

**Description of problem:**

When I launch the App from the Homescreen it always starts fresh. Even if I just opened it, press the home button, and tap the App Icon again it refreshes completely (Splash Screen and all). If I use the app switcher, no refresh occurs.

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by balloob** [comment]
Unable to reproduce this on a Pixel 3 XL.

**Comment by m2hofi94** [comment]
super weird, I just installed a Screen Recorder to get "evidence" but now it doesnt happen anymore. It occured consistently earlier :man_shrugging: 

I guess there was something else going on, so I'm closing this...

Sorry for the annoyance :see_no_evil:
