### ISSUE TITLE
Support PiP when viewing a stream enabled camera

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-android#267]
**Home Assistant Android version:**
1.3.1 (77)
**Android version:**
10
**Phone model:**
Pixel 4 XL
**Home Assistant version:**
0.103.3
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
We should support PiP when a camera is opened and the video stream starts.  

It also looks like the full screen icon is disabled, that may be the reason why PiP is not working?

![image](https://user-images.githubusercontent.com/1634145/72574132-da6e8e00-387c-11ea-9ce0-1517965b37af.png)

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by dshokouhi** [comment]
important to note that this works as expected in chrome so maybe missing permissions or something?

![image](https://user-images.githubusercontent.com/1634145/72575487-74d0d080-3881-11ea-8218-18ab2626db1a.png)

![image](https://user-images.githubusercontent.com/1634145/72575498-7d290b80-3881-11ea-8b0f-b6edb97d4cad.png)

**Comment by Pe-MaKer** [comment]
Same here.
Please take care that camera streaming on the app works the same as it does on chrome. Without scrolling the video due to the useless camera name banner and ideally with pip support.

**Comment by Zamunda4Eva** [comment]
Yes, please add this feature.

**Comment by a-jackson** [comment]
I'm getting the same problem as this as well. Also when turning the phone landscape the header banner with the camera name is pushing down the video chopping off the bottom

**Comment by dshokouhi** [comment]
@a-jackson that sounds like a separate issue. If you experience that issue in Chrome on Android then please open a bug on the front end repo.  If it only exists on the android app then please open a new issue here for it.

**Comment by dshokouhi** [comment]
Closed in #471
