### ISSUE TITLE
CI is broken for `master`

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#279]
Current master HEAD 195bc96  is broken. It broke when we merged #271 / cc241e1 .

See https://travis-ci.com/home-assistant/home-assistant-android/builds/145139085#L1039-L1040

```
> Task :app:processDebugGoogleServices FAILED

Parsing json file: /home/travis/build/home-assistant/home-assistant-android/app/google-services.json
```

**Comment by JBassett** [comment]
Someone with the encryption key for the `secrets.tar.enc` needs to modify the google-services.json inside to also include a client for `io.homeassistant.companion.android.debug` like `mock-google-services.json`
