### ISSUE TITLE
Rotating the device will reload the interface

### ISSUE THREAD

**Issue by Skeletorjus** [home-assistant/home-assistant-android#28]
When rotating the device, Home Assistant for Android will reload the whole interface and return to the home view.
Expected behavior is to rotate the page to landscape mode.
It would also be natural to show cameras in full screen if the UI is currently displaying a more info dialog for one.

**Comment by CedrickFlocon** [comment]
WIP : https://github.com/home-assistant/home-assistant-android/pull/20

**Comment by Skeletorjus** [comment]
> WIP : #20

Thanks! For some silly reason I didn't think of checking the pull requests... :)
