### ISSUE TITLE
Internal home url not working and notifications no longer work

### ISSUE THREAD

**Issue by raresserban** [home-assistant/home-assistant-android#281]
**Home Assistant Android version:** 1.4.0

**Android version:** 9

**Phone model:** LG G6

**Home Assistant version:** 1.4.2

**Last working Home Assistant release (if known):**

**Description of problem:**
I have set up external access and added it into the HA Android app. First, it didn't work at all and just redirected me to the browser and then I deleted all the app data, then it started working. I have setup the correct ssid name and internal url but it never uses that, only if I put the internal url in the primary url box, which obviously won't give me remote access.

Secondly, now my android phone can no longer receive notifications, even after HA restart. The service is still there, but on call it says that the entity id is not found.

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by xaviml** [comment]
Did you give the permission for location to the app? The app needs to get the current SSID of your network and in order to do that Android requires the app to have the Location permition enabled. I don't know if this is your case, but this happened to me.

**Comment by JBassett** [comment]
You shouldn't need to grant location permissions if you just want to have the local/remote urls to work.

**Comment by quthla** [comment]
Retrieving wifi ssid requires location permission

**Comment by xaviml** [comment]
I can confirm what @quthla just said, which is what I was referring to. This is part of Android permission management, you need the same permission as the one to scan the network.

**Comment by JBassett** [comment]
After rereading the documentation starting in 8.0 you are correct.  Guess we need to request that permission when they go to enable the internal url.

**Comment by dshokouhi** [comment]
Don't we already prompt the user to accept location permissions the moment they login?  Maybe we should do the following:

1. Before permission prompt when logging in notify user they will get the prompt and what features get enabled if permission is granted.  On this screen you can even have a button that says "Enable Location Permission" so the prompt can show after they read the reasoning.
2. If permission was granted enable device tracker and additional settings.
3. If permission was denied disable device tracker and additional settings.  Add the reasoning for internal URL and SSID disabled with a link/button to enable location permissions.

**Comment by raresserban** [comment]
Indeed, I did not give Location permissions cause I don't want the app to constantly pool for location and eat battery life, but I guess I can give the permission and not enable that functionality.

Regarding the second issue with the notifications, if I access the HA locally and then restart, in theory the notifications should work again right?

**Comment by raresserban** [comment]
So I see that I have my phone two times as an entity with the same exact name in HA...Is there any way to delete them so the entity is generated again?

**Comment by dshokouhi** [comment]
you can delete the integration, clear data in the app, restart HA and then log back in with the app to recreate the integration.....then once logged in restart HA again and notifications should be working

**Comment by raresserban** [comment]
I changed the name of my phone and got a new notify service. The old service is still there but doesn't bother me. I didn't want to delete the integration since I already had 2 phones with notifications that worked fine, only mine didn't.
