### ISSUE TITLE
No validation for widgets

### ISSUE THREAD

**Issue by cogneato** [home-assistant/home-assistant-android#292]
**Home Assistant Android version:**
1.4.0 (88)
**Android version:**
10
**Phone model:**
Pixel 3
**Home Assistant version:**
104.3
**Last working Home Assistant release (if known):**
n/a
**Description of problem:**
Widgets can be created without entering any data or combinations of missing data
**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by balloob** [comment]
This has been resolved with the new widget UI.
