### ISSUE TITLE
Widget icons and labels out of line and labels cut off

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/home-assistant-android#299]
**Home Assistant Android version:**
1.4.0 (92)

**Android version:**
10

**Phone model:**
Huawei Mate 20 Pro

**Home Assistant version:**
0.104.3

**Last working Home Assistant release (if known):**

**Description of problem:**
Widget icons appear out of line with other icons on the home screen and the labels are cut off after very few characters (the second widget in the screenshot below should say "Computer Room").
![Screenshot_20200123_165600_com teslacoilsw launcher_2](https://user-images.githubusercontent.com/2099542/73013256-deb42180-3e0f-11ea-9fa8-df18eb513718.jpg)

Ideally the icon should be slightly higher up and the label should wrap over at least two lines

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by andriej** [comment]
Same here (Android 10 / OnePlus 6)

**Comment by balloob** [comment]
A widget is not an icon, so it is not meant to align with the launcher. There are also too many launchers out there, and we would have to support all of them. 

I do agree that we should explore if we can expand the space for the name.

**Comment by JBassett** [comment]
Fixed in https://github.com/home-assistant/home-assistant-android/pull/401
