### ISSUE TITLE
Automatic Switch Between Local/Internet server

### ISSUE THREAD

**Issue by mccoy88f** [home-assistant/home-assistant-android#30]
Thanks for this great job.
One of the important request Is:
Switching from local address when over home wifi
And on internet access when outsider home.
I Hope soon ☺️ thanks

**Comment by andriej** [comment]
Set your remote address with DNS on local router with local IP and it will work with same settings everywhere.

**Comment by timmo001** [comment]
I do like this as an idea for the future. Perhaps do a mdns discovery scan on startup to see if the same server is on the current network when connected to wifi and swap over to the local address. Might cause issues with

**Comment by Knoxie** [comment]
@andriej That only works for someone running their own DNS server. Not all users will have that setup.

**Comment by balloob** [comment]
Some routers don't support accessing a remote url that points to an internal IP. It's a limitation of the users router. So yes, we should collect two urls, one for local and one for outside your home. More info in the dev docs: https://developers.home-assistant.io/docs/en/app_integration_sending_data.html#short-note-on-instance-urls

**Comment by quthla** [comment]
The app should also subscribe to [WIFI_STATE_CHANGED_ACTION](https://developer.android.com/reference/android/net/wifi/WifiManager.html#WIFI_STATE_CHANGED_ACTION) broadcasts then and reload the webview with the appropriate url

**Comment by Arkadije** [comment]
What if you access your HA instance locally when you are at home, but access it through Nabucasa when you are away. The ap should be able to switch between those tow URLs. 
Especially if you have automation turned on that if you are home no remote access is available and if you are not at home remote access is available. 
Support of two URLs should be a welcomed addition.

**Comment by allanpersson** [comment]
![20200103_121031](https://user-images.githubusercontent.com/46043392/71720532-5a7b0980-2e22-11ea-986a-3c105bd67861.jpg)
![Screenshot_20200103-121002_Home Assistant](https://user-images.githubusercontent.com/46043392/71720540-6070ea80-2e22-11ea-9f83-8efd2c6798cb.jpg)

With v66 let me know if you want me to open a new issue 🙏
