### ISSUE TITLE
Companion won't accept my internal IP when provided with my WiFi SSID

### ISSUE THREAD

**Issue by gsotiriou** [home-assistant/home-assistant-android#300]
**Home Assistant Android version:** 1.4.0 (77)

**Android version:** Android 9

**Phone model:** Xiaomi Mi6 

**Home Assistant version:** 0.103.6

**Last working Home Assistant release (if known):** New feature as far as I'm aware

**Description of problem:** I have my HA exposed via DuckDNS and I've been long using the external (https://) link with the companion. I decided to use the new feature and provide my SSID along with my internal address (https://ip:port) to have internet-independent connectivity to my server when I'm home. It won't accept it and prompts me with a popup to re-check my settings. 

**Traceback (if applicable):** N/A

**Additional information:** The only thing I can think of is that I am connected to a single WiFi SSID which is 2.4 GHz and 5 GHz at the same time (not separate networks) and also my WiFi gear is mesh-like which in turn means that I may be connected to any node at any point in time.

**Comment by JBassett** [comment]
If you open the internal address with chrome does it require that you bypass a SSL error?  It sounds like the SSL certificate you are using isn't valid for you internal ip address, which is normal. Normally you would use a http://ip:port address internally.

**Comment by gsotiriou** [comment]
Trying with http instead of https in the internal IP made no difference. 
![IMG_20200124_192557](https://user-images.githubusercontent.com/34280016/73089728-851b2800-3edf-11ea-889b-54727b8451a0.jpg)
![IMG_20200124_192633](https://user-images.githubusercontent.com/34280016/73089729-851b2800-3edf-11ea-9cec-fb7994ad1f9d.jpg)

**Comment by dshokouhi** [comment]
Does that internal URL load in chrome on the same device?

**Comment by Albertowue** [comment]
Same scenario and same result for me

**Comment by gsotiriou** [comment]
> Does that internal URL load in chrome on the same device?

Yes it does! 
![Screenshot_2020-01-25-11-07-56-817_com android chrome](https://user-images.githubusercontent.com/34280016/73118896-154e8100-3f63-11ea-8be0-b1932caad3df.jpg)

**Comment by JBassett** [comment]
You are correct it loads in the browser but that '!' in the URL bar means you accepted a bad certificate.  The reason the app doesn't work is because the URL doesn't match what the certificate says is valid .

**Comment by gsotiriou** [comment]
> You are correct it loads in the browser but that '!' in the URL bar means you accepted a bad certificate. The reason the app doesn't work is because the URL doesn't match what the certificate says is valid .

Indeed the certificate is invalid for this URL as it has been issued by Let's Encrypt for my domain name "example.duckdns.org". However once you've set up HA with external access (and a valid certificate for that external access hostname) the internal address starts replying only to https and ditches the http that HA first uses when it's being set up for the first time.

So to take one thing at a time:
1) Using the internal IP:PORT address with http is not possible. Not in browser and by extension not in the app as well.
2) Using the internal IP:PORT address with https is not acceptable by the app as it seems (hence my reason for opening this issue).
2a) Issuing a valid certificate for internal IP address is not allowed by how internet works.
3) I hope this feature is not mutually exclusive - meaning , that when you use the external address you can no longer use the internal.

**Comment by JBassett** [comment]
I think ideally we would allow HA its self to be hosted on 2 ports, one with SSL one without.  However if @balloob doesn't think HA should do that, perhaps we can allow an exception to the SSL error `ERR_CERT_AUTHORITY_INVALID`.  When we see that on an internal address and the certificate Common Name matches the URL we have stored in the external url setting we allow it?

**Comment by balloob** [comment]
We shouldn't go there. There are nginx proxies one can install to wrap Home Assistant in TLS, so you have two ports.

If your router supports it, just connect to the https duckdns domain, data still won't leave your network and it's encrypted. Accepting non certified certificates is a direction we should avoid.

**Comment by balloob** [comment]
We should close this issue. Initially opened because of specifying wrong port, and https doesn't work with IP addresses.
