### ISSUE TITLE
Allow service data for widget

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-android#303]
**Home Assistant Android version:**
1.4.0 (94)
**Android version:**
10
**Phone model:**
pixel 4 xl
**Home Assistant version:**
0.104.3
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
Now that we are pulling in all services we should allow the user to enter JSON/YAML for the service data.  Not every service call needs a entity ID but does require additional data such as `frontend.set_theme`
**Traceback (if applicable):**

```

```

**Additional information:**

![image](https://user-images.githubusercontent.com/1634145/73110950-2d6bc500-3ebd-11ea-8e5d-e7897865b2bf.png)

**Comment by KBerstene** [comment]
@JBassett I'm working on this specific case
