### ISSUE TITLE
Question - How to setup widgets

### ISSUE THREAD

**Issue by scottismyname** [home-assistant/home-assistant-android#305]
I'm unsure how to setup widgets. What do I need to be inputting for the different fields?

**Comment by dshokouhi** [comment]
@scottismyname make sure you are using the latest firebase build, you should see drop downs for the service and entity ID to select from.

**Comment by scottismyname** [comment]
So weird.... I had the latest version but there was no drop downs... I reinstalled and everything works perfectly!

Will we eventually be able to see the current state of devices with widgets?

**Comment by dshokouhi** [comment]
Eventually, I imagine so but for the first release its purely to call some services. 

 If everything is working can you please close this bug :)
