### ISSUE TITLE
No longer available for Chrome OS

### ISSUE THREAD

**Issue by lonebaggie** [home-assistant/home-assistant-android#306]
Unable to update on my Acer Chromebook R13 from app store

Your device is not compatible with this version

**Comment by dshokouhi** [comment]
Please do not delete the issue template all the information is important, what android version did you have installed previously?

**Comment by lonebaggie** [comment]
Sorry. Just to confirm Home Assistant Companion for Android 1.5.0  the play store allows me to download and install. so fixed thank you
