### ISSUE TITLE
Zones on the map are moving strange while zooming

### ISSUE THREAD

**Issue by zhulik** [home-assistant/home-assistant-android#310]
**Home Assistant Android version:**
10.4.0 (96)

**Android version:**
9 (MIUI 11)

**Phone model:**
Xiami Mi MIX 3

**Home Assistant version:**
0.104.3
**Last working Home Assistant release (if known):**

**Description of problem:**
As shown in the attached video, when you zoom the map, zones on are moving pretty strange. 
**Traceback (if applicable):**

```

```

**Additional information:**
[Video](https://drive.google.com/file/d/1SVu4RP4rgmF8VhbnxArJswS7tpieU-iD/view?usp=drivesdk)

**Comment by SeanPM5** [comment]
Pretty sure this is a general frontend issue, it happens on iOS devices as well. Bug was reported here last year: https://github.com/home-assistant/home-assistant-polymer/issues/2853
