### ISSUE TITLE
Notification don't work with local build (Android Studio)

### ISSUE THREAD

**Issue by neopilou** [home-assistant/home-assistant-android#311]
**Home Assistant Android version:**
1.4.0 (local build)

**Android version:**
9

**Phone model:**
Galaxy S5e
Galaxy S9+

**Home Assistant version:**
0.104.3

**Description of problem:**
"notify.mobile_app" don't work with local build (Android Studio) of home assistant companion. Notifications sent from home assistant are not received on the device. In the HA log just "SenderId Mismatch", nothing else, no traceback : 

2020-01-24 17:45:00 ERROR (MainThread) [homeassistant.components.mobile_app.notify] SenderId mismatch

**Comment by JBassett** [comment]
Unfortunately the key that is embedded in the app for notifications when released needs to stay a secret.  Because of this when you build locally you will be unable to use notifications.
