### ISSUE TITLE
internal IP not working

### ISSUE THREAD

**Issue by dedepene** [home-assistant/home-assistant-android#314]
**Home Assistant Android version:**
1.5.0 (96)
**Android version:**

**Phone model:**
samsung galaxy s8
**Home Assistant version:**

**Last working Home Assistant release (if known):**
latest
**Description of problem:**
as soon as i configure SSID and internal url (https://192.168.1.195:8123)  I start getting errors - "Unable to connect to HA. review connection settings and try again." The very same url works just fine on my LAN from within a browser - mobile or PC. Whys is the app struggling with the inetranl address?
**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by neopilou** [comment]
@dedepene Local IP with https usually causes an SSL certificate error.  This stops the navigation.  For security reasons, the app does not suggest that you override this error as some browsers may do ... You have to use a local ip with http : "http://192.168.1.195:8123". If you have SSL certificate with domain name configured in HA, you can use Nginx reverse proxy (for example) to obtain an address in https with SSL and DNS, and a internal URL in http without SSL.

**Comment by dedepene** [comment]
> @dedepene Local IP with https usually causes an SSL certificate error. This stops the navigation. For security reasons, the app does not suggest that you override this error as some browsers may do ... You have to use a local ip with http : "http://192.168.1.195:8123". If you have SSL certificate with domain name configured in HA, you can use Nginx reverse proxy (for example) to obtain an address in https with SSL and DNS, and a internal URL in http without SSL.

Thanks for the explanation, it makes sense. However, I'm not able to find anything on this specific scenario. I can find http to https via nginx but not the opposite use case. - https://www.home-assistant.io/docs/ecosystem/nginx_subdomain/

Would you know of a good source to read up on this please?

**Comment by neopilou** [comment]
Do you have HA or HA.io?
Is your SSL certificate configured in HA (do you have the fullchain.pem and privkey.pem files in the HA "config/ssl" folder) ?

**Comment by dedepene** [comment]
> Do you have HA or HA.io?
> Is your SSL certificate configured in HA (do you have the fullchain.pem and privkey.pem files in the HA "config/ssl" folder) ?

I have hassio running on a bare-metal AMD64, and yes - I have it configured for SSL. As a result I can reach the instance at https:// but I also need to reach it internally when there's no interent connection. 

Thanks for your help!

**Comment by neopilou** [comment]
So you just have to delete or comment the lines :
    ssl_certificate
    ssl_key
    server_port
in "http:" section in your configuration.xaml.

Restart HA and connect with the URL "http: //192.168.1.195: 8123"

Then install the addon "NGINX Home Assistant SSL proxy". 

By default the HTTPS port is 443, but you can change it in the addon options (do not forget to modify it if necessary in the port forwarding settings from your router). 

Add your domain name in the addon options. 

Start addon, 

Your internal URL will remain "http://192.168.1.195:8123" and from the outside it will be your domain name + ": port" (if different from 443)

**Comment by dedepene** [comment]
@neopilou , you're the man! :)

This worked like a charm and you saved me countless hours of trial and error. Thank you!

**Comment by dedepene** [comment]
@neopilou ,

I'm running into an issue with the ESPHome addon, and probably others too. What happens is that the addon loads its webui fine, but all subsequent requests are denied (i.e. "show logs", "validate" etc.). A lot of entries like this in the esphome addon log:

```
WARNING 403 GET /ace (0.0.0.0) 1.93ms
WARNING 403 GET /logs (0.0.0.0) 1.90ms
WARNING 403 GET /ace (0.0.0.0) 1.61ms
WARNING 403 GET /ace (0.0.0.0) 1.80ms
WARNING 403 GET /ace (0.0.0.0) 1.94ms
```
In the meantime, if I load the local instance (http://192...) - it works fine. So I googled a bit and it seems to be a websocket forwarding issue, but I'm lost on this one. Any idea how to configure nginx to do this please?

Thanks!

**Comment by balloob** [comment]
This issue has been resolved. It's not a place for further discussions. Use forum or chat.
