### ISSUE TITLE
interface enhancement: swipe between view

### ISSUE THREAD

**Issue by froggy974** [home-assistant/home-assistant-android#315]
Hi,
Just a small interface enhancement proposal : 
It could be nice to be able to use left/right swipe to change between view tabs

**Comment by neopilou** [comment]
This cannot be integrated into the application, but you can use one of these custom cards for HA:
[https://github.com/maykar/Lovelace-Swipe-Navigation](https://github.com/maykar/Lovelace-Swipe-Navigation)
[https://maykar.github.io/custom-header/](https://maykar.github.io/custom-header/#intro/intro)

**Comment by balloob** [comment]
Yep, swiping is a frontend issue.

**Comment by froggy974** [comment]
it's not possible to do something like that in the app ?
it would be a great ergnonomy enhancement 
![ha app slide](https://user-images.githubusercontent.com/17068466/82542350-2181ce00-9b52-11ea-8383-6e2725aa39f4.gif)
