### ISSUE TITLE
When APK on Google Play?

### ISSUE THREAD

**Issue by angeltonio** [home-assistant/home-assistant-android#319]
the version on Google Play is 4.3, when we have the last version on google play??

**Comment by angeltonio** [comment]
Or maybe a link to take the apk compile..???

**Comment by balloob** [comment]
1.5 is the latest version and it's on Google Play: https://play.google.com/store/apps/details?id=io.homeassistant.companion.android&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1
