### ISSUE TITLE
Dim screen when not using it like fully kiosk browser

### ISSUE THREAD

**Issue by sverleysen** [home-assistant/home-assistant-android#325]
It would be nice if you could use the Androids device sensors (or camera) to dim the screen when you aren't using the screen, or no motion is detected on the camera.
That is currently the only reason for me not to use the app on my wall mounted tablet.

**Comment by balloob** [comment]
It's not the focus of our app to add a ton of features for tablet use. Our focus is to be used on phones, not as an always on solution. We shouldn't add this.

**Comment by ngdio** [comment]
Would it hurt to have kiosk features though? I also want to use Home Assistant on my tablet and would like features like this one. Or is it too difficult finding someone to develop/maintain such features?

**Comment by balloob** [comment]
Every feature needs to be maintained forever. It needs to be included in every update forever. It needs to be translated. And it can make adding other features more complicated, as all features need to be considered with every other feature toggled on/off. 

And so we need to set a goal for what we want to achieve and focus on that. Other apps can focus on providing a great kiosk experience.
