### ISSUE TITLE
Navigation using remote control doesn't work on the login screen (AndroidTV)

### ISSUE THREAD

**Issue by bieniu** [home-assistant/home-assistant-android#327]
**Home Assistant Android version:** 1.5.1 (from Google Play)

**Android version:** 9.0 (AndroidTV)

**Phone model:** Xiaomi Mi Box 3

**Home Assistant version:** 0.104.3

**Last working Home Assistant release (if known):** None

**Description of problem:**
Navigation using remote control doesn't work on the login screen. I'm not able to change focus to username/password inputs.

**Comment by Gronsak** [comment]
Can confirm this for Nvidia Shield TV (2017) running Android 9.0 as well.

**Comment by neopilou** [comment]
I assume it's a HA frontend issue because navigation inside a webview cannot be managed in the app.

**Comment by dshokouhi** [comment]
Hmm I guess I didnt notice this because I used my harmony keyboard.  After logging in I did notice that I was unable to navigate HA with the remote so it must be all related.   They may need to apply this to the entire front end but not sure.  Good catch!

**Comment by dshokouhi** [comment]
@bieniu and @Gronsak does the android tv remote app or shield tv remote app work?

**Comment by bieniu** [comment]
@dshokouhi Android TV Remote App also doesn't work.

**Comment by dshokouhi** [comment]
Yea directional pad inside a virtual device isn't working either.  It does work on the app scan and URL entry screens so it does appear to be a front end issue.

**Comment by Gronsak** [comment]
No d-pad option works but I got signed in by using the Nvidia Shied TV apps trackpad since it gives you a mouse cursor. though in app navigation is a bit sparse using a dpad, I either get locked into the leftside menu selection or can only scroll the home screen (can only interact with the lovelace elements using the cursor)

From what I can see this is probably something that has to be fixed on the home assistant frontend

**Comment by balloob** [comment]
I suggest we remove the Android TV badge.

**Comment by Brausmith** [comment]
I too am having issues at the login screen on a 2018 Sony Bravia and a Vodafone TV box.

**Comment by foxy82** [comment]
> I suggest we remove the Android TV badge.

Is there no way to fix forward? It would be amazing to have this app on the TV as it allows me to switch the matrix in my loft without using my phone. Just removing TV support would be sad.

**Comment by balloob** [comment]
The way forward would be for someone to step up and fix it. You can't just allow installation on a TV and then just expect bug reports will trigger volunteers to step up and add support for this 🤷‍♂.

**Comment by foxy82** [comment]
I meant is there no technical way forward. If we think it is fixable with time/expertise that is great.

Looking at the code it looks like it is using WebKit and there are a few articles on the web on getting the remote to work this seems to be the best one: 
https://stackoverflow.com/questions/19716840/handle-arrow-keys-from-d-pad-on-webview-google-tv-app

It mentions adding KeyPress code to the js in the website. Does that fit in with the accessibility push mentioned in the latest release?

I'm not an app or JavaScript developer so could be way off base with my research.

**Comment by balloob** [comment]
No, that does not go with the accessibility push. Our accessibility push is for people with disabilities. Not people with Android TVs. 

Look, we shouldn't have added the Android TV badge, the UI doesn't work in it. It should not have been added.

**Comment by robbiet480** [comment]
I gotta agree here. I haven't even tested it yet but all i've heard is complaints. I don't see how a web UI will ever work well on a ten foot display. The only thing i'd entertain on Android TV in the absence of a working frontend is a notification only app that replaces [Notifications for Android TV](https://www.home-assistant.io/integrations/nfandroidtv/).

**Comment by robbiet480** [comment]
I've disabled Android TV on the Play Store, at least for now.
