### ISSUE TITLE
[Suggestion] Allow swiping left and right in UI to switch "tabs"

### ISSUE THREAD

**Issue by scottismyname** [home-assistant/home-assistant-android#328]
Sorry, not sure if "tabs" are the right word but I'm sure you know what I mean.

Right now if you have more than one tab in the lovelace UI, you need to click the corresponding tab at the top.  It would be nice if you could swipe left and right to change tabs.

**Comment by balloob** [comment]
https://github.com/home-assistant/home-assistant-android/issues?q=is%3Aissue+swipe+is%3Aclosed

**Comment by JBassett** [comment]
Beat me to it:
duplicates: https://github.com/home-assistant/home-assistant-android/issues/202, https://github.com/home-assistant/home-assistant-android/issues/225. and https://github.com/home-assistant/home-assistant-android/issues/315
