### ISSUE TITLE
[Question] Can you use home WiFi to set "home" status?

### ISSUE THREAD

**Issue by scottismyname** [home-assistant/home-assistant-android#334]
Now that we have our local WiFI SSID, is it possible to make it so that while we're connected to this, that HA knows we're home?

I just upgraded my router from an Asus AC68 to an Asus AC88 and all of a sudden my nmap device tracking is really inconsistent.  My AC68 was rock solid.  Using the same settings on the new router and my devices are shifting me from home to away while I'm always home.

**Comment by balloob** [comment]
This is a good idea. Could work if we could monitor if we're switching WiFi networks.

**Comment by JBassett** [comment]
Would we want to set the device tracker entity to home/away or just expose the connected WiFi status and connection info as an entity and let the user decide how to handle that?

**Comment by balloob** [comment]
Maybe just trigger a location broadcast whenever we change wifi?

**Comment by scottismyname** [comment]
Oh I like that idea....if we detect we're on our home wifi, trigger a location broadcast.  This seems to be the problem for detecting that we're home.

**Comment by JBassett** [comment]
https://developer.android.com/topic/performance/background-optimization
We can try and build a [job](https://developer.android.com/topic/performance/background-optimization#sched-jobs]) to get around it but it's not going to be a simple task due to changes in later versions of android unfortunately.

**Comment by balloob** [comment]
Ah too bad !

**Comment by balloob** [comment]
So I guess the answer to this question is "no". 

Note that we still query the zones, which includes the home zone, and have those zones registered to trigger updates.
