### ISSUE TITLE
Feature request: add URL option for push notification

### ISSUE THREAD

**Issue by funkbuddha** [home-assistant/home-assistant-android#335]
I need to send a URL from my NVR to my phone via a push notification so that when I tap the notification, it takes me to the NVR’s recording that generated the alert. 

Something like this

message: 'test message'
data:
  android:
    notification:
      url: https://www.google.com
      

Thanks!

**Comment by allanpersson** [comment]
Duplicate of https://github.com/home-assistant/home-assistant-android/issues/162 🙏
