### ISSUE TITLE
Pressing back should not go to previous view (tab)

### ISSUE THREAD

**Issue by tadly** [home-assistant/home-assistant-android#338]
**Home Assistant Android version:** 1.5.1
**Android version:** 10
**Phone model:** Pixel 3
**Home Assistant version:** 0.104.3
**Last working Home Assistant release (if known):** ---

**Description of problem:**
Changing views (tabs) and then pressing back goes to the previous view.
This is not how things usually work on android and feels rather confusing.

**Comment by balloob** [comment]
This is a frontend issue.
