### ISSUE TITLE
(Not important!) Update Google Play description 

### ISSUE THREAD

**Issue by allanpersson** [home-assistant/home-assistant-android#34]
There is alot of Android apps using home assistant in "name" and "company". The play store description should mention this is the official one 🙏

![Screenshot_20191119-202905_Google Play Store](https://user-images.githubusercontent.com/46043392/69179199-6f6a3a80-0b0b-11ea-8a14-9822bcf88705.jpg)

**Comment by balloob** [comment]
I disagree. We will be nr1 pretty soon when you search for Home Assistant. We use the official logo and will be the first in results.

**Comment by allanpersson** [comment]
@balloob sorry if I was unclear. I agree the app soon will be in top, the problem is not the "name" or "company" it self. But the fact that the only thing saying its the official app is the logo and the email address.

In the "description" of the app when you click it the description should tell about the app and that it's the official one. Honestly I would have thought the one from home assistant team was the official one if I didn't knew and was active on github and community forum, which most users won't be. So for them and for avoiding threads seeking help for wrong apps the description inside the app should be more clear and stating its the official one in my opinion 🙏

**Comment by allanpersson** [comment]
![20191120_064736](https://user-images.githubusercontent.com/46043392/69212486-c1d64600-0b61-11ea-89a8-a79f8e4bfa97.jpg)

**Comment by balloob** [comment]
Good point in putting it in the description. I have updated the short description to 

> The official app for Home Assistant. Control your home anywhere in the world.

(it's limited to 80 chars)

What do you think ?

**Comment by allanpersson** [comment]
I think it sounds very good 👍
