### ISSUE TITLE
Add Lovelace UI administrative rights

### ISSUE THREAD

**Issue by Joebuckeye123** [home-assistant/home-assistant-android#340]
Excellent work with Home Assistant companion.  I plan to make Home Assistant Companion (Android app) the front-end of a tablet that will be used by family members to navigate Lovelace UI.  Have one concern: The only person that should have access to the Home Assistant back-end is the Administrator.  
Can a login/logoff be added to the Lovelace UI (Upper right-side) toolbar?  Here's my suggestion:

- If you are not the Admin the Home Assistant (left-side) toolbar will not be available. The end user only has access to the Lovelace UI tabs.

- If you log in as Admin the toolbar will remain available until you log out.  This should only apply to the Home Assistant Companion device that will be used by family members. 

This action will prevent someone that is not the Admin from making changes to the Home Assistance instance.

I would take care of this myself.  Don’t have the technical skill set yet to make this happen.  It’s a long road.  Working my way there.

**Comment by allanpersson** [comment]
Take a look at https://github.com/maykar/custom-header it does what you need 🙏

**Comment by Joebuckeye123** [comment]
Thank you!  I will look into this custom-header option.

**Comment by JBassett** [comment]
We just display the Home Assistant Front-End.  If you think that should be a part of the actual UI you should add the defect here:  https://github.com/home-assistant/home-assistant-polymer
