### ISSUE TITLE
Device Tracking - "Last Seen" Property

### ISSUE THREAD

**Issue by blawford** [home-assistant/home-assistant-android#344]
Is it possible to add a property to the device tracker to show when the location was last updated? Otherwise it is hard to see whether the location is currently accurate or not.

**Comment by balloob** [comment]
This should be fixed in the backend.

**Comment by blawford** [comment]
Sorry, can you elaborate? Something I can so?

**Comment by JBassett** [comment]
Or you can use a template to get it: `{{states.device_tracker.device_name.last_updated}}`

**Comment by balloob** [comment]
This fixes it. https://github.com/home-assistant/home-assistant/pull/31551

**Comment by blawford** [comment]
Thanks both.
