### ISSUE TITLE
Feature request: tracker only client

### ISSUE THREAD

**Issue by andriej** [home-assistant/home-assistant-android#345]
**Home Assistant Android version:** n/a
**Android version:** n/a
**Phone model:** n/a
**Home Assistant version:** n/a
**Last working Home Assistant release (if known):** n/a
**Description of problem:** n/a
**Traceback (if applicable):** 
```
n/a
```

I'd like to recommend (but I'm also not sure if it's more backend or app-like feature): it would be nice to be able to login on some device just as a tracker, so without all the access to HA panel. Maybe it would need some backend support on user (so another permission level: admin/user/viewer/tracker?)

It would be especially helpful to login on devices on which we don't want to give full access to HA on, but we would like to track them.

**Additional information:**

**Comment by balloob** [comment]
Home Assistant has a limited user system. You are either an admin or a user. In your case, make the users "user" level and just don't open the app?

**Comment by andriej** [comment]
Yeah, but opening the app on device i.e. mounted in car would lead to access to all switches and cards, while it could only show none of that info at all.
It's not urgent but maybe worth considering in HA's user system on timeline?

**Comment by balloob** [comment]
This is not a feature that we currently want to consider.
