### ISSUE TITLE
Call service for all entities

### ISSUE THREAD

**Issue by Anonym-tsk** [home-assistant/home-assistant-android#347]
Please add `all` as entity_id to widget configuration.

**Home Assistant Android version:**
Latest

**Android version:**
10

**Phone model:**
OnePlus 6T

**Home Assistant version:**
Latest

**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by gadgetchnnel** [comment]
It seems that, even though "all" doesn't show as an option, if you just type it into field it actually works.

I was able to use this to make a widget that turns off all lights by having "light.turn_on" as the service and "all" as the entity id.

**Comment by KBerstene** [comment]
@JBassett I don't know if you want to leave this as something to be able to just be typed in or if you want to add it as an option to every `entity_id` field.  I don't know if there are other keywords that HA has that might want to get added into the list as custom values as well.  Thoughts?

**Comment by balloob** [comment]
Just `all`.
