### ISSUE TITLE
Feature request: update & remove notifications

### ISSUE THREAD

**Issue by CodeFinder2** [home-assistant/home-assistant-android#353]
As already mentioned in #215, I would like to  ask for the ability to update and remove existing notifications. This is especially useful in a smart home context because we may want to inform the user about certain required actions (e.g., you forgot to close the back door) and once this is done (door closed), the reminder (= notification) should disappear which also serves as a nice feedback. This way, the notifications can somehow serve as a "TODO list". (It's similar, if not equivalent, to `persistent_notification.dismiss`).

Thanks for considering!

**Comment by andriej** [comment]
Somehow 'tag's were helpful since today, right now there's discussion about closing the backend on unsupported features.
It wasn't pure dismiss, but you could overwrite previous message with current status like ("Door were closed').

**Comment by CodeFinder2** [comment]
Yes, but if I got you right, isn't 'overwriting' and updating the same? 🙈

What do you mean by "right now there's discussion about closing the backend on unsupported features."? 🤔

**Comment by andriej** [comment]
This issue https://github.com/home-assistant/home-assistant-android/issues/349

**Comment by CodeFinder2** [comment]
Great thanks!
