### ISSUE TITLE
Add localizations

### ISSUE THREAD

**Issue by Misiu** [home-assistant/home-assistant-android#37]
App already looks great 🎉
but it needs to support multiple languages.
Other projects already use lokalise.com, so I think the next step is to create a community-driven project that will allow us to help with translation.

**Comment by TheZoker** [comment]
Home Assistant already uses lokalise for the front-, backend and iOS app:
https://lokalise.com/project/3420425759f6d6d241f598.13594006/
https://lokalise.com/project/130246255a974bd3b5e8a1.51616605/
https://lokalise.com/project/834452985a05254348aee2.46389241/

So I guess there will soon be a project for the Android app

**Comment by balloob** [comment]
I've created a new project on Lokalise and found @TheZoker, so he is a member now too.

If a dev is working on this to automate uploading/downloading, let me know and I can add you to the Lokalise group. Example translation download/upload scripts can be found here https://github.com/home-assistant/home-assistant/tree/dev/script - although it is kinda different in Android world probably.

**Comment by CedrickFlocon** [comment]
fixed https://github.com/home-assistant/home-assistant-android/pull/72
