### ISSUE TITLE
Long notification messages are truncated -- cannot expand

### ISSUE THREAD

**Issue by shbatm** [home-assistant/home-assistant-android#372]
**Home Assistant Android version:**
App 1.6.0 (105)

**Android version:**
10

**Phone model:**
Samsung Galaxy S9+

**Home Assistant version:**
Home Assistant 0.105.2

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
Notification messages with text longer than 1 line are cut-off and cannot be expanded to show the rest of the text.

**Traceback (if applicable):**

```
N/A
```

**Additional information:**
Looks like (to my non-Android developer ignorant eye) notifications need a BigTextStyle added.
https://developer.android.com/training/notify-user/expanded#large-style

**Comment by dshokouhi** [comment]
Just tested this myself with the following service data and I see the same issue.  Cannot pull down notification to read the rest.

```yaml
message: "This is a very long message text that will push down the notification by one line"
```

![image](https://user-images.githubusercontent.com/1634145/74215100-c4be6f80-4c54-11ea-9cdc-be7eb3410d8f.png)

**Comment by shbatm** [comment]
(disclosure: untrained eye, just trying to help)

Looks like you may be able to add something like:
```java
        .setStyle(new NotificationCompat.BigTextStyle()
                .bigText(data[MESSAGE]))
```

At [this line](https://github.com/home-assistant/home-assistant-android/blob/aacb4ea605c8fd3c59d3b0550c128a47eafdc365/app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt#L181) to fix the issue.

**Comment by CodeFinder2** [comment]
I've realized this issue as well.

**Comment by shbatm** [comment]
Tagging @JBassett since you've been doing a lot of great work on the notifications.

**Comment by robbiet480** [comment]
@shbatm Mind submitting a PR so you get credit for the fix? Thanks!
