### ISSUE TITLE
Feature Request: Report charging/not charging battery status

### ISSUE THREAD

**Issue by myakove** [home-assistant/home-assistant-android#373]
Report charging/not charging battery status to hass.

**Comment by Kisty** [comment]
It's coming. See #374

**Comment by dshokouhi** [comment]
This is in the current firebase build 111

**Comment by dshokouhi** [comment]
Closing issue as its already merged.

![image](https://user-images.githubusercontent.com/1634145/74252536-b0a15f00-4ca2-11ea-8c63-4cdade7582c8.png)
