### ISSUE TITLE
home state is "Home" not "home"

### ISSUE THREAD

**Issue by mcfrojd** [home-assistant/home-assistant-android#374]
**Home Assistant Android version:**
1.6.0 (105)
**Android version:**
10
**Phone model:**
OnePlus 6T
**Home Assistant version:**
0.105.2
**Last working Home Assistant release (if known):**

**Description of problem:**
The app reports home state as "Home" and not "home".
So if you like me use a group of 3 device_trackers the group state wount get set to "home" when the app reports "Home"
**Traceback (if applicable):**
Should be an easy fix to replace the capital "H" with an "h"
```

```

**Additional information:**

**Comment by dshokouhi** [comment]
This is odd I just checked all my devices and they all show the state as `home`.  Make sure to check the states tab for what is actually shown.

![image](https://user-images.githubusercontent.com/1634145/74249675-6322f300-4c9e-11ea-8f6e-feefcb060d45.png)

**Comment by mcfrojd** [comment]
This is what i get.
I think this might be new since 1.6.0
(you might need to "login fresh")
![Screenshot (2)](https://user-images.githubusercontent.com/7395495/74251664-c3d91c80-4cec-11ea-9d06-5fcc6b8c4621.jpg)

**Comment by dshokouhi** [comment]
I am on the latest firebase build 111

**Comment by mcfrojd** [comment]
Im on the latest in Google Play Store 1.6.0 (105) i guess the (105) is the firebase build on that one

**Comment by dshokouhi** [comment]
Yea that number represents the firebase build.  My wifes phone is on the official release as well.  Lets see if others have the same issue too.

**Comment by balloob** [comment]
@mcfrojd do you have a zone called Home?

**Comment by mcfrojd** [comment]
@balloob Omg.. well i seem to have forgot that i was fiddeling with zones when the new zone editor was released.
So yes this was totally my own fault.
