### ISSUE TITLE
Shopping List doesn't refresh its contents after adding an item

### ISSUE THREAD

**Issue by valantur** [home-assistant/home-assistant-android#379]
Adding an item to the shopping list clears the item box, but the item doesn't show up on the list until I click some other tab and then click back. This happens on both the shopping list sidebar and the shopping list lovelace card.

Thanks for looking into this!

**Comment by dshokouhi** [comment]
Please make sure to fill out the issue template so we know what versions you are on.  Can you test this behavior in the browser to see if its consistent?

**Comment by valantur** [comment]
Here's the info from the template I forgot to include:

Home Assistant Android version: 1.6.0 (105)
Android version: 10
Phone model: Samsung Galaxy S10e
Home Assistant version: 0.105.2
Last working Home Assistant release (if known): 0.105.2

This happens to me on the Android app, Firefox and Chrome, but only in my mobile phone, not on the computer.

**Comment by valantur** [comment]
I just found that it's a known issue with the frontend for non-admin users:
https://github.com/home-assistant/home-assistant/issues/28346
I'll close the issue now, thanks and sorry for the false alarm :)

**Comment by obaldius** [comment]
when adding/removing elements with a service call the list won't update in lovelace, not even with admin permissions.

**Comment by jpoeppelman1** [comment]
I have the same issue.

**Comment by dshokouhi** [comment]
Please dont comment on old and closed bugs, in this case this issue has nothing to do with the android app as the issue is in HA core. Check open issues in HA core and create a new issue there if it doesn't exist.
