### ISSUE TITLE
No way to change Home Assistant server address

### ISSUE THREAD

**Issue by bdr99** [home-assistant/home-assistant-android#38]
Currently the only way to change the configured address of the Home Assistant server is to clear the app data or uninstall and reinstall the app. The app should provide a UI for changing the server address.

**Comment by dshokouhi** [comment]
Yea edit the URL and maybe also add separate instances would be nice to have too.

**Comment by balloob** [comment]
The logout button on the profile page of the app should (is?) linked to the logout function in the app. 

https://developers.home-assistant.io/docs/en/frontend_external_auth.html#revoke-token

**Comment by CedrickFlocon** [comment]
WIP : https://github.com/home-assistant/home-assistant-android/pull/49

**Comment by CedrickFlocon** [comment]
ready to be review

**Comment by balloob** [comment]
Fixed in #49
