### ISSUE TITLE
Battery and wifi sensors have generic names

### ISSUE THREAD

**Issue by klejejs** [home-assistant/home-assistant-android#381]
**Home Assistant Android version:**
1.7.0 (116)
**Android version:**
9.0
**Phone model:**
Sony XZ1 Compact
**Home Assistant version:**
0.105
**Last working Home Assistant release (if known):**

**Description of problem:**
It would be nice if all the device sensor names and id's were created based on chosen device name, not simply generic one so that all the devices have almost the same name.
**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by hmmbob** [comment]
Agree - though this is not only applicable to the Android app but also to the iOS app, if I read [the docs](https://companion.home-assistant.io/docs/core/sensors) right.

**Comment by hhromic** [comment]
I faced the same issue and I agree sensor names should be tied to device name.

For example, I have a Neato vacuum named `alfie`, and its entiites are `vacuum.alfie`, `sensor.alfie_battery_level`, `camera.alfie_cleaning_map` and `switch.alfie_schedule`. As you can see this scheme is very clean, organised and easy to manage.

The mobile application integration already creates `device_tracker.NAME`, I think it should follow the same scheme as the Neato integratoin and create `sensor.NAME_battery_level` and `sensor.NAME_wifi_connection`. Consistency is important in my humble opinion.

This will also make having multiple mobile applications way easier to organise and interface from within Home Assistant. At the moment they show-up as `sensor.battery_level`, `sensor.battery_level_2`, etc.

**Comment by dshokouhi** [comment]
So I am not sure if this is an android issue as the iOS app has the same issue.  I think we need to get this fixed in HA core: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/mobile_app/entity.py#L61

**Comment by TazUk** [comment]
> At the moment they show-up as sensor.battery_level, sensor.battery_level_2, etc.

In our case only the first of two previously registered and uniquely named devices had the battery and WiFi sensors created.

The second set of entities were logged as not created due to duplicate names.

**Comment by dshokouhi** [comment]
@TazUk was that an HA error? can you share it here?  Just want to make sure my PR will take care of it :) all I am doing is adding the device name.

**Comment by TazUk** [comment]
@dshokouhi 
Yes - showed up in the logs however I was in the process of getting my system up and running again after a host OS failure this morning at 6am GMT right before I left for work.
Unfortunately I just whizzed past it, and having checked logs via the HA front end and in the home-assistant.log file can see no trace now. 

If there's somewhere else I can pull it from please let me know.

It was something to effect of "duplicate entity refused" against sensor.battery_level.

I've renamed the sensors which were linked to my phone, however there is no sign of additional wifi_connection / battery_level sensors for my wife's phone.
I'm guessing they'll show up again at some point?

**Comment by dshokouhi** [comment]
@TazUk try to force stop the app and re-open it...if that doesnt work then try to clear data and start over on that device...if that fails then please open a new issue with the error you experienced.

**Comment by TazUk** [comment]
> @TazUk try to force stop the app and re-open it...if that doesnt work then try to clear data and start over on that device
@dshokouhi  that's going to go over like a lead balloon with my wife right now so I may need to leave resolving it for another day.

> .if that fails then please open a new issue with the error you experienced.
If I get something in the logs I will, but without that I suspect this may just be an edge case that shouldn't happen in normal day to day behaviour.

**Comment by TazUk** [comment]
@dshokouhi for what it's worth I was able to do a quick force stop and launch of the app on the offending phone. No new sensors have appeared - I'd try restarting HA but I've had my fill of computers today. I've made a not to look into it at the weekend.
