### ISSUE TITLE
Notification clickAction to open specific HA navigation path

### ISSUE THREAD

**Issue by shbatm** [home-assistant/home-assistant-android#382]
I noticed that #356 now allows you to set a `clickAction` on a notification to open a url. Would it be possible to use this to jump to a specific Lovelace url/navigation path inside the app?

For example if I have a low battery alert, go to my Battery view in the app when opening, or if I have a camera alert, jump to the camera view?

**EDIT:** A more advanced request would be to open a more-info dialog for a specific entity with the clickAction. Using the same examples above, could provide an `entity=sensor.battery` as the click action to open the battery sensor   more-info dialog inside the app. Same thing for a camera stream. 

@JBassett (tagging you since you've been doing a lot of great work on the notifications)

**Comment by ronsum232** [comment]
I have tried using browser_mod as a workaround until an internal method is developed.

- Trigger event: mobile_app_notification_action - filter by event action's name.
- Wait for: sensor._mobile_app_entity_.attributes.visibility = visible
- browser_mod.navigate || browser_mod.popup || browser_mod.more_info

Two issues with this approach are:
- unable to identify which device called the action (to map to browser_mod's deviceID)
- app doesn't open when firing an action - additional click of the main notification needed.

I've Thumbed up in the meanwhile.
