### ISSUE TITLE
Full screen mode stopped working

### ISSUE THREAD

**Issue by dgtal1** [home-assistant/home-assistant-android#386]
**Home Assistant Android version:**
1.7.0 (116)
**Android version:**
10
**Phone model:**
Huawei P30
**Home Assistant version:**
0.104.3
**Last working Home Assistant release (if known):**
0.104.3
**Description of problem:**
Since a couple of days I can't get the app to show in full screen mode. Not sure of when exactly it started. I'm sure it worked with app version 1.5, but I've got auto app updates enabled when charging my phone, so this could brake in 1.6. Today I saw an update available to 1.7.0 and it was already broken. Updating to 1.7.0 didn't fix it.
Closing the app in android task manager and starting it over doesn't solve it.

Here's how it looks like:
![Screenshot_20200212_133617_io homeassistant companion android](https://user-images.githubusercontent.com/27864579/74336385-71583880-4d9e-11ea-9ce7-35ef6f477ac8.jpg)

Setting enabled:
![Screenshot_20200212_133657_io homeassistant companion android](https://user-images.githubusercontent.com/27864579/74336394-77e6b000-4d9e-11ea-994b-5a6345f32eb8.jpg)

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by neopilou** [comment]
It's not bug, see [#342](https://github.com/home-assistant/home-assistant-android/issues/342)

**Comment by dgtal1** [comment]
I don't understand. It used to work just fine. The status bar at the top of the screen was hidden and there was more space for the app. Now the option doesn't do anything. Not effective.
Why was it changed? It used to work just fine.... :( I do have a drop-shaped notch, but I liked the full screen mode. 

And what do you mean by this: "but just hide the navigation bar."?? It doesn't hide anything now.

**Comment by dshokouhi** [comment]
@dgtal1 this is the new behavior for devices with any type of notch in order to prevent the UI from loading incorrectly.  As the notch is in the status bar only the navigation bar gets hidden.  In some devices there is not much of a navigation bar but this is the expected behavior.
