### ISSUE TITLE
App should open all URLs matching "base_url"

### ISSUE THREAD

**Issue by bieniu** [home-assistant/home-assistant-android#387]
**Home Assistant Android version:** 1.7
**Android version:** 10
**Phone model:** OnePlus 6
**Home Assistant version:** 0.105.3
**Last working Home Assistant release (if known):** None

**Description of problem:**
App should open all URLs matching `base_url` from Home Assistant configuration. For example with:  `base_url: https://hass.example.com/` all URLs with hass.example.com should be associated to HA Companion app.
I think this is the documentation of this feature: https://developer.android.com/studio/write/app-link-indexing#associatesite

This feature would also fix: #382

**Comment by barrymossel** [comment]
Agreed! Now, when I use my base_url in an actionable notification Android asks to open Chrome or the Chrome instance of Home Assistant. Rather would have it to open the Companion app...

**Comment by balloob** [comment]
We should not match base url. Instead we should support users specifying relative urls, which we then open appropriately (local/remote url based on wifi etc)

**Comment by barrymossel** [comment]
> We should not match base url. Instead we should support users specifying relative urls, which we then open appropriately (local/remote url based on wifi etc)

Do you mean relative urls will be opened in the companion app? Would work for me!

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/home-assistant-android/pull/461
