### ISSUE TITLE
Direction of travel sensor

### ISSUE THREAD

**Issue by FuzzyMistborn** [home-assistant/home-assistant-android#388]
This is something gpslogger does that I use to control my garage door. I have to loop around the block when I come from one direction so I don't need the garage door to open as early as when I come the other way.

**Comment by Twanislas** [comment]
Hi !

Isn't that already supported in HA by using the [proximity](https://www.home-assistant.io/integrations/proximity/) integration ?

**Comment by FuzzyMistborn** [comment]
It does whether you're heading towards or away from home which isn't accurate enough for my use case.  I'm asking for the compass direction.  See part circled in blue:
![image](https://user-images.githubusercontent.com/16689090/74368987-a070a900-4da2-11ea-8d58-56acaea2c247.png)

**Comment by DaftHonk** [comment]
My device_tracker provides *course* vice *speed*:

````
source_type: gps
battery_level: 82
latitude: XX.XXXXXXX
longitude: -XX.XXXXXXX
gps_accuracy: 15
altitude: -10
course: 0
speed: 0
vertical_accuracy: 4
friendly_name: XXXXXXXXX
````

**Comment by FuzzyMistborn** [comment]
Yep, looks like course is what I'm after.  Closing.
