### ISSUE TITLE
Sent battery status update is sent whenever the charging state changes.

### ISSUE THREAD

**Issue by Gluwc** [home-assistant/home-assistant-android#391]
It would be great if a battery status update is sent whenever the charging state changes. Currently it only appears to sends updates to the battery status whenever a GPS update gets triggered.

This will be awesome for some automations like going to bed. Things like plugging in your phone will send an actional notification to ask if you want to enable sleep mode.

Another consideration could be to update all battery status in real-time whenever the phone is charging since it is charging anyway, but less important in my opinion.

Thanks in advance, hugs and kisses, yours sincerely,

Lucas

**Comment by Twanislas** [comment]
Big +1

To me, battery status should be pushed to HA on every state change (charging / not charging) by default.

Actually I would love for that to be a toggle (on/off) setting in the app, along with :
- Update battery in realtime when charging
- Update location in realtime when charging
- Update <whatever sensor> in realtime when charging

We'd need to factor in the data usage as well. I don't care a thousand updates every 30 sec when I'm on wifi but maybe I don't want that on carrier data...

"realtime" being something along 1m or 30s of course.

This would allow (for example) realtime location tracking when driving (and plugged to a power source in the car) and thus fast reaction when coming home (open the garage door, TTS notifications announcing I'm nearing home on all the Google Mini's and such)

**Comment by balloob** [comment]
@Twanislas please don't add feature requests in existing issues but open a new issue.

**Comment by Twanislas** [comment]
@balloob very good point. I was just trying to give ideas.
Still, very good point :D. I'll go ahead and open FRs.
Thanks !

**Comment by tdejneka** [comment]
I can confirm that the reported battery level can lag the battery's true state.

I've been using a Macrodroid macro to report the phone's battery state (every time it changes by 1%) and it's reported as a sensor entity. I noticed this entity indicated 64 whereas the Companion's battery sensor reported 55. 

The phone was plugged in, charging, and connected to WiFi. Location Services are _off_.

A few minutes later the Companion's battery sensor reported 64 but the macro-based sensor had already moved on to report 65.

I don't know what mechanism it uses to report battery level. If it's time-based then it allows for (on my phone) a ~10% discrepancy between reported and actual battery level. I would prefer to see it report by fixed increments of 5% (5, 10, 15, 20, 25, etc).

**Comment by dshokouhi** [comment]
This is now implemented in #525 battery status updates when the phone is goes on/off the charger.
