### ISSUE TITLE
Make Sensor tracking toggleable in settings. 

### ISSUE THREAD

**Issue by tbrasser** [home-assistant/home-assistant-android#392]
It seems that by default all the sensors get published to home assistant without a way to configure which sensor you want enabled or not. Can these be made configurable just like the full screen and location settings? 

**Home Assistant Android version:**
1.7
**Android version:**
10
**Phone model:**
Mi 9T
**Home Assistant version:**
105.3
**Last working Home Assistant release (if known):**

**Description of problem:**

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by balloob** [comment]
You can disable the entities in Home Assistant.

**Comment by tbrasser** [comment]
I get that, but not everyone using the app also knows exactly how home-assistant core works / is configured. Having these settings configurable would result in the users of the app being in control (of their phones functioning) instead of the person that manages the home assistant installation.

**Comment by balloob** [comment]
We've talked about this and do not want to implement this currently.
