### ISSUE TITLE
Unable to get past initialization screen after entering URL

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-android#395]
**Home Assistant Android version:**
1.7.0 (play store)
**Android version:**
5.1.1
**Phone model:**
Fire HD7 running custom rom
**Home Assistant version:**
0.106dev
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**

After entering my instance URL the page gets stuck on the initialization screen and I am unable to login.  I am however able to use a browser on the same device and login.  One thing I did notice was that the Initialization screen reloaded once as if it tried to load something then failed.

**Traceback (if applicable):**

```
N/A
```

**Additional information:**
![image](https://user-images.githubusercontent.com/1634145/74372812-22a3a200-4d90-11ea-87fd-6ec3c6c0c9fd.png)

**Comment by dshokouhi** [comment]
Not sure if this qualifies as `authentication` or `onboarding` for the label :)

**Comment by balloob** [comment]
It's onboarding. Authentication is once we have gotten the auth tokens from onboarding.

**Comment by neopilou** [comment]
I encountered the same problem because my version of webview was not up to date.

**Comment by dshokouhi** [comment]
I did make sure to install Android webview and clearing data but got the same results

**Comment by neopilou** [comment]
Have you tested with Fully Kiosk? If it works, it comes from the app, otherwise from Android webview

**Comment by dshokouhi** [comment]
I don't use fully kiosk. All I did was install Android webview from the play store. Whatever version that is it should be supported on Android 5.1 as that's the OS I'm using. Unless there is some other dependency?

**Comment by neopilou** [comment]
The installation of android webview from the play store does not work even if it is possible to install it because Android webview is a system app. It is present in the playstore for updates. If you are using a custom rom, you can use Xposed framework to force the use of Android Webview and get its updates.

**Comment by dshokouhi** [comment]
Thank you @neopilou  that was 100% it :)

I first had to install: https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US

Then in xposed I installed: https://repo.xposed.info/module/net.typeblog.webview

After a restart I am able to login and use HA!

![image](https://user-images.githubusercontent.com/1634145/74452798-68b34100-4e36-11ea-802c-bccdc9549f26.png)

**Comment by marronedamian** [comment]
Hello! I have my tablet with android 4.2 and it had the error due to the webview. Install chrome and it didn't fix it, I managed to fix it by installing Opera browser.

**Comment by dshokouhi** [comment]
@marronedamian android 4.2 is not supported ;) only android 5 and up.

**Comment by marronedamian** [comment]
Hi dshokouhi !, but installing opera works, I just tried it :D
![WhatsApp Image 2022-04-23 at 2 13 38 PM](https://user-images.githubusercontent.com/17587930/164916577-00d746d7-fab0-4174-bee3-fc3d40c7a179.jpeg)
![WhatsApp Image 2022-04-23 at 2 13 36 PM](https://user-images.githubusercontent.com/17587930/164916578-1d472bbf-79cd-493a-9a6a-5c91bec9fb43.jpeg)
![WhatsApp Image 2022-04-23 at 2 13 38 PM (1)](https://user-images.githubusercontent.com/17587930/164916580-239b4c3e-2c84-40ca-803d-05e41c90d320.jpeg)

**Comment by dshokouhi** [comment]
@marronedamian all you are doing is using the HA frontend in a browser, you are not actually using the HA android app ;)

**Comment by marronedamian** [comment]
@dshokouhi Yes, of course, but since I can't install the app, at least I use the browser. With Chrome I had the same problem that was initializing but with Opera I was able to solve it. Sorry if I explained badly.
