### ISSUE TITLE
Image URLs passed in notifications should be authenticated with access token if base URL is known

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/home-assistant-android#397]
On the iOS side you can pass a image URL in a notification like `https://mydomain.org/local/photos/picture.png` without a token/secret and the app automatically authenticates the URLs because it knows `https://mydomain.org` is safe to provide tokens to. We should do the same so users don't have to append tokens to the URL. Also helps down the road when authenticating to camera streams which have short lifespan tokens.

**Comment by balloob** [comment]
FYI, Home Assistant does not support appending tokens to the URL.

**Comment by robbiet480** [comment]
You're right, I misremembered what iOS did. It sets the proper `Authorization` headers on the request if the base URL matches what we have stored.

**Comment by JBassett** [comment]
I feel like we should only apply tokens if they supply a path only and determine the host when we go to fetch the image as we do for loading the front end.
`/local/photos/picture.png` will choose correct domain based on wifi status.

**Comment by robbiet480** [comment]
Ugh. Misremembered again. That's also how iOS works right now. We only attempt to auth if one of two things are true of the image URL:

1. URL is something like `/local/photos/picture.png`
2. URL is empty because user is trying to show a camera snapshot.
