### ISSUE TITLE
Use kotlin-android-extensions and avoid "findViewByID"

### ISSUE THREAD

**Issue by marciogranzotto** [home-assistant/home-assistant-android#40]
[kotlin-android-extensions](https://kotlinlang.org/docs/tutorials/android-plugin.html) has a lot of helper methods that improve the readability of the project.

For instance, it can import views directly from the layout just using the ID, avoiding the whole `findViewByID` thing.

**Comment by CedrickFlocon** [comment]
https://github.com/home-assistant/home-assistant-android/pull/4#issuecomment-549031814
