### ISSUE TITLE
Does the app work with no internet?

### ISSUE THREAD

**Issue by SittingDuc** [home-assistant/home-assistant-android#410]
**Home Assistant Android version:** 1.7.0 (play store)

**Android version:** CyanogenMod 12.1-20160529

**Phone model:** Samsung SM-T800 / chagallwifi / Galaxy Tab S 10.5

**Home Assistant version:** 1.105.2

**Last working Home Assistant release (if known):**

**Description of problem:**

Hello. I want a tablet to control my home assistant. My IoT is firewalled off the internet because _"the S in IOT is for Security"_. I have installed the app on the tablet I have lying around, on a network with no internet access. The firewall on the tablet notes the app attempts a TCP connection to ```88.198.17.141:443```, which seems to be near to https://lokalise.co/. That domain appears several times in the github sources, but I don't read kotlin well enough to understand the context.

Does this app work without internet access?

After entering the LAN address of my server: ```https://192.168.x.y:8123/```, I am rewarded with a completely blank (white) screen. I figure this is one of: 
 * the app not working without internet access
 * or an issue with Cyanogenmod 12.1 being ancient ;) 
 * or an issue with the site being signed with an offline CA that is not (yet) trusted by that android install. I will fix that and try again.

So, I am back to, on a tablet which has no internet access, on the same subnet as my home assistant instance (i.e. using Firefox Android, the site ```https://192.168.x.y:8123/``` loads and works fine), is it expected that this app will work?
If this app should work, then how do I debug the next step? I will double check the CA is 'trusted' with Firefox and/or Chrome; but after that, do I need logcat to see where the app is going south?

Cheers!

**Comment by JBassett** [comment]
The certificate that is being hosted is most likely not valid for an IP only.
Duplicate: https://github.com/home-assistant/home-assistant-android/issues/314
