### ISSUE TITLE
Unable to Register Application

### ISSUE THREAD

**Issue by goliath888** [home-assistant/home-assistant-android#417]
**Home Assistant Android version:**  
1.7.0

**Android version:** 
Android 9.0 Oxygen 9.0.6

**Phone model:** 
OnePlus 3T. 

**Home Assistant version:** 
Home Assistant Core 0.105.2 
 
**Last working Home Assistant release (if known):** 
Android app 1.6 maybe? with the 1.5 sure

**Description of problem:**

I am unable to access Home Assistant, it gets stuck in the screen with the "Unable to Register Application" message.

Things I have try:
- Restarting HA. 
- Reinstalling the app
- Grant all permissions to the app
- Disable battery optimization for the app.
- Enable GPS

**Additional information:**
I have the stock OxygenOS version with Google Services installed. In other tablet it works great with the 1.7, so it seems to be devices related and not server related. In HA logs I do not see anything. 
Can I see any logs in the phone? 
I connect in my local network with the url like http://serverip:8123 (in my other device this works)

**Comment by dshokouhi** [comment]
This sounds slightly different than #132 because in this instance it was working previously and after the latest update it is not?

**Comment by dshokouhi** [comment]
So where exactly do you get stuck? Is it after logging in or before?  Are there any HA error messages?

**Comment by mecko** [comment]
> 
> 
> So where exactly do you get stuck? Is it after logging in or before? Are there any HA error messages?

I have the same issue. It happens after entering the username and password.

It started with 1.7.0 (it worked fine before updating the app).

For what it's worth, I run Android 10 (not 9 like OP), using LineageOS 17.1 (not OOS like OP) and using microG (not Google Services like OP).

**Comment by dshokouhi** [comment]
@mecko can you check the HA logs to see if you get any errors?

**Comment by goliath888** [comment]
> So where exactly do you get stuck? Is it after logging in or before? Are there any HA error messages?

The same as @mecko 

Steps: 
- I go to the app (reinstalled and clean everthing several times), 
- Enter the url like http://miserverip:8123. I also try with https:homeassistant.mydomain.com (I only access in my local network, but I have nginx to access like this with a SSL certificate) 
- Enter user and password.
Then get the error.

Nothing in HA logs.

I also read the issue that has microG services, but I have Google Services installed. Not rooted phone, everything is stock.

Tell me if you need anything else I can try or check.

**Comment by dshokouhi** [comment]
Can you share a screenshot of the error please?

**Comment by goliath888** [comment]
The same as the issue #190 (without the skip button:

![image](https://user-images.githubusercontent.com/61027944/74562441-1f184280-4f6b-11ea-95dc-b1c6a1bc6f43.png)

**Comment by balloob** [comment]
105.4 fixes issues with mobile app registration.

**Comment by goliath888** [comment]
> 105.4 fixes issues with mobile app registration.

Just update...everything the same.

Home Assistant 0.105.4
App: 1.7.2-128

Clean storage &cache in the app. No logs in HA.

Still "Unable to register application"

**Comment by mecko** [comment]
> 
> 
> 105.4 fixes issues with mobile app registration.

It didn't fix _this_ issue.

**Comment by dynobo** [comment]
Having the same issue. Happy to help with additional testing.

HassOS: 3.10
HomeAssistant: 0.105.4
Companion App: 1.7.2-128
Android: Lineage 16.0, MicroG (no gApps). Installed through Aurora Store.
I'm using the App only in local WLAN (no remote access). `mobile_app:` is present in `configuration.yaml`, rebooted.

- When I'm opening the App for the first time (or after deleting App data), I enter as url `http://192.168.0.111:8123` (no ssl enabled).
- The App seems to connect, as I am being asked for username and password. 
- After entering both, I get the same error screen as posted above ("registration error").
- Same screen appears directly on the next App opening.
- Companion App was working fine for quite some weeks, until I updated App + HA (so I'm not sure what broke it)
- I see no errors in HA-Logs

**Comment by balloob** [comment]
We only support Google Play Services. We have never published our app to the Aurora store and do not suppport it.

If people still experience this issue and use Google Play Services, please open a new issue. Make sure to have the mobile app integration loaded and after a failed registration check the logs of Home Assistant and report any errors logged.

**Comment by goliath888** [comment]
> We only support Google Play Services. We have never published our app to the Aurora store and do not suppport it.
> 
> If people still experience this issue and use Google Play Services, please open a new issue. Make sure to have the mobile app integration loaded and after a failed registration check the logs of Home Assistant and report any errors logged.

I have Google Play Services installed, should I a open a new issue? Happy to help with logs or whatever, just tell me what do you need.

**Comment by balloob** [comment]
Are you on Discord? Can you pop into #devs_apps ? Yeah, and let's create a new issue. This one got too off-topic

**Comment by dynobo** [comment]
Just to clarify: Aurora is just another frontend to Google Play Store. The apks are the same. The difference is, that no Google Play Services are required on the phone. (I will stop using the Companion App as soon as it requires Google Play Services, and I'm probably not the only one.)

Thanks for the App and I think this problem will be handled in another issue, so everything is fine. :-)
