### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by sgttrs** [home-assistant/home-assistant-android#425]
Home Assistant already supports Russian at Lokalize.com. Is it possible to add Russian language support for a companion application?

**Comment by robbiet480** [comment]
I've gone ahead and enabled Russian as a translatable language. [Sign up here](https://lokalise.com/public/145814835dd655bc5ab0d0.36753359/) to begin translation.

Thanks!

**Comment by sgttrs** [comment]
Thank you!
