### ISSUE TITLE
Widget Broke after first Beta

### ISSUE THREAD

**Issue by CrallH** [home-assistant/home-assistant-android#426]
**Home Assistant Android version: 1.7.2-128

**Android version: 10

**Phone model: Huawei P30 Pro

**Home Assistant version: 0.105.3

**Last working Home Assistant release (if known):last stable

**Description of problem: After the first beta release the widget just turn red when pressed. If a new widget is added it spins and turns green, but the old widgets wont work again.

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by KBerstene** [comment]
Do you know what version of the app you were previously using? Any widgets created in v1.5.0 won't work after the 1.6.0 upgrade (sorry). If you created them in 1.6, this is likely a bug.

**Comment by CrallH** [comment]
Don't know the version, but I created them in the first version that had widget option.

**Comment by KBerstene** [comment]
It sound like the old widgets just need to be recreated, unfortunately.  The 1.6.0 update broke backwards compatibility for the widgets that were introduced in 1.5.0.

**Comment by dshokouhi** [comment]
Closing as old widgets must be recreated in 1.6+
