### ISSUE TITLE
Notification problem

### ISSUE THREAD

**Issue by andreamastro** [home-assistant/home-assistant-android#437]
**Home Assistant Android version:**
1.7.2-128
**Android version:**
9
**Phone model:**
Huawei P20 Lite ANE-LX1
**Home Assistant version:**
0.105.3
**Last working Home Assistant release (if known):**

**Description of problem:**
I cannot receive notification with action button and when I send "request_location_update" I receive a notification with "request_location_update" as a text. I have not this problem with Xiaomi Mi8
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Try to start fresh on the device having issues, most likely you need to clean something up:

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app
