### ISSUE TITLE
Android battery level

### ISSUE THREAD

**Issue by peetereczek** [home-assistant/home-assistant-android#438]
## The problem

With version 0.105 you have announced that Android mobile app will report battery level to HA, but it does not:
![image](https://user-images.githubusercontent.com/42431204/74613883-24b08c80-5113-11ea-91be-9ec03597c8eb.png)
![image](https://user-images.githubusercontent.com/42431204/74613889-32fea880-5113-11ea-9d2b-89b15e277267.png)

What can I do to figure it out why I can't see battery level of my phone in device list? I see that there are errors, how can I fix them?

## Environment

- Home Assistant release with the issue: 0.105.4
- Last working Home Assistant release (if known): 0.105.4
- Operating environment (Hass.io/Docker/Windows/etc.): Docker Hass.io
- Integration causing this issue: mobile app 1.7.2-129
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/mobile_app/

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt
Refusing to update non-registered sensor: fc7ca061a3422d0c22ea06597a9103577cc604e3ccd2e2b98843236d6786ff98_battery_level
Refusing to update non-registered sensor: fc7ca061a3422d0c22ea06597a9103577cc604e3ccd2e2b98843236d6786ff98_wifi_connection

```

**Comment by allanpersson** [comment]
You will find the entity if you go to:
Configuration ➡️ Integrations ➡️ Find your device on the list and you will see 3 entities

**Comment by dshokouhi** [comment]
Looks like you need to clean things up, try running these steps and you should see the new sensors.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by peetereczek** [comment]
> Looks like you need to clean things up, try running these steps and you should see the new sensors.
> 
> https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

Thanks, that helped!
