### ISSUE TITLE
Add support for charger state

### ISSUE THREAD

**Issue by tiagofreire-pt** [home-assistant/home-assistant-android#440]
**Home Assistant Android version:** 
Last commit available on github.

**Android version:**
9.0

**Phone model:**
Samsung Galaxy J7 2017

**Home Assistant version:**
0.105.4

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**

The full integration of an android smartphone with its main status reported to Home Assistant would improve the data available for automations regarding the phone states:

The ones for the charging plug:
    android.intent.action.ACTION_POWER_CONNECTED
    android.intent.action.ACTION_POWER_DISCONNECTED

This possibility would be awesome for automations regarding routines and voice assistants.

This full integration on the HA app would require less complexity, resources used by a bunch of apps and generally more efficient workflow and HA configuration.

**Comments** 

Related to https://github.com/home-assistant/home-assistant-android/issues/201#issuecomment-584741995.

**Comment by allanpersson** [comment]
This is already implemented as an attribute of the battery sensor 🙏

**Comment by allanpersson** [comment]
![Screenshot_20200217-124643_Home Assistant](https://user-images.githubusercontent.com/46043392/74651247-ab9d4d80-5183-11ea-920a-e9c83e9019e6.jpg)

**Comment by tiagofreire-pt** [comment]
@allanpersson, thanks, I didn't notice it.  ❤️ 

I'm closing this issue.
