### ISSUE TITLE
Cannot view videos in full screen

### ISSUE THREAD

**Issue by a-jackson** [home-assistant/home-assistant-android#447]
**Home Assistant Android version:**
1.7.2-128
**Android version:**
10
**Phone model:**
Pixel 2 XL
**Home Assistant version:**
0.105.5
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
Video in a picture-entity card cannot be displayed full screen. I can do it on desktop and on the mobile website in both Chrome and Firefox but the full screen button in the bottom right corner of the video is greyed out in the app.

As a workaround I have been able to login on Chrome and then use Add to Home Screen, when opened like this it does allow full screen.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

![Screenshot_20200218-191710](https://user-images.githubusercontent.com/2199309/74770203-b212ee80-5283-11ea-8eb3-d4d43ee84765.png)
Full screen button is greyed out

**Additional information:**

I have seen this on 2 other phones, a Galaxy S9 and a Pixel 2 and one was a differnet Home Assistant server however I don't have version information for them.

**Comment by dshokouhi** [comment]
In https://github.com/home-assistant/home-assistant-android/issues/267 I did mention that the full screen button is disabled which prevents PiP from happening so this is either related or a duplicate

**Comment by dshokouhi** [comment]
Closed in #471
