### ISSUE TITLE
Google location enabled requirement to use 'internal connection url'

### ISSUE THREAD

**Issue by GreenhouseAU** [home-assistant/home-assistant-android#449]
**Home Assistant Android version:**
1.7.2-128

**Android version:**
Multiple
**Phone model:**
Multiple
**Home Assistant version:**
Home Assistant 0.102.3
**Last working Home Assistant release (if known):**
Don't know
**Description of problem:**
Google location services is required to be enabled in order to use the internal connection URL. If I enable it, the internal URL works. If I disable it, the app only uses the (external) home assistant URL.

I only enable location services when (rarely) driving as to not drain battery.

Can an alternate method be employed to see if the phone is 'home' (i.e. connected to the supplied SSID, current (DHCP) IP = 192.168.0.100 (for example))?

**Traceback (if applicable):**

**Screenshot of problem:**

**Comment by JBassett** [comment]
Without the location permission we cannot get the connected WiFi SSID.  You don't need to enable location tracking, just give the application permission for it to work.

**Comment by GreenhouseAU** [comment]
Permission was already granted to the app before posting this. It doesn't change the fact that Google location must be enabled in order to use the 'internal url'.

**Comment by GreenhouseAU** [comment]
@JBassett - is it possible to open this up again please? I believe this is a legitimate issue as the behaviour does not follow a settings logic....

**Comment by theloukou** [comment]
Please re-open this issue.
I have the same problem as OP. Location permission is granted, app stil can't "read" SSID if actual location services are disabled. Works fine with it on, not with it off. Reads out "<unknown ssid>".
This probably goes beyond the permission itself.
Running Android 9, latest app version. I would be glad to provide logs, or any kind of needed information.

**Comment by dshokouhi** [comment]
@theloukou you need location permission and also location services enabled in order for it to work, if you turn it off you will get the error.

**Comment by theloukou** [comment]
I am pretty sure this is not always true. I have two more devices that work just fine without location services on, and two friends with their own setups, both of theirs work fine as well with services off.

**Comment by GreenhouseAU** [comment]
> @theloukou you need location services enabled in order for it to work

That's the whole point of this issue. It's a battery draining/privacy reducing setting that shouldn't be required if you are home (and mine is disabled most of the time). Surely there is another option (as I suggested in the original post)?

**Comment by tsdogs** [comment]
I confirm the issue. Having geolocation to be turned on when at home it's an issue.
It's anyway related to android 8.0+ and don't think there's much we can do. 
It has to do with privacy and here there's a clear explanation:
https://www.davx5.com/faq/wifi-ssid-restriction-location-permission
