### ISSUE TITLE
Cloudflare 2FA - Disallowed user Agent

### ISSUE THREAD

**Issue by darox** [home-assistant/home-assistant-android#45]
I protect my Home Assistant Setup towards the internet through Cloudflares 2FA system. However, when manually entering the address of my instance, I get disallowed user Agent from Google. 

See screenshot: https://imgur.com/a/zCtcgbX

Any chance that this can be fixed?

**Comment by fanaticDavid** [comment]
I have the same problem. I have my Home Assistant instance running behind an NGINX reverse proxy. To add an extra layer of security, I set up NGINX to use Google OAuth. When I manually enter the external URL to reach my HA instance, it shows me the "Sign in with Google" button (as it should) but when I tap that, I get the 403 error `disallowed_useragent`.

**Comment by balloob** [comment]
Since the login workflow with Google cannot be run within an embedded webview, there is no way for us to intercept the cookies.

If it were possible to intercept cookies, it would complicate the app a lot. This is not something we should add to the official app.

**Comment by darox** [comment]
Many thanks for having a look into it!

**Comment by fanaticDavid** [comment]
I'm assuming there isn't a path (other than the root one) which could be excluded from authentication to allow the app to communicate with the Home Assistant instance?

**Comment by CuriousDebate** [comment]
I found the workaround for an android phone to still have the app feel. Just login with Chrome browser. Then click the hamburger menu, add to desktop. Android creates an "App" that I've seen functions just like the full android app. Any advantages to using the Android app over this chrome kinda app?

**Comment by hetlelid** [comment]
Another workaround would be to additionally enable the option in cloudflare to send OTP to your email address. You the will need to whitelist all the emailaddresses allowed to login with OTP. This works fine for development purpose at least
