### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by ApexInfosysIndia** [home-assistant/home-assistant-android#459]
Hi there,

Push notifications aren't working. All the other features including location tracking, etc. are working fine. Please help

**Comment by allanpersson** [comment]
Please don't remove template, the informations there is important 🙏

**Comment by ApexInfosysIndia** [comment]
What information do you need?

**Comment by allanpersson** [comment]
All the lines from the issue template (the ones you deleted)
https://github.com/home-assistant/home-assistant-android/issues/new?assignees=&labels=bug&template=Bug_report.md&title=

**Comment by dshokouhi** [comment]
Closing in favor of #460

**Comment by ApexInfosysIndia** [comment]
1.7.2-2

10.0

Oppo Reno 2

Home Assistant 0.105.5

Only works with the official (play store)

Push notifications aren't working. All the other features including location tracking, etc. are working fine.

**Comment by dshokouhi** [comment]
@ApexInfosysIndia lets stick to 1 open bug please :)
