### ISSUE TITLE
Repeated log in logbook (device_tracker status)

### ISSUE THREAD

**Issue by Sebclem** [home-assistant/home-assistant-android#487]
**Home Assistant Android version:**
1.8.0-145
**Android version:**
9
**Phone model:**
Galaxy S8 (SM-G950F)
**Home Assistant version:**
0.106.2
**Last working Home Assistant release (if known):**

**Description of problem:**
I have just noticed that i have a lot of repeated logs in the logbook for the device tracker status.
The logs repeatedly say `S8-Seb is at home` or `S8-Seb is away` every minutes.
I don't know if it's related to the android app or directly to Home assistant.
**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/23737709/75692554-08315a00-5ca6-11ea-92e9-bef0014cf6ac.png)

**Additional information:**

**Comment by dshokouhi** [comment]
I think this might be a `logbook` issue and not an Android app issue.  The app is just reporting location to HA and logbook is displaying that data.

**Comment by Sebclem** [comment]
Yes you're right, it's seem that after a supervisor restart, the logs stop spamming.
My bad, sorry for the useless issue
