### ISSUE TITLE
When full screen mode is enabled the keyboard does not push up text input fields

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-android#488]
**Home Assistant Android version:**
1.8.0-144
**Android version:**
10
**Phone model:**
Pixel 4 XL
**Home Assistant version:**
0.106.2
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**

When I enable full screen mode under App Configuration anything in the HA UI that has an input text field is hidden behind the keyboard.  When I disable full screen mode the text fields push up properly and are not behind the keyboard.

Steps to reproduce:
1. App configuration > turn on full screen
2. Configuration > Users
3. Add user

see screenshot below

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/1634145/75706994-f7b3bc00-5c72-11ea-868f-cfff1ec450fd.png)

**Additional information:**

**Comment by neopilou** [comment]
It's a common old 10 years issue with webview in fullscreen (https://issuetracker.google.com/issues/36911528). 
I'll make a pull request very soon to fix it.

**Comment by JBassett** [comment]
Fixed via https://github.com/home-assistant/home-assistant-android/pull/492
