### ISSUE TITLE
Unify geocoded locations and zones for tracking

### ISSUE THREAD

**Issue by McGiverGim** [home-assistant/home-assistant-android#497]
**Is your feature request related to a problem? Please describe.**
The zone tracking does not seem very reliable. Sometimes it takes more than 1 hour to detect that someone has left a zone, others works perfectly. Usually is good to detect when entering a zone, but not when leaving it.

Of course, I have tested to not optimize battery in the app, enable location always, enable data always, etc.

**Describe the solution you'd like**
I have observed that the new geocoded locations are updated more often in the History of HA than the zones one. In the history of HA I can see that the person is at X zone, but the geocoded location shows a very different place (new and and more accurate) at 100Km of distance.

If can be done, I think the zone location of the person must be a "join" of both solutions, zone and geocoded. The real one is the latest received.

The solution is not perfect, sometimes the geocoded location takes time too to detect where it is, but usually detects it before.

**Describe alternatives you've considered, if any**
Make the zone location work faster, but I suppose this is on the Google side. I don't know if we can do something to help with it.

**Additional context**
Nothing.

**Comment by dshokouhi** [comment]
So as of now all sensor updates are tied to location updates.  The geocoded sensor only updates when location is updated, like the other sensors.  Instead of looking at the zone the device is in when you look at the history you will want to look at the GPS coordinates as those will correlate better to the actual updates being sent.

**Comment by allanpersson** [comment]
A (temporary) solution is for you to send intent, see https://companion.home-assistant.io/docs/core/location

**Comment by McGiverGim** [comment]
I'm not too sure if I'm understanding the situation. If I understand it right, all the sensors are updated with each location update, and this location update is tied to the GPS coordinates of the device.

If that is true, then I don't understand that, from yesterday:

![image](https://user-images.githubusercontent.com/2673520/75910594-6a2cc380-5e4e-11ea-88c8-912e1b495f9a.png)

Pixel is the phone of my wife, that is used for tracking. Piedad is my wife, she is at the same place than Pixel all the time, of course. 

`Chamartin` is a train station. I want to be notified when my wife takes the train, so I have a zone there. The Pixel is showing like she was there until 16:45:20:
![image](https://user-images.githubusercontent.com/2673520/75910783-c5f74c80-5e4e-11ea-9a84-2ba3f0e96ce2.png)

But the Geocoded info shows a lot more changes in location, here for example at the 16:28:16 in Segovia, at 100Km of Chamartin:
![image](https://user-images.githubusercontent.com/2673520/75911002-22f30280-5e4f-11ea-9154-a1f1fb388824.png)

If I have understood, this location update, Segovia, comes with GPS coordinates and all the sensors must be updated, so the Pixel and Piedad must detect that and detect that this coordinates are out of the Chamartin zone, but it doesn't.

Thanks for your time and sorry if I have not understood it right :(

**Comment by dshokouhi** [comment]
@McGiverGim so a zone is defined based on GPS coordinates and it also accounts for the radius that is set: https://www.home-assistant.io/integrations/zone#radius

Geocoded location just takes the current GPS coordinates and translates them into an address instead of latitude and longitude coordinates.  So if the device moves a few meters the zone may not change but the address might change.

One other thing to consider is the GPS accuracy used, that also falls into account when determining the device tracker location.  Geocoded location I believe does not care about the accuracy here I think however for the device tracker if the accuracy is too low it will skip that update or request a more accurate location.

@JBassett did I get this right or did I misunderstand something here?

**Comment by McGiverGim** [comment]
This is the reason why I shown a geocoded point at 100 kilometers of my zone. The radius of the zone is only about 100 or 200 meters, so is it out of the zone by a lot.
The zone only changes when he arrives to the next station, at 200 kilometers of the origin.

**Comment by JBassett** [comment]
@dshokouhi you are 100% correct.  We added logic to limit the inaccuracy of the `device_tracker` sensor.  However, we did not add any logic to the Geocoded Location, it simply takes the center of the last location, no matter how inaccurate and pulls an address from that.

**Comment by McGiverGim** [comment]
So what you say is that if the "precision" of the device_tracker sensor is low, the zone tracking ignores the value and does not change?
If that is true, maybe can you add a selection combo as beta/experimental feature that lets the user select the limits for that? I'm pretty sure this inaccuracy is very conservative, at least what I have observed. Tracking my wife using Google Maps I can see the radius and is not too big in the major part of the travel.

**Comment by McGiverGim** [comment]
I suppose this is the PR that added the accuracy filtering, true? https://github.com/home-assistant/home-assistant-android/pull/181

**Comment by McGiverGim** [comment]
I've been thinking about it... What about a second filter about the accuracy?

I don't know how much data we have in the app, but if we have enough, we can do something like that:

1. If the accuracy of the new location is smaller than the minimum accuracy defined, send the location, like now. This is the actual behaviour and does not change nothing.
2. If the accuracy of the new location is bigger than the minimum accuracy, then:
2.1. If the old location was inside a zone, and the new location is detected like away, then send the new location if the `distance > (np_accuracy + z_radius)`
![image](https://user-images.githubusercontent.com/2673520/76110634-1f8e8100-5fdf-11ea-99fb-a17dc1f0cd87.png)
2.2. If the new location is inside a zone, and the old location was away or in a different zone, then send the new location if `distance + np_accuracy < z_radius`:
![image](https://user-images.githubusercontent.com/2673520/76110920-a80d2180-5fdf-11ea-86f7-674fd5985c68.png)

In this way, we only send the location when the new position is completely inside the zone, including the accuracy. This give us more margin in the accuracy, especially when going from a zone to away, to detect correctly the change of state and start automations that now are being blocked by an accuracy too exigent. This will only be used when changing zone, while staying in the zone only the point 1 is used, like now, so the GPS coordinates will be the same than now the major part of the time. And can be an option "Smart zone detection" or similar deactivated by default.

What do you think?

**Comment by fineemb** [comment]
The current problem is that device_tracker (latitude, longitude) and geocoded (Location attributes) are not the same, not the same as the new frequency and results

**Comment by McGiverGim** [comment]
True, but I suppose that if ones refreshes the data, is because the phone has new GPS coordinates and calls both methods, but one gets discarded by the minimum accuracy filter and the other has not filter at all.

So I think it will be good to modify the filter (making it bigger or making it smart, at least as option).

Maybe my case is the worst, my wife takes a high speed train that can go at more than 300Km/h, with tunnels, etc. With the speed and I suppose the metal of the train the accuracy maybe is never below the minimum, so it takes 200Km of distance for the device_tracker to update it (when she arrive to the destination) but I can see in the geocoded log that it has several points in the travel and they are accurate enough.

Regards and thanks for your great software!!

**Comment by McGiverGim** [comment]
Can you confirm that the "fix" is simply to filter the geocoded locations too? So no solution for us?

**Comment by JBassett** [comment]
For now yes.  I'm not opposed to making the logic smarter but the quick fix was, well, quick. ;-) Feel free to open a feature request with the details of the logic.  However when we determine you broke a zone, we already retry and attempt to get higher accuracy if the accuracy didn't meet the requirements.

**Comment by McGiverGim** [comment]
Thanks! I will open a new feature request later.

**Comment by McGiverGim** [comment]
Opened: https://github.com/home-assistant/home-assistant-android/issues/518 if someone wants to track the problem.

**Comment by slydiman** [comment]
> The current problem is that device_tracker (latitude, longitude) and geocoded (Location attributes) are not the same, not the same as the updata frequency and results

I see the same and it is not fixed. I have only 1 zone with a small radius and the device_tracker.my_phone always shows "at home". But the sensor.my_phone_geocoded_location shows the correct location and address (few miles from the zone).

I'm trying to create a template device_tracker parsing sensor.my_phone_geocoded_location.location to device_tracker.my_phone.latitude/longitude
