### ISSUE TITLE
Multiple SSID entry unclear

### ISSUE THREAD

**Issue by Knoxie** [home-assistant/home-assistant-android#498]
**Home Assistant Android version:**
1.8-147
**Android version:**
10
**Phone model:**

**Home Assistant version:**

**Last working Home Assistant release (if known):**

**Description of problem:**
Adding entries into the list is unclear as there is no on screen 'add' button. Just a checkbox via keyboard. This is not clear to the user that they need to push the check to complete the process. Typing SSID in and hitting save doesn't add the new SSID as expected.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by JBassett** [comment]
@Timmmeeeh can you take a look?

**Comment by dshokouhi** [comment]
@Knoxie great find!  Looks like this is partially working.  Instead of clicking Save after typing in the SSID hit "enter" on the keyboard and it looks like it actually creates the list at that point, you still need to click save once added to the list.  So we not only need an add button but we also need to ensure the SSID that is entered into the field also gets saved when user select save. On my end I did not see a checkbox.

**Comment by Knoxie** [comment]
There was no checkbox, but they keyboard changed from enter to check. I didn't notice until the second time. 

I think using an Add button would be more intuitive for the user to realize they can add multiple. Otherwise they may: Open Dialog - > Type -> hit save, re-open dialog ->Type -> save etc. instead of  Open -> type -> add -> type -> add etc.

**Comment by Knoxie** [comment]
https://developer.android.com/reference/android/net/wifi/WifiManager#addNetworkSuggestions(java.util.List%3Candroid.net.wifi.WifiNetworkSuggestion%3E)

What about showing a list of previously connected to networks that you can select from. Be nice for people with several networks, or networks with long complex names.

**Comment by JBassett** [comment]
@Knoxie I agree that would be a good feature request, but the scope of the original bug has been fixed.  Please create a new feature request for populating the autocomplete.

**Comment by Knoxie** [comment]
No
