### ISSUE TITLE
Register with mobile app integration

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#5]
This allows users to see the mobile app in their Home Assistant installation and gives the app urls to communicate with the instance while away from home. 

https://developers.home-assistant.io/docs/en/app_integration_setup.html#registering-the-device-1

**Comment by BCNelson** [comment]
@JBassett Is this done in #25 if not what still needs to be done

**Comment by JBassett** [comment]
@BCNelson The only thing left is to use the stored url for remote ui on the webview.  But that probably belongs with the issue for having multiple urls for home vs away.

**Comment by balloob** [comment]
Will create a new issue for that.
