### ISSUE TITLE
Unable to find Home Assistant instance

### ISSUE THREAD

**Issue by ofalvai** [home-assistant/home-assistant-android#50]
The auto scanning feature can't find my HA instance. I'm on the same network, I have location enabled.
HA version: 0.101.2

**Comment by aaamoeder** [comment]
same for me.. cannot find it, and when I manually enter the url and press enter nothing happens..

**Comment by andriej** [comment]
For me it couldn't find it alghough manually added adress worked flawlessly.

**Comment by aaamoeder** [comment]
> For me it couldn't find it alghough manually added adress worked flawlessly.

what did you enter as url ? I entered "https://xxx.xxx.xxx.xxx:8123" and then nothing happened.

**Comment by andriej** [comment]
OP6 with And10 here. 
I've entered https://my.domain (as it's on standard https port).
Do you have HTTPS service on 8123? Try without the s in https.

**Comment by aaamoeder** [comment]
Now it's working but only when using the external URL and not the local IP adress.. which I find odd..

**Comment by CedrickFlocon** [comment]
Duplicate : https://github.com/home-assistant/home-assistant-android/issues/6

**Comment by trrevvorr** [comment]
Manually entering the eternal url (hosted via nabu casa) is the only way I could get it to work as well. For me, this is preferable though as I want to access my HA instance when not at home on my phone.
