### ISSUE TITLE
Add light sensor

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/home-assistant-android#501]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a nice to have feature for wall mounted tablets.

**Describe the solution you'd like**
I imagine myself and others probably have some wall mounted tablets with the android app installed.  As these devices are always plugged in it would be useful to get a light sensor as that can allow us to have these sensors in each area for automating light brightness.

**Describe alternatives you've considered, if any**
We can currently use Tasker to grab these values and send them back however it involves a lot of setup. 

**Additional context**
Sensor information can be found here: https://developer.android.com/guide/topics/sensors/sensors_environment

Not sure if the other sensors are there but light is definitely there for any device that does auto brightness.

**Comment by balloob** [comment]
It's not the focus of our app to add a ton of features for tablet use. Our focus is to be used on phones, not as an always on solution. I don't think that we should add this.

**Comment by Hypfer** [comment]
Could be interesting from an environment monitoring standpoint, though.

**Comment by simbus82** [comment]
> It's not the focus of our app to add a ton of features for tablet use. Our focus is to be used on phones, not as an always on solution. I don't think that we should add this.

So for a Tablet use the best solution is to open HA with a browser? Only for information...

**Comment by balloob** [comment]
@simbus82 you can still use the app. It's just that we shouldn't add features that are not contributing to the phone experience.
