### ISSUE TITLE
Color Statusbar

### ISSUE THREAD

**Issue by broesie** [home-assistant/home-assistant-android#505]
I’m using the android app, and I’m using themes, however if I open with the app, the statusbar keeps using a blue color. If I open it with chrome, it use the color of the theme. Is it possible to change it, so we can use the colors of themes?

In the app:
![statusbar_app](https://user-images.githubusercontent.com/21012345/76142668-14376600-6070-11ea-963b-96b7e5e0dd61.png)

In Chrome:
![statusbar_chrome](https://user-images.githubusercontent.com/21012345/76142672-1a2d4700-6070-11ea-8667-4257241c3048.png)

**Comment by JBassett** [comment]
Duplicates: https://github.com/home-assistant/home-assistant-android/issues/272
