### ISSUE TITLE
Scroll bar on the bottom as an option?

### ISSUE THREAD

**Issue by Wibias** [home-assistant/home-assistant-android#507]
Hey!

Would it be possible to get the scrollbar to the bottom of the screen, as an option for the users or make more space for it at the top? Even on a big phone like the p30 pro there is only space for 2 icons while scrolling because of the arrows. 
Or just remove the arrows and instead make more room for the icons of the views.

**Comment by balloob** [comment]
We don't control the frontend, we just render the Home Assistant frontend. You should open a request there.
