### ISSUE TITLE
Add screen saver option

### ISSUE THREAD

**Issue by dmaciaszek** [home-assistant/home-assistant-android#509]
**Is your feature request related to a problem? Please describe.**
I have wall mounted tablet. After some time when app not used it would be nice the screen go to "sleep" .

**Describe the solution you'd like**
 It would be nice to have somethink like screen saver e.g. displaying big clock (time) or configurable background. After tap on screen, app could be wake up (or maybe based on motion sensor).

**Additional context**
Similar solution closed https://github.com/home-assistant/home-assistant-android/issues/325. But I think https://play.google.com/store/apps/details?id=app.homehabit.view&hl=pl is good example. There is option to set screen saver displaying time.

**Comment by balloob** [comment]
It's not the focus of our app to add a ton of features for tablet use. Our focus is to be used on phones, not as an always on solution. We shouldn't add this.

**Comment by dmaciaszek** [comment]
Ok thanks for reply. I think many people will be happy for tablet features becasue the official android app is great and there is no need to use third party apps for wall mounted devices. Especially HA 0.107 release have option to define many dashboards in side menu. But I understand your point of view so maybe in the future. Thanks.
