### ISSUE TITLE
New card picker looks weird

### ISSUE THREAD

**Issue by escoand** [home-assistant/home-assistant-android#511]
**Home Assistant Android version:**
1.8.0-144

**Android version:**
7.1.2

**Phone model:**
Motorola Moto G4

**Home Assistant version:**
0.107dev

**Last working Home Assistant release (if known):**

**Description of problem:**
The new card picker looks weird in the app. The mobile chrome browser does not have this problem.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![Screenshot_20200310-203339](https://user-images.githubusercontent.com/428567/76352406-49151880-630f-11ea-9c2b-287e0c7e998d.png)

**Additional information:**

**Comment by JBassett** [comment]
Could you retest please @escoand.  I am unable to reproduce on the latest dev build.

**Comment by escoand** [comment]
You're right, it's working now.
