### ISSUE TITLE
Privacy Issue: geocoded location is sent regardless of tracking settings

### ISSUE THREAD

**Issue by make-all** [home-assistant/home-assistant-android#513]
**Home Assistant Android version:**
1.8.0-144

**Android version:**
9.1.0

**Phone model:**
Samsung A20S

**Home Assistant version:**
0.106.5

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**
In home assistant logbook, the "Geocoded Location" of a user can be seen, even when they have both Background Location Tracking and Zone Based Tracking disabled.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
Expectation would be to only report geocoded location when location is being reported based on the zone and background location settings.

**Comment by dshokouhi** [comment]
The geocoded sensor is separate from the device tracker and location tracking settings.  If you do not wish to use it then simply disable the entity from the integration panel.

![image](https://user-images.githubusercontent.com/1634145/76371179-abadea80-62f6-11ea-9bcb-5a90ea3e1d38.png)

**Comment by make-all** [comment]
The issue is not on the server side.

It is a privacy issue for the phone to be sending this information without express user consent in the first place, whether the server is recording it or not. 

It is a reasonable user expectation that if they disable background location tracking, they are not tracked outside of the defined zones. And if they disable both background and zone based tracking, their location is not tracked at all.

**Comment by andriej** [comment]
Agree on OPs issue, currently it's not clearly stated and visible for user (user, not admin of HA) on what's he/she js agreeing on.
