### ISSUE TITLE
FEATURE REQUEST - Support Dynamic Attachments

### ISSUE THREAD

**Issue by sparkydave1981** [home-assistant/home-assistant-android#515]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Provide support in the Android app for the Dynamic Attachments (that are available for iOS) [as per the docs](https://companion.home-assistant.io/docs/notifications/dynamic-content/).

**Describe alternatives you've considered, if any**
N/A

**Additional context**
DYnamic attachments make things like [sending camera snapshots as a notification](https://companion.home-assistant.io/docs/notifications/dynamic-content/#camera-stream) super easy and would be awesome to have in the Android app.  Given that this is already available for iOS, the code is obviously in HA, we just need the Android app to support it.

**Comment by JBassett** [comment]
Unfortunately as far as I know and could dig up in documentation, Android doesn't support this type of notification.
