### ISSUE TITLE
Different groups for notifications

### ISSUE THREAD

**Issue by McGiverGim** [home-assistant/home-assistant-android#519]
**Is your feature request related to a problem? Please describe.**
When you use the app notifications a lot, is difficult to know when they are important (alarm for example) or informative only.

**Describe the solution you'd like**
Android let's divide the notifications in different groups, with different sounds, visibility, etc.. Let assign a group in the service as optional parameter when sending the notification.

**Describe alternatives you've considered, if any**
None.

**Additional context**
None.

**Comment by JBassett** [comment]
Duplicate: https://github.com/home-assistant/home-assistant-android/issues/107
