### ISSUE TITLE
Question - Ariela

### ISSUE THREAD

**Issue by Wibias** [home-assistant/home-assistant-android#52]
Hey ho! 

Out of Curiosity is there a reason you the official app developers are not working together with the Arieal App Developer? Was using the Ariela App for the longest, but since it's sadly only one developer, so progress can be kinda slow and its also not open source. So I will most likely switch to the official App for the above Reasons. But the Ariela app has some cool functions so it would be cool if both Apps got merged! :D

**Comment by balloob** [comment]
Ariela is not open source and added some functions that are too advanced for the official app.
