### ISSUE TITLE
Battery sensor not updated when location permission is disabled

### ISSUE THREAD

**Issue by vigonotion** [home-assistant/home-assistant-android#520]
**Home Assistant Android version:**
1.8.0-144
**Android version:**
10

**Phone model:**
Samsung Galaxy S10 Plus

**Home Assistant version:**
0.107.0b1

**Last working Home Assistant release (if known):**

**Description of problem:**
My family members don't want to be tracked, so I disabled the location permission for Home Assistant. Now, the battery sensors don't update anymore. Battery sensors should still show up in Home Assistant.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**
I'm willing to grant Home Assistant the location permission, but then I'd need a switch to disable reporting to Home Assistant from inside the App

**Comment by dshokouhi** [comment]
This is actually as designed.  Location must be enabled for the app in order for sensor updates to be sent to HA.

https://companion.home-assistant.io/docs/core/sensors

You can simply disable the `device_tracker` entity from the integration screen so you won't get any location updates.

**Comment by vigonotion** [comment]
I know that I can disable the entity in Home Assistant, but this would leave me in the power of re-enabling it whenever I want, which I think is suboptimal. But as you stated, this is not a bug on the Android app, so I'm closing this.
