### ISSUE TITLE
Locations received while offline are never reported to HA

### ISSUE THREAD

**Issue by Hypfer** [home-assistant/home-assistant-android#521]
**Home Assistant Android version:** 1.8.0-153

**Android version:** 9

**Phone model:** Moto Z3 Play

**Home Assistant version:** 0.107.0

**Last working Home Assistant release (if known):** /

**Description of problem:**
Currently, there's no local cache for received locations which haven't been persisted to the HA server yet.

This is problematic for situations such as roaming or a hiking trip somewhere without cellular coverage since they simply vanish from the timeline

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by balloob** [comment]
Home Assistant does not allow writing historical data. If we would store them locally then it would look like they all got in at the same second, which would be wrong.

**Comment by Hypfer** [comment]
@balloob 

True. Will this limitation be changed at some point or is that a design decision?

**Comment by balloob** [comment]
It's a design decision in the core of Home Assistant. It would break all automations ever, so I would not count on it.

**Comment by Hypfer** [comment]
Hm. But why would it?

Of course it doesn't make sense to react to events in the past, but looking at the data logging aspect of home assistant, I do think that it might make sense to provide a way to add to the data store without any other automation processing.

Only downside being that it might confuse people since the state an automation acted upon might be changed later but that could probably also be avoided by marking non-realtime events.

Would it make sense to move this discussion into a separate thread in the correct space or is this decision final?
