### ISSUE TITLE
Mobile app notification does not work

### ISSUE THREAD

**Issue by psamim** [home-assistant/home-assistant-android#522]
**Home Assistant Android version:**
1.8.0-144
**Android version:**
10
**Phone model:**
Galaxy S10+
**Home Assistant version:**
0.107.4
**Last working Home Assistant release (if known):**

**Description of problem:**
When trying to send a notification to mobile app using the `notify.mobile_app_**` service from the developer tools I get the below error.

**Traceback (if applicable):**
```
hass         | 2020-03-21 22:37:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2961320208] 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://mobile-apps.home-assistant.io/api/sendPush/android/v1
hass         | Traceback (most recent call last):
hass         |   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
hass         |     connection.context(msg),
hass         |   File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
hass         |     await asyncio.shield(self._execute_service(handler, service_call))
hass         |   File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
hass         |     await handler.func(service_call)
hass         |   File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
hass         |     await notify_service.async_send_message(**kwargs)
hass         |   File "/usr/src/homeassistant/homeassistant/components/mobile_app/notify.py", line 135, in async_send_message
hass         |     result = await response.json()
hass         |   File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1031, in json
hass         |     headers=self.headers)
```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/1868679/77233463-30d1b300-6bc5-11ea-86da-0a7a3aceac52.png)

**Additional information:**

**Comment by dshokouhi** [comment]
Can you please share the service data that you used?

**Comment by psamim** [comment]
@dshokouhi Sure.

```yaml
message: "Hello"
```

![image](https://user-images.githubusercontent.com/1868679/77233898-3ed50300-6bc8-11ea-8a5f-a4306560cacd.png)

**Comment by dshokouhi** [comment]
@psamim can you try these steps: https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

then try again?

**Comment by psamim** [comment]
@dshokouhi
I did with no luck. I see the error again.

I am not sure but I can have some guesses here. I live in Iran and I guess calling the Firebase services from Iran are blocked. Assuming the service is not calling Firebase directly and also assuming it does check the result back from Firebase before itback to HA server, it might not be an issue.

**Comment by dshokouhi** [comment]
Does this URL resolve for you? https://mobile-apps.home-assistant.io/api/sendPush/android/v1

The service doesn't call firebase directly but it relays it from a HA server to firebase.  Firebase is needed to send notifications to your device.

https://github.com/home-assistant/mobile-apps-fcm-push

**Comment by psamim** [comment]
@dshokouhi No, I get 403 error from the URL above.

**Comment by dshokouhi** [comment]
403 is ok, thats an authentication error so it is able to resolve but probably not able to send to your device is my guess.  Can you maybe try with a VPN? Just guessing here :)

**Comment by psamim** [comment]
No I am getting 403 from Google itself and not the relay server. It seems the request does reach the relay server. I think the reason may be that the relay server is served on Google Cloud. Is it? Becaus as I know Google blindly and entirely banns every request from Iran (and some others) to everything that it hosts.

Thanks for your time and quick responses. So I think there is nothing you can do except moving the relay server to another data-center which I assume you would not :).

**Comment by dshokouhi** [comment]
I am not certain about that, we can wait for one of the developers to chime in on that.

**Comment by psamim** [comment]
When I run
```bash
curl https://mobile-apps.home-assistant.io/api/sendPush/android/v1
```

This is what I get from an IP from Netherlands using a VPN:

```
{"errorMessage":"You did not send a token!"}%
```

This is what I get from an IP from Iran:
``` 
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/androidV1/api/sendPush/android/v1</code> from this server.  <ins>That’s all we know.</ins>

**Comment by JBassett** [comment]
There isn't much we can do if you instance of HA can't reach the servers to send the notifications unfortunately.  If you can proxy/vpn that traffic to a location that can hit the Google servers your notifications _should_ work.

**Comment by psamim** [comment]
@JBassett I understand. Thanks. I just have a suggestion here. I know that I am not the first person facing this issue and using HA in countries banned by Google or behind some firewal. Can we have small side note somewhere to inform users that for the notification to work the HA instance need to access the endpoint?

**Comment by angeltonio** [comment]
What happens to you also happens to me, I do not understand why if I am in the same Wi-Fi of my HA I have to be connected to the Internet to receive notifications and besides that it seems to be blocked for many countries ...

**Comment by angeltonio** [comment]
HA can be used without an Internet connection but it seems you need for some important things the notifications to be connected to the Internet, I think push notifications do it that way as they did it is not the best option ..

**Comment by Andalaosa** [comment]
https://companion.home-assistant.io/docs/notifications/notification-details/

Rate limiting#
Currently, you are allowed to send a maximum of 500 push notifications per day per device. The rate limit resets at midnight UTC daily. This is to ensure that the service remains cheap to maintain. In the future we may add support for upgrading to allow more notifications.

**Comment by mmojadad** [comment]
@psamim
Hi, Did you find any solution for Iran location?

**Comment by dshokouhi** [comment]
> @psamim Hi, Did you find any solution for Iran location?

use persistent connection for notifications

https://companion.home-assistant.io/docs/notifications/notification-local

**Comment by psamim** [comment]
Or use HTTP proxy.

I set up Privoxy so that it only forwards some URLs to another upstreadm proxy:

```
forward-socks5 .home-assistant.io 192.168.31.20:1080 .
forward-socks5 .googleapis.com 192.168.31.20:1080 .
```

But to make Hass use the HTTP proxy, I had to set `HTTP_PROXY` env var and also manually modify `/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py` to [make it respect and use this env var as said here](https://github.com/home-assistant/core/issues/36788).
