### ISSUE TITLE
Monitor battery status

### ISSUE THREAD

**Issue by Nihvel** [home-assistant/home-assistant-android#53]
Using the app as a kiosk, it will be handy to be able to monitor the status of the battery especially for those tablets that don't always stay attached to the wall and connected to a power source.

The Amazon Fire HD 7 (and probably few others) do not have the GPS module and applications like GPSLogger for logging the location and the battery can't properly work. A work-around I am using is by having a Fake GPS app running in background. Recently the tablet stopped sending messages to HA, don't understand why, therefore the battery status can't be tracked anymore.

The android app could solve this issue even though this means having it running in background. GPSLogger installed in my smartphone works great and the message with location and battery are sent every 15 minutes (take this as a little hint).

Thank you!

**Comment by balloob** [comment]
Custom sensors is supported by the mobile app integration and could be included with location info https://developers.home-assistant.io/docs/en/app_integration_sensors.html

**Comment by Nihvel** [comment]
Thanks, but I meant something more user-friendly: I don't understand a thing from that documentation because I'm a non-developer. And anyway, even if I were one, the issue opened here would like to ease this functionality. Waiting feedback! But thanks again for the project

**Comment by dshokouhi** [comment]
@Nihvel the comment from balloob was more guidance to whomever is going to pick up this feature request to develop it.  You will need to wait for someone to implement it so you can get the battery information.

**Comment by Nihvel** [comment]
@dshokouhi alright, makes more sense now, thanks for explaining ;)

Just as a note: I did enable the _mobile_app_ in _configuration_ and the integration saw the tablet on 2 rows. Not sure about which one was what. In the _developers_ tab it appeared the _device_tracker.my_tablet_ (both of them) but without much information.
Only _name_ and source. Source was set to _GPS_.
Probably, since this tablet does not have a GPS, it just didn't work.

So well, for whomever is going to pick this up: Probably an integrated mqtt client or rest api but anyway that wouldn't depend by the location, is a good solution.

Thanks again!
