### ISSUE TITLE
crash after logging in

### ISSUE THREAD

**Issue by BMicraft** [home-assistant/home-assistant-android#55]
When logging into my server manually (using https on a public nginx proxy server) the app crashes right after a successful login.

The page reloads as if to show my devices but then the app closes without a message right after loading in the blue header bar. Reopening the app looks like opening it the first time, nothing saved.

Device: OnePlus 7 with Android 10, rooted
Android System WebView 78.0.3904.108
Home Assistant App: 1.0.0
Home Assistant: 0.101.3

I have seen #32 but I do not think this applies here as no errors are logged. This is from my nginx `access.log`:
```<MY_IP> - - [22/Nov/2019:02:41:28 +0100] "GET /api/websocket HTTP/1.1" 101 32616 "-" "Mozilla/5.0 (Linux; Android 10; GM1900) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:43 +0100] "GET /auth/providers HTTP/2.0" 200 60 "https://<FQDN>/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:43 +0100] "POST /auth/login_flow HTTP/2.0" 200 173 "https://<FQDN>/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:56 +0100] "POST /auth/login_flow/bb1092ff5e444c2e82dc32d6cf2476c2 HTTP/2.0" 200 182 "https://<FQDN>/auth/authorize?response_type=code&client_id=https://home-assistant.io/android&redirect_uri=homeassistant://auth-callback" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:56 +0100] "GET /?external_auth=1 HTTP/2.0" 200 1315 "-" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:56 +0100] "GET /frontend_latest/chunk.c7b017ac9eca58717858.js HTTP/2.0" 499 0 "https://<FQDN>/?external_auth=1" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:56 +0100] "GET /frontend_latest/chunk.807c6f34c5c530f4cca6.js HTTP/2.0" 499 0 "https://<FQDN>/?external_auth=1" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:56 +0100] "GET /frontend_latest/chunk.458ea1d430f92886bbd0.js HTTP/2.0" 499 0 "https://<FQDN>/?external_auth=1" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:56 +0100] "GET /frontend_latest/chunk.64c373937461d7f4df1a.js HTTP/2.0" 499 0 "https://<FQDN>/?external_auth=1" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:56 +0100] "GET /frontend_latest/chunk.2695d3b011f65d298b38.js HTTP/2.0" 499 0 "https://<FQDN>/?external_auth=1" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
<MY_IP> - - [22/Nov/2019:02:41:56 +0100] "GET /frontend_latest/chunk.3a3de4e2d7b60783b7b2.js HTTP/2.0" 499 0 "https://<FQDN>/?external_auth=1" "Mozilla/5.0 (Linux; Android 10; GM1900 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36"
```
Let me know if you need to know more

**Comment by CedrickFlocon** [comment]
Hello @BMicraft.
Could you try with a newer version (we have a continuous deployment with [Firebase App Distribution](https://appdistribution.firebase.dev/i/KSHQEptq))

**Comment by BMicraft** [comment]
@CedrickFlocon I don't seem to be getting any mails after signing up, is there any other way to get the apk?

**Comment by BMicraft** [comment]
Now the app tells me I need to enable `mobile_app` integration even though I am using `default_config:` and already have third party clients in the mobile app integration

If it is of any use here is my [nginx proxy config](https://github.com/home-assistant/home-assistant-android/files/3883955/home.assistant.nginx.proxy.conf.txt)

**Comment by CedrickFlocon** [comment]
Fix firebase App distribution : https://github.com/home-assistant/home-assistant-android/pull/62

**Comment by CedrickFlocon** [comment]
I think you should be able to skip the integration screen.

> Now the app tells me I need to enable `mobile_app` integration even though I am using `default_config:` and already have third party clients in the mobile app integration
> 
> If it is of any use here is my [nginx proxy config](https://github.com/home-assistant/home-assistant-android/files/3883955/home.assistant.nginx.proxy.conf.txt)

**Comment by BMicraft** [comment]
> I think you should be able to skip the integration screen.

Oh you're right, I totally missed that. Now I have to login again? It seems to be working though.

**Comment by CedrickFlocon** [comment]
I let you close this if it has been fixed

**Comment by BMicraft** [comment]
Hold up, it looks like closing the app is logging me out.

**Comment by CedrickFlocon** [comment]
If it's a new bug could you close this one and open a new issue. 
BTW try to uninstall the application and instakk it again

**Comment by BMicraft** [comment]
Okay I installed the apk `#22` from Firebase after uninstalling my build but my previous comment still applies.
I will open a new issue about that though. Would that be related to the failing mobile integration sign-up or is that a different issue?
