### ISSUE TITLE
Feature request: Tasker integration

### ISSUE THREAD

**Issue by Nossnevs** [home-assistant/home-assistant-android#58]
Tasker is very popular and can be used to automate things on Android phones. 

This app might have the same feature set in the future but in the mean time you could integrate with tasker.

**Comment by balloob** [comment]
There is also a standalone tasker app that integrates Home Assistant. Tasker integration is out of scope for this app.

**Comment by poelzi** [comment]
@balloob this standalone app works so good, that I use plain HTTP requests instead.
