### ISSUE TITLE
Add option for fullscreen mode 

### ISSUE THREAD

**Issue by Nihvel** [home-assistant/home-assistant-android#59]
As opposite to this: https://github.com/home-assistant/home-assistant-android/issues/26 there should be an option for going fullscreen and hide both the _status bar_ and _navigation bar_.

**Comment by balloob** [comment]
This is not a feature that the Home Assistant frontend, which is what shows the UI in the app, supports natively.

**Comment by barrymossel** [comment]
Wouldn't this be possible?
https://developer.android.com/training/system-ui/navigation

**Comment by Nihvel** [comment]
I agree with the reply above. The Android app should support features that are not found within HA itself, such as Kiosk mode without using CCH (therefore Fully Kiosk Browser app). 

If the scope of the app is opening a webpage to HA I can as well open it thru a Chrome Tab (or the app above). Else makes no sense to have an app for it. My 2 cents.

**Comment by barrymossel** [comment]
> Closing in favor of #59

But that one is closed, right. Thought no-one would look there anyway. And I believe the question is mis-understood there. Not the UI should be fullscreen, but rather the app (so the shell). The UI will adapt to the shell anyway I reckon, just like on a monitor...
