### ISSUE TITLE
Add zeroconf/mdns discovery

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#6]
Discovery is currently stubbed out. Home Assistant is discoverable on `_home-assistant._tcp.local.`

**Comment by RussNelson** [comment]
If it's stubbed out, then why does it say that it's attempting to scan? This is confusing as heck.

**Comment by marciogranzotto** [comment]
I made a preliminary implementation of mdns search. But I still need to structure it a little better before opening a PR

**Comment by marciogranzotto** [comment]
Question about mdns.
When I find a mDNS record on my network, this is what android returns me:
```
BonjourService{flags=2, domain='local.', regType='_home-assistant._tcp.', serviceName='Home', dnsRecords={base_url=https://RETRACTED.duckdns.org, version=0.102.3, requires_api_password=true}, ifIndex=9, hostname='Home._home-assistant._tcp.local.', port=8123}
192.168.1.133
```
The thing is, using my `duckdns` external URL, I'm remapping the port to `1220`, so if I would use that URL with the port that mDNS returns, it wouldn't work.
If I use the discovered IP address, and the port, it will work. But I have no way to know if `ssl` is required or not...

Should I just assume that `http://IPADDRESS:PORT` works?

**Comment by balloob** [comment]
You should update your config to make sure that your base url includes the port that you use.

We should initially try to connect to the base url. 

If that won't work, we can do the `http://IPADDRESS:PORT` but it means we need to disable SSL verification in case the user uses Let's Encrypt (hence why we should use the base url)

**Comment by marciogranzotto** [comment]
If the base URL fails, I can also check if starts with `https` and use that with the IP address

**Comment by balloob** [comment]
@marciogranzotto have you made progress on your implementation ?
