### ISSUE TITLE
Play Store - add instructions how to connect if scan doesn't work

### ISSUE THREAD

**Issue by aisbergde** [home-assistant/home-assistant-android#63]
Scan doesn't find the instance.
When I manually enter some URL (local network, duckdns, with or without port) nothing will be found, I get only error messages . This normally will result in a bad rating.
I suggest to add some more instructions how to use the app, what are the requirements for a successful scan, what to try if scan doesn't work.

**Comment by CedrickFlocon** [comment]
https://github.com/home-assistant/home-assistant-android/issues/6

**Comment by aisbergde** [comment]
manual entering the URL also will not find it. But it looks that some users are able to manual enter. 
That's why I suggest to add some information about the requirements and the format how to enter the URL manually. I would like to test the app, but I can't if I can't connect.

**Comment by CedrickFlocon** [comment]
Some help to enter the url : https://github.com/home-assistant/home-assistant-android/pull/66

**Comment by trrevvorr** [comment]
Here's what I tried:
- automatic scan - failed
- manually enter `hassio.local:8123` - failed, couldn't click button
- manually enter `http://hassio.local:8123` - failed with error message
- manually enter eternal url (hosted via nabu casa) - worked!

**Comment by balloob** [comment]
Android does not support zeroconf/mdns, so `hassio.local` does not work. Once we add #6, we will find it.

**Comment by RussNelson** [comment]
http://10.0.1.7:8123 doesn't work in the app. It works from my desktop's browser.

**Comment by barrymossel** [comment]
Might be the same issue as mine: https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/9/8/9806d0a94945806a242e148f0b0fde6a0257053b.jpeg

**Comment by balloob** [comment]
Example has been added and will be in next release.
