### ISSUE TITLE
Unable to connect to HA instance

### ISSUE THREAD

**Issue by SeafireGit** [home-assistant/home-assistant-android#64]
Hello,
I installed the app, and am now unable to connect to my instance.
In the connection setting tab, I put the ip of my instance. I only use HA on local network, with no ssl, on standard port. 

When connecting to @ip:8123 I reach the credential page, but then it loops back to credential part. Connecting to other port doesn't work. 

I'm using Huawei and android 8.

Any guess? Or any information I can provide?

**Comment by SeafireGit** [comment]
I forgot to mention I use a fresh install of Ha 102.1 through Hass.io

**Comment by SeafireGit** [comment]
Same issue with 102.2 :(

**Comment by balloob** [comment]
You need to make sure you add protocol too, so make sure it includes `http://`

**Comment by SeafireGit** [comment]
Same result, but it works without, as I can reach the Auth page.

Here are some log from the app itself :
1202 20:43:09 [Debug] :  AppLifecycleState.inactive
1202 20:43:09 [Debug] :  AppLifecycleState.resumed
1202 20:43:09 [Debug] :  AppLifecycleState.inactive
1202 20:43:09 [Error] :  Loading settings...
1202 20:43:09 [Error] :  Long-lived token read successful
1202 20:43:09 [Debug] :  Launching OAuth
1202 20:43:09 [Debug] :  AppLifecycleState.resumed
1202 20:43:09 [Debug] :  AppLifecycleState.inactive
1202 20:43:10 [Debug] :  AppLifecycleState.paused
1202 20:43:11 [Debug] :  AppLifecycleState.inactive
1202 20:43:11 [Debug] :  AppLifecycleState.resumed
1202 20:43:20 [Debug] :  Launching OAuth
1202 20:43:20 [Debug] :  AppLifecycleState.inactive
1202 20:43:21 [Debug] :  AppLifecycleState.paused
1202 20:43:23 [Debug] :  AppLifecycleState.inactive
1202 20:43:23 [Debug] :  AppLifecycleState.resumed
1202 20:43:25 [Debug] :  AppLifecycleState.inactive
1202 20:43:26 [Debug] :  AppLifecycleState.resumed

**Comment by balloob** [comment]
This needs more information. what is the exact url that you enter, what auth providers do you have and please show a screenshot of what you mean of "loop back" credential part. And which phone ?

**Comment by balloob** [comment]
Upgrade to the latest 1.1.1 release and see if the issue persists.

**Comment by pepeEL** [comment]
I have installed clean Version 1.1.1(32) and still dont find my instance in my home network

When use manually configuration and Type address http://IP:8123 all work ok
But auto no working. 
My Phone Huawei P20 with Android 9.1

**Comment by Aquarito** [comment]
I've got a similar problem:
- App doesn't find my Home Assistant instance
- when entering the adress manually it get a blank screen. Tried it with https://<ip>:8123 and https://<hostname>:8123
- works when using the Nabu Casa URL

Is there some kind of SSL certificate check active? My certificate's hostname doesn't match the hostname in my LAN. Only guessing.. ;)

Phone is a Xiaomi Mi9T Pro on MIUI 11 (Android 10)

**Comment by Bruceforce** [comment]
I'm having the same issue as @Aquarito 
I'm running the latest version of home Assistant in a docker container with self signed (but trusted on Android) certificates. The HA app can't find my instance in lan and if I enter https://IP:8123 manually I get a blank (white) screen and nothing happens. If I enter the same url in Chrome it redirects me to the auth page correctly.

**Comment by msgongora** [comment]
I'm not sure if what I'm getting it's related to this issue, but I changed the IP of my HA and now I can't use the app. I got same error if for some reason the HA is accessible within my network. At this point I think I'll be fine clearing the cache to get the authentication page again, but I guess this logic have to change.
![Screenshot_20191214-220432](https://user-images.githubusercontent.com/2498591/70868763-ed2a3600-1f51-11ea-8ac7-10fdacb73252.png)

**Comment by balloob** [comment]
I am going to close this issue as every poster seems to have a different problem and original reporter has not come back. 

Please retest with latest app version. If you change IP, there is no log out button yet and there is already an issue for it. (can't find it right now soo)
