### ISSUE TITLE
Animated images doesn't show

### ISSUE THREAD

**Issue by andriej** [home-assistant/home-assistant-android#67]
In UI I have weather card with animated images used for current and forecasted conditions.
Those images do not load on same connection (internal and external) on which direct shortcut on Android work flawlessly.

I'm using latest firebase version (26).

**Comment by dshokouhi** [comment]
are you sure its firebase version 26? I only show 22 and 23.  I find it helpful to check the version under App Configuration when you load the app and hit the menu.

**Comment by andriej** [comment]
It was before the first coffee, it's 22.

**Comment by JBassett** [comment]
Is this still an issue on the latest builds?  If it is could we more info on how you are connecting to HA (http vs https) and where the images are hosted with urls?

**Comment by andriej** [comment]
Forgot to close it - on my side at least the issue was with weather card. I've moved to the new one from HACS and it worked in meanwhile.
