### ISSUE TITLE
Jackson-module-kotlin Android compatibility

### ISSUE THREAD

**Issue by CedrickFlocon** [home-assistant/home-assistant-android#68]
According to this [issue](https://github.com/FasterXML/jackson-module-kotlin/issues/218) Jackson module kotlin 2.9.10 is only compatible with Android >= 24

Stack Trace
>Fatal Exception: java.lang.NoSuchMethodError
No virtual method getAnnotationsByType(Ljava/lang/Class;)[Ljava/lang/annotation/Annotation; in class Ljava/lang/reflect/Method; or its super classes (declaration of 'java.lang.reflect.Method' appears in /system/framework/core-libart.jar)
com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.isRequiredByAnnotation (KotlinAnnotationIntrospector.kt:61)
com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.hasRequiredMarker (KotlinAnnotationIntrospector.kt:68)
com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.access$hasRequiredMarker (KotlinAnnotationIntrospector.kt:23)

**Comment by JBassett** [comment]
According to the issue you linked to the PR it looks like they are going to be fixing this in the library.  I don't think we should revert to manually mapping the objects.  We can downgrade to 2.9.6 as referenced here: https://github.com/FasterXML/jackson-module-kotlin/issues/218#issuecomment-470900330  until a new 2.10 release is create.

**Comment by CedrickFlocon** [comment]
I need more coffee ...
It's look like [2.10](https://github.com/FasterXML/jackson-module-kotlin/releases/tag/jackson-module-kotlin-2.10.0) has been released.
Let try this update

**Comment by marciogranzotto** [comment]
There's also [Moshi](https://github.com/square/moshi) which seems to have great Kotlin support. I haven't used it though.
