### ISSUE TITLE
Has a 'beta' channel been suggested for Google Play?

### ISSUE THREAD

**Issue by Knoxie** [home-assistant/home-assistant-android#70]
Might be nice to setup a beta channel for people to use with Google Play so that more people can test new changes without needing Android Studio or knowledge of building the app from scratch to test it as it develops.

**Comment by dshokouhi** [comment]
Have you seen the firebase link in the readme?

https://github.com/home-assistant/home-assistant-android#continuous-integration

**Comment by Knoxie** [comment]
I did not, But i still think a beta channel is a good idea moving forward. Easier for people to manage if everything is based from Google Play.

**Comment by andriej** [comment]
+++1 - it's much easier to participate as beta-tester within 'beta' Google Play channel.
I'd really love to support with reporting issues thru Google Play.

**Comment by bieniu** [comment]
+1

**Comment by mediacowboy** [comment]
I think a beta channel on google is a great idea. ++++1 for me

**Comment by balloob** [comment]
Do not post +1 comments, they will be deleted.

**Comment by balloob** [comment]
We're going to stick for now with just Firebase test apps for now.
