### ISSUE TITLE
No connection timeout if current instance url no longer reachable

### ISSUE THREAD

**Issue by mattlward** [home-assistant/home-assistant-android#71]
I just managed to get a connection via my VPN to home.  I disconnected the VPN and wanted to try my external host name and cannot get to the manual address screen now.  It wants to continue using the manual ip address with the VPN connection.

Is there a way short of uninstalling the app and re-installing it to get a fresh line for a manual addition?

I do get a connection error that the web page is not available after a long delay.

**Comment by balloob** [comment]
Ah. Yes this is an interesting one. Normally we would want people to use the logout function in the UI, but if the UI cannot show, we should provide an alternative.

We send [connection status](https://developers.home-assistant.io/docs/en/frontend_external_bus.html#connection-status-update-connection-status) updates from the UI once it is loaded, so we should automatically open a profile management screen if we don't get a report within 5 seconds of opening the UI.

**Comment by mattlward** [comment]
That would be great!  If a person could save an internal url and an external url, it would be even better.  Just pick the one you need.
