### ISSUE TITLE
Don't allow user to press back to log out

### ISSUE THREAD

**Issue by Kisty** [home-assistant/home-assistant-android#76]
First off, this is great to see an official HA app. Well done! 👏👏👏 

I found that by pressing back too many times logged me out of HA. This is a UX bug. See #75.

**Comment by quthla** [comment]
This is a frontend issue so must be fixed there.

**Comment by balloob** [comment]
Shouldn't we just start a new webview for the website, so there is no history of the login page to back to. 

The person didn't get logged out but just navigated back to the login page. Killing app and reopening would have solved it.

**Comment by andriej** [comment]
It would, it happened to mee too.

**Comment by quthla** [comment]
> Shouldn't we just start a new webview for the website, so there is no history of the login page to back to.
> 
> The person didn't get logged out but just navigated back to the login page. Killing app and reopening would have solved it.

I think the issue is rather that when navigating back from an external page to a HA page, the frontend will not ask the the app for authentication again and just show the login.

**Comment by balloob** [comment]
#75 will help.

The issue is that we change the url and it forgets it was using external auth. Indeed a frontend issue. I wonder if we need to chanfe how we detect external auth. Maybe we should check if some JS object exists instead?

**Comment by quthla** [comment]
> #75 will help.
> 
> The issue is that we change the url and it forgets it was using external auth. Indeed a frontend issue. I wonder if we need to chanfe how we detect external auth. Maybe we should check if some JS object exists instead?

You could try checking if the externalApp interface is present.

**Comment by andriej** [comment]
It happened to me also on "new ui available" and reload of lovelace. After refresh - login screen. Killing app and reopening fixed situation.

**Comment by balloob** [comment]
Fixes in https://github.com/home-assistant/home-assistant-polymer/pull/4280
