### ISSUE TITLE
App not available at Play Store

### ISSUE THREAD

**Issue by javicalle** [home-assistant/home-assistant-android#78]
When I search at Play Store, I can't find the app.
If I go through the link:
* https://play.google.com/store/apps/details?id=io.homeassistant.companion.android

what I found is "This app is not avaliable":

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/optimized/3X/a/6/a63afba316e7b5a835a7be4e8c8c8b91ed03c4b3_2_393x500.png)

If I look at the code ([here ](https://github.com/home-assistant/home-assistant-android/blob/master/app/build.gradle)and [here](https://github.com/home-assistant/home-assistant-android/blob/master/gradle/dependencies.gradle)), `minsSdkVersion` should be Android 5.0:
```
    defaultConfig {
        applicationId "io.homeassistant.companion.android"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode "${System.env.VERSION_CODE ?: 1}".toInteger()
        versionName "1.0.0"
    }
```

My mobile phone is Android 6.0.1 (Cyanogen 13.1.2)

Why may the application not be available to me?

Thanks in advance.

**Comment by CedrickFlocon** [comment]
To be able to publish it for the [State of the union](https://www.home-assistant.io/blog/2019/11/22/state-of-the-union/#android-app) we decide to target only adult user (faster review from the playstore). Could it be the issue ?
@balloob I think we can update it ?
>Target audience and content
Target age
The target age group for your app is: 18 and over

**Comment by javicalle** [comment]
I don't think that is the reason, I think I am adult enough ;-p

Maybe some Google device certification issue? Some apps are not avaliable because device/OS is not Google certified, (like Netflix).

**Comment by balloob** [comment]
I'm fine with updating the audience if that fixes it, but doesn't seem like it's the issue in this case. Want me to still update it ? 

I don't know if there are any toggles for allowing uncertified devices? I was under the impression that anything with Play Store was certified.

**Comment by allanpersson** [comment]
@balloob could it be a country/region restriction? Without knowing if it's the problem here I could imaging countries like China, Hong Kong, Russian etc would block certain apps/services like they do with other "it stuff".

Maybe @javicalle could come with more detailed information about device/os/region etc to be able to solve the problem and be one step ahead if there is some limitations of the app.

**Comment by javicalle** [comment]
@allanpersson sure, here is the information:
Device: Oneplus One
OS: Cyanogen 13.1.2
Android version: 6.0.1
Play Protect: device certified 

Any other information that can be relevant?

**Comment by Kisty** [comment]
Can you download any other apps? Might be that Google Play aren't allowing download because it's Cyanogen and rooted (is it rooted?) If not I can't see any reason either! Looked at merged manifest and nothing.

**Comment by javicalle** [comment]
Just to say thanks to @Kisty 

By the way, I am able to download and install the app from the [Firebase App Distribution](https://appdistribution.firebase.dev/i/8zf5W4zz)
Installed and working without problems.
