### ISSUE TITLE
App crashes if logged in but refresh token revoked on the server side

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/home-assistant-android#79]
Hi there,

I might have found a bug or "missbehaviour" on the Android App.

I was cleaning up the "Refresh Tokens" list and doing that I also removed the one for the Android App.

What I noticed from that is that my Chrome Home linked site was banned right after and once the ban was removed I was able to login again.

On the Android App it doesn't open anymore, or to better say, it does open but it crash right after.

I am about to send the feedback via phone and I will add in the description this GitHub ticket number to give some background information.

I am running HA in Python Env on the latest stable version 0.102.2 on an Intel NUC with CentOS 7

Hope it helps :)
Cheers
Andrea

**Comment by balloob** [comment]
If we refresh the token and we get a 400 status back, we should check the response in JSON. It is in the format `{ "error": "<error_code>"}`. If `<error_code>` is `invalid_grant`, we should log the user out.

**Comment by SeLLeRoNe** [comment]
Not sure the fact this issue was closed meant it was part of yesterday's release, if so, it isn't working.
To have the problem fixed I literally had to uninstall and reinstall the App, so that the initialization started again.
