### ISSUE TITLE
App crashes when certificate has expired

### ISSUE THREAD

**Issue by patricf** [home-assistant/home-assistant-android#81]
I just noticed that the app crashes immediately when the certificate has expired.
After crashing a few times I got an option to send feedback but I couldn't copy the stack trace. It said something about: `CertPathValidatorException: Trust anchor for certification path not found. `

I sent the feedback but don't know if it goes to you or Google. 

Getting an error message in the app would be preferred.

Edit:
Attaching screenshot of stack trace. 
![Screenshot_20191130-132922](https://user-images.githubusercontent.com/254333/69900576-962f3900-1375-11ea-8bc2-e7a8e6facc4c.jpg)

**Comment by JBassett** [comment]
This should now bring you to settings so you can change urls.
