### ISSUE TITLE
Check if android device is on same network as HA to show 'At home' and pause location tracking

### ISSUE THREAD

**Issue by selinium** [home-assistant/home-assistant-android#83]
If the Android app can see the Home Assistant instance, perhaps using mDNS, on the local network it could determine it is 'At home' and notify HA.

This could also pause location tracking.

This feature could be used without location tracking if the user only cares about whether users are at home.

**Comment by balloob** [comment]
location tracking is also reporting battery status, and might include other info too. So pausing it might not be ideal.

**Comment by blakeblackshear** [comment]
I think it would be better to continue reporting location as an additional or alternative device tracker to a router integration. No need to fetch GPS though.

**Comment by JBassett** [comment]
If you only want changes of zones we now have a setting for that via: https://github.com/home-assistant/home-assistant-android/pull/129
