### ISSUE TITLE
Migrate to a MaterialComponents Theme

### ISSUE THREAD

**Issue by gabrielemariotti** [home-assistant/home-assistant-android#84]
Using the [Material Components Library](https://github.com/material-components/material-components-android) you [shouldn't use](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#4-change-your-app-theme-to-inherit-from-a-material-components-theme) an `AppCompat` Theme.

> Doing an app-wide migration by changing your app theme to inherit from a **Material Components theme** is the recommended approach. However, be sure to test thoroughly afterwards, as components in existing layouts may change their looks and behavior.
>Note: If you can't change your theme, you can do one of the following:
> - Inherit from one of our Material Components Bridge themes. See the Bridge Themes section for more details.
> - Continue to inherit from an AppCompat theme and add some new theme attributes to your theme. See the App Compat Themes section for more details.

**Comment by Boduc** [comment]
#199

**Comment by Boduc** [comment]
#199

**Comment by asadayut027** [comment]
hi bae

**Comment by rajput306** [comment]
thanks for this [information](http://www.cremeitalia.com/).

**Comment by wilmardo** [comment]
This is closed by #157 right?
