### ISSUE TITLE
Firebase App Distribution Link broken 

### ISSUE THREAD

**Issue by BCNelson** [home-assistant/home-assistant-android#85]
The link for me takes me to the page then has me enter my email. I then get an error saying that the link is invalid

Invalid link
The link you're trying to access is no longer available

**Comment by CedrickFlocon** [comment]
I have updated the link one or two week ago. 
Did you try the new one (in the readme on the master branch)

**Comment by balloob** [comment]
I just tried it and it works.

**Comment by JBassett** [comment]
Appears to be working.
