### ISSUE TITLE
Device Tracking Settings Needed

### ISSUE THREAD

**Issue by Knoxie** [home-assistant/home-assistant-android#86]
- Turn tracking on/off
- Allow device naming
- Turn on/off battery tracking
- Location accuracy setting (Gps/wifi/cellular)
- Limit updates to time/distance changed

**Comment by balloob** [comment]
We shouldn't get a lot of different options. So let's not add ability to turn off battery tracking. We just always include it. 

I think that we should just start with on/off.

**Comment by aleksandrov1995** [comment]
@balloob I do agree with that, however, in my opinion a good setting besides on/off would be, how often to report location. Moreover, I an option to disable the location tracking when at home ( e.g. connected to home WiFi or as it was previously mentioned if the app sees HA on the network, although this is a bit of a personal preference, which I do think a few people will benefit from).

Regards

**Comment by dshokouhi** [comment]
It would be neat if we add a setting for a stationary device like a tablet that never leaves the home.  You don't really need to know its GPS coordinates but you do want things like battery.
