### ISSUE TITLE
Onboarding registers twice with Home Assistant

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#89]
The onboarding registration activity kicks off registration in [`onResume()`](https://github.com/home-assistant/home-assistant-android/blob/master/app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt#L70-L73).

Once registration is done, it will show a location permission dialog. Once the user approves, we get back to the registration activity, kicking off the `onResume()` again. This causes two config entries to be created.

In Home Assisstant:
![image](https://user-images.githubusercontent.com/1444314/70098750-c418b580-15e1-11ea-9e0f-00e755a15a40.png)

CC @JBassett

**Comment by JBassett** [comment]
Going to get a fix out as soon as I can get the kids to bed!
