### ISSUE TITLE
Alert window doesn't has correct title or button

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#90]
When the frontend uses the JavaScript `alert()`, it shows an alert to the user with the wrong title and a missing caption for the OK button (button does work).

![image](https://user-images.githubusercontent.com/1444314/70098768-d692ef00-15e1-11ea-9cf8-b0be140abec2.png)

**Comment by balloob** [comment]
@gmatyszczak does this also fix the `%s` or should I open a new issue for that?

**Comment by gmatyszczak** [comment]
I couldn't reproduce the issue with `%s`. Could you provide steps? Or retest it on your side?

**Comment by balloob** [comment]
Cannot reproduce either anymore. Perfect !
