### ISSUE TITLE
Input for manual entering HASS url has placeholder set as label

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#91]
The input to enter the HASS url has the placeholder set as label, causing the example to float above the input field when the user is entering their url.

![image](https://user-images.githubusercontent.com/1444314/70098853-2671b600-15e2-11ea-84c7-324dafd84905.png)

This should be set as the placeholder instead.

**Comment by CedrickFlocon** [comment]
It's the defaut behaviour of a textinputlayout.
![wtGwu](https://user-images.githubusercontent.com/7161169/70119241-1dc4c280-166a-11ea-8f8f-3104cf58fade.gif)

**Comment by balloob** [comment]
hmm are there no different labels and placeholders? In that case the label should become "Home Assistant URL" and maybe we add a text below ?

**Comment by balloob** [comment]
Docs: https://material.io/develop/android/components/text-input-layout/

So there is "Hint" and "Helper Text". I think that the URL should be in the helper text?

**Comment by CedrickFlocon** [comment]
good point we could use the helper text
how it's look like => https://miro.medium.com/max/640/1*J8ErKkHq7VUfuXyMZY1gaQ.gif

**Comment by quthla** [comment]
https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout.html#attr_TextInputLayout_hintAnimationEnabled
