### ISSUE TITLE
Use remote UI for webview if available

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-android#92]
If app receives a remote UI during app registration, use that url for the webview.

Step 2 will be to only do that if you're not at home but that's out of scope for this issue.

**Comment by balloob** [comment]
This should be fixed by setting the correct url here: https://github.com/home-assistant/home-assistant-android/blob/ab602bca4f7a4e1ad87684ee2155fbb072bff248/app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt#L24-L27

We should do that by checking if it's in storage, like this code snippet. If it is, use that instead of the authentication url. https://github.com/home-assistant/home-assistant-android/blob/4f34a9b67f542b6d414aab9da50f03c9ac5d8b46/data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt#L166

**Comment by quthla** [comment]
It should be considered to implement this together with the internal / external URL feature the iOS app has. That is also planned for the Android app and could reuse some of the code for remote UI.

**Comment by balloob** [comment]
I disagree. This on its own is already adding value.
