### ISSUE TITLE
How to remove multiple device trackers from Devices

### ISSUE THREAD

**Issue by aleksandrov1995** [home-assistant/home-assistant-android#98]
I suppose the last release fixes the issue, but please let me know how to remove the previous added device trackers.

![Screenshot_20191204-094116_Home Assistant](https://user-images.githubusercontent.com/12535078/70123010-6ab09500-167a-11ea-932e-e882f4c14205.jpg)

**Comment by JBassett** [comment]
If you go to the Integrations screen you will see multiple instances of `Mobile App: PHONE_TYPE`.  You can remove the unused instances of the integration.  That will leave you with 2 `devices`.  This PR: https://github.com/home-assistant/home-assistant/pull/29173 fixes the two devices per mobile app integration.

**Comment by balloob** [comment]
That fix has been released to the app store as 1.1.1 👍
