### ISSUE TITLE
Unable to connect to HA

### ISSUE THREAD

**Issue by escoand** [home-assistant/home-assistant-android#99]
I've upgraded the app to 1.1.1 and try to reconnect my HA instance. Now I always see a message in the login screen:

```
Du bist dabei, https://home-assistant.io/android Zugriff auf deine Home Assistant Instanz zu gewähren.

Anmeldung mit Home Assistant Local.

Error: invalid client id or redirect uri
```

**Comment by balloob** [comment]
Is your Home Assistant instance able to connect to the internet?

**Comment by balloob** [comment]
Home Assistant needs to be able to verify that client ID `https://home-assistant.io/android` is able to use the `homeassistant://auth-callback` redirect URI. It does so by looking for `<link rel="redirect_uri">` on https://home-assistant.io/android. This is specified by [IndieAuth](https://www.w3.org/TR/indieauth/).

If Home Assistant is unable to do this, it will mark it as an invalid redirect uri. We could be better with our error messages.

**Comment by robbiet480** [comment]
[This bit of the companion docs](https://companion.home-assistant.io/en/troubleshooting/errors#invalid-client-id-or-redirect-uri--or--os-error-while-looking-up-redirect_uri) may be helpful.

**Comment by escoand** [comment]
Hmm, got it working but had to stop eth0 and just use wlan0. When using both I'm not able to connect with curl to home-assistant.io - it's timing out. Is this a known issue on hassio and rpi?

**Comment by balloob** [comment]
I'm thinking that we should hardcode allowed redirect URI for iOS and Android in Home Assistant, so it won't require the internet.
